### ISSUE TITLE
Hacktoberfest 2022

### ISSUE THREAD

**Issue by blaiseAI** [swapagarwal/swag-for-dev#1003]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Digital Ocean

Q. Where have you seen the announcement (URL)?  
A. : https://hacktoberfest.digitalocean.com

Q. What kind of swag (clothing, stickers, ...)?  
A. : Hacktoberfest 2022 t-shirt

Q. Have you received swag from this?  
A. : Yes, Previous years

Q. How long did it take?  
A. : 3-5 Weeks

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
