### ISSUE TITLE
[Hacktoberfest]  Medusa swag oppotunity in October

### ISSUE THREAD

**Issue by aashishpanthi** [swapagarwal/swag-for-dev#1009]
## Wild swag opportunity appeared!

- [X] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : [Medusajs](https://medusajs.com/) offers it for the hacktoberfest.

Q. Where have you seen the announcement (URL)?  
A. : https://medusajs.com/blog/medusa-hackathon/

Q. What kind of swag (clothing, stickers, ...)?  
A. : Medusa tee (clothing) + Medusa hoodie (clothing) + Medusa stickers

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : Yes

You can even win cash prizes up to $1500 by participating in their hackathon.
Otherwise, you can win swag from medusa by contributing.

- 1 PR ⇒ Medusa sticker
- 3 PRs ⇒ Medusa tee + Medusa stickers
- 5 PRs ⇒ Medusa tee + Medusa hoodie + Medusa stickers

- [X] I've checked that the promotion is legit.
- [X] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
