### ISSUE TITLE
Highlight new swag opportunities

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/swag-for-dev#101]
We can add some kind of sticker to one of the image corners to denote that this is a new swag opportunity. Alternatively, it can be added in sorting logic, i.e. show in order of date added. Thoughts?

**Comment by plibither8** [comment]
On a similar note, why not add the date the swag was created/added? It can be something like:
> *Added on: 34th May, 2034*

**Comment by qhieu45** [comment]
@swapagarwal I can work on this but we need to define what is new swag opportunities. 
We don't have any data yet on date added. We can start adding them indeed. 
What do we do with the ones that were added before?

**Comment by swapagarwal** [comment]
@qhieu45 `dateAdded` is now available for all items!
A first proposal can be something like consider the latest 3 items added in the last 30 days as new and highlight them. Let's keep the numbers configurable and tweak with feedback from others.

**Comment by swapagarwal** [comment]
Changed default sorting to show new items first.
