### ISSUE TITLE
[Hacktoberfest] Hashnode swag oppurtinuty for bloggers (every month)

### ISSUE THREAD

**Issue by aashishpanthi** [swapagarwal/swag-for-dev#1011]
## Wild swag opportunity appeared!

- [X] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Hashnode and Community classroom.

Q. Where have you seen the announcement (URL)?  
A. : https://www.commclassroom.org/hashnode

Q. What kind of swag (clothing, stickers, ...)?  
A. : Clothing (Hashnode T-shirt) + Stickers (Hashnode stickers) + Prize or gadgets

Q. Have you received swag from this?  
A. : Yes

Q. How long did it take?  
A. : 20 days

Q. Does it ship worldwide?  
A. : Yes

You can write blogs on hashnode.com on the tracks provided and get a chance to win a grand prize or track winner swag every month.

- [X] I've checked that the promotion is legit.
- [X] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
