### ISSUE TITLE
Hacktoberfest 2022

### ISSUE THREAD

**Issue by Shubhada510** [swapagarwal/swag-for-dev#1013]
## Wild swag opportunity appeared!

- [ ✓] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Digital Ocean

Q. Where have you seen the announcement (URL)?  
A. : https://hacktoberfest.com/participation/#beginner-resources

Q. What kind of swag (clothing, stickers, ...)?  
A. : The first 40,000 participants (maintainers and contributors) who complete Hacktoberfest can elect to receive one of two prizes: a tree planted in their name, or the Hacktoberfest 2022 t-shirt

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : 1 month ( October) 

Q. Does it ship worldwide?  
A. : Yes

- [ ✓] I've checked that the promotion is legit.
- [ ✓ I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
