### ISSUE TITLE
Geeks for geeks : Problem of the Day Challenge

### ISSUE THREAD

**Issue by Shubhada510** [swapagarwal/swag-for-dev#1014]
## Wild swag opportunity appeared!

- [✓ ] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Geeksforgeeks

Q. Where have you seen the announcement (URL)?  
A. : https://practice.geeksforgeeks.org/problem-of-the-day

Q. What kind of swag (clothing, stickers, ...)?  
A. : Anything of our choice among GFG merchandise, Discount on Gfg courses, Annual GFG premium subscription

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : Till you complete the challenge

Q. Does it ship worldwide?  
A. : No

- [✓ ] I've checked that the promotion is legit.
- [✓ ] I've checked that it's still available to the public.

**Comment by Aryan1982** [comment]
Is anyone working on it?

**Comment by aslafy-z** [comment]
We cannot accept this kind of contest. Thank you for the proposal.

**Comment by aslafy-z** [comment]
Ok, as I understood, it's not a contest. Feel free to open a PR for this!

**Comment by rahulkundu1209** [comment]
Hey @aslafy-z assign me the issue.

**Comment by aslafy-z** [comment]
@rahulkundu1209 done!
