### ISSUE TITLE
Geeksforgeeks : Interview Series Challenge

### ISSUE THREAD

**Issue by Shubhada510** [swapagarwal/swag-for-dev#1015]
## Wild swag opportunity appeared!

- [✓] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Geeksforgeeks

Q. Where have you seen the announcement (URL)?  
A. :https://www.geeksforgeeks.org/crack-the-coding-interview-with-geeksforgeeks-weekly-contest-series/

Q. What kind of swag (clothing, stickers, ...)?  
A. : Clothing, Stickers, Accesories

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : Till the challenge continues

Q. Does it ship worldwide?  
A. : No

- [✓] I've checked that the promotion is legit.
- [✓ ] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
We cannot accept this kind of contest. Thank you for the proposal.
