### ISSUE TITLE
[Hacktoberfest] Added developer nation swag opportunity

### ISSUE THREAD

**Issue by utsavbhattarai007** [swapagarwal/swag-for-dev#1018]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. :  Developer nation

Q. Where have you seen the announcement (URL)?  
A. :  https://content.developernation.net/developer-nation-newsletter-signup-form

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing

Q. Have you received swag from this?  
A. : yes

Q. How long did it take?  
A. : 20-30 days

Q. Does it ship worldwide?  
A. : yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by biswajeetbehera123** [comment]
I can start working on this if you assign me to this issue @utsavbhattarai007

**Comment by aslafy-z** [comment]
I could not find any clothing swag opportunity on this website. Closing this issue. Feel free to contribute on some other @biswajeetbehera123
