### ISSUE TITLE
InfluxData Challenge

### ISSUE THREAD

**Issue by jpdias** [swapagarwal/swag-for-dev#1021]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : InfluxData

Q. Where have you seen the announcement (URL)?  
A. : [https://www.influxdata.com/influxdb-challenge/](https://www.influxdata.com/influxdb-challenge/)

Q. What kind of swag (clothing, stickers, ...)?  
A. : Clothing (socks, tshirt)

Q. Have you received swag from this?  
A. : Not yet.

Q. How long did it take?  
A. : --

Q. Does it ship worldwide?  
A. : Yes.

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
