### ISSUE TITLE
Images: force jpeg?

### ISSUE THREAD

**Issue by vikaspotluri123** [swapagarwal/swag-for-dev#103]
Refs https://github.com/swapagarwal/swag-for-dev/pull/93#discussion_r223505178

Currently images are forced to be jpegs when they're processed. Given the source hopefully put thought into image type, is it worth forcing the image type to be jpeg?

Even though the site is tiny (500k), what about modern formats, such as progressive jpegs or webp?

**Comment by aslafy-z** [comment]
Just to clarify, images are not forced to be jpegs but they we force the conversion to jpegs (progressive jpegs, see [#93 (diff)](https://github.com/swapagarwal/swag-for-dev/pull/93/files#diff-6eb60389fb540a5c670ae4d43af865a9R19)).

jpeg2000: only safari: https://caniuse.com/jpeg2000
webp: only chrome/opera: https://caniuse.com/webp

webp is coming to firefox and ie but it's very fresh:
https://www.cnet.com/news/firefox-to-support-googles-webp-image-format-for-a-faster-web/
https://www.cnet.com/news/googles-webp-image-format-finally-finds-a-browser-ally-microsoft-edge/

still nothing for safari...

**Comment by aslafy-z** [comment]
WebP support has been integrated. Closing this from now.
