### ISSUE TITLE
Different opportunity for IHP stickers

### ISSUE THREAD

**Issue by MixeroTN** [swapagarwal/swag-for-dev#1061]
- [x] I've checked that this isn't a duplicate issue.

Q. Which opportunity?  
A. : IHP

#675 from 2020 links the announcement in their [GitHub repo](https://github.com/digitallyinduced/ihp#ihp-stickers), but it seems that it no longer exists.

**Instead, I found another method [on their website](https://ihp.digitallyinduced.com/Stickers).**
- [Leave a review about IHP on G2](https://www.g2.com/products/ihp/reviews)
- Send us a quick email with a screenshot of your G2 review to [stickers@digitallyinduced.com](mailto:stickers@digitallyinduced.com). Don't forget to include your postal address :)
- We'll sent out your stickers

I'm not sure if the form from the old announcement still exists and is being processed, which doesn't change the fact that the announcement is most likely gone.

**Comment by aslafy-z** [comment]
Thank you, this was fixed with https://github.com/swapagarwal/swag-for-dev/commit/595541ff2fb9b9a3aff9a563681e5b393bf3ab8c
