### ISSUE TITLE
[Bug] : checkbox background is not fully blue when we select done option. 

### ISSUE THREAD

**Issue by love-sonkar** [swapagarwal/swag-for-dev#1063]
## Issue regarding the website

- [Y] I've checked that this isn't a duplicate issue.

When we select in done checkbox there is a small white dot left it should be blue as background.

## screenshot ##

![white](https://github.com/swapagarwal/swag-for-dev/assets/82786865/a97b8642-3517-4184-a0dd-94ac5f343a65)

i have highlited the error you can see clearly here there is a small white dot left when user checked the boxes the issue remains in all checkbox.

**Comment by Gurjit11** [comment]
Can i contribute to this issue ? please assign it to me

**Comment by love-sonkar** [comment]
I'm working on it bro you can check another issue
