### ISSUE TITLE
[Hacktoberfest] Added a new Appwrite swag opportunity

### ISSUE THREAD

**Issue by shivam200446** [swapagarwal/swag-for-dev#1069]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A.: Appwrite

Q. Where have you seen the announcement (URL)?  
A.: https://appwrite.io/blog/post/hacktoberfest-2023

Q. What kind of swag (clothing, stickers, ...)?  
A.:  Hoodie and stickers 

Q. Have you received swag from this?  
A.: NO yet

Q. How long did it take?  
A.: 4-6 week

Q. Does it ship worldwide?  
A.: yes

Earn an Appwrite hoodie and stickers for contributing only one accepted and merged PR!

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by Anase27** [comment]
what exactly do we need to do here?

**Comment by aslafy-z** [comment]
Resolved with #1070

**Comment by shivam200446** [comment]
@aslafy-z Sir please check Pr I have added info to data.json file
Thanks you.
