### ISSUE TITLE
Can i add a new swag 

### ISSUE THREAD

**Issue by Codebox124** [swapagarwal/swag-for-dev#1071]
## Wild swag opportunity appeared!

- [ ] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : 

Q. Where have you seen the announcement (URL)?  
A. : 

Q. What kind of swag (clothing, stickers, ...)?  
A. : 

Q. Have you received swag from this?  
A. : 

Q. How long did it take?  
A. : 

Q. Does it ship worldwide?  
A. : 

- [ ] I've checked that the promotion is legit.
- [ ] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
Hello @Codebox124 
If you have swag to add, please open an issue and fill up the form, I will then assign you to the issue. Then, you'll be able to open a PR resolving this issue.
