### ISSUE TITLE
[Hacktoberfest] WeMakeDevs and Hashnode swags and accessories opportunity every month 

### ISSUE THREAD

**Issue by aashishpanthi** [swapagarwal/swag-for-dev#1072]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : WeMakeDevs and Hashnode

Q. Where have you seen the announcement (URL)?  
A. : In twitter (X): https://wemakedevs.org/events/hashnode

Q. What kind of swag (clothing, stickers, ...)?  
A. : Clothing and accessories

Q. Have you received swag from this?  
A. : Yes

Q. How long did it take?  
A. : One month

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aashishpanthi** [comment]
Hello can you assign me this issue?

**Comment by aashishpanthi** [comment]
Also, can you add hacktoberfest label?

**Comment by aslafy-z** [comment]
The hacktoberfest label is added at the repository level, there is no need for it to be added to the pull request AFAIK.

**Comment by aslafy-z** [comment]
Closing it as explained in #1074
