### ISSUE TITLE
[Hacktoberfest] Add cloudinary swag opportunity for this year's hacktoberfest

### ISSUE THREAD

**Issue by aashishpanthi** [swapagarwal/swag-for-dev#1075]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Cloudinary

Q. Where have you seen the announcement (URL)?  
A. : Yes, here it is https://cloudinary.com/blog/hacktoberfest-celebrate-open-source-sdks

Q. What kind of swag (clothing, stickers, ...)?  
A. : Clothings, stickers

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aashishpanthi** [comment]
Can anyone assign me this issue?

**Comment by aslafy-z** [comment]
The hacktoberfest label is added at the repository level, there is no need for it to be added to the pull request AFAIK.

Please check your [hacktoberfest profile](https://hacktoberfest.com/profile/), the PR should be marked as WAITING, which means the contribution was taken in account.

**Comment by aashishpanthi** [comment]
> The hacktoberfest label is added at the repository level, there is no need for it to be added to the pull request AFAIK.
> 
> Please check your [hacktoberfest profile](https://hacktoberfest.com/profile/), the PR should be marked as WAITING, which means the contribution was taken in account.

Yes, it is
