### ISSUE TITLE
[Hacktoberfest] IHP stickers no longer valid

### ISSUE THREAD

**Issue by aashishpanthi** [swapagarwal/swag-for-dev#1076]
## Issue with an existing swag opportunity

- [x] I've checked that this isn't a duplicate issue.

Q. Which opportunity?  
A. : IHP stickers

![image](https://github.com/swapagarwal/swag-for-dev/assets/60884239/53db9045-3943-401a-a2be-03cc93bc5fde)
This is an opportunity that isn't valid. It points to a GitHub repo and doesn't have any form to fill out to get the swags. This item needs to be removed.

**Comment by aashishpanthi** [comment]
Please assign me this issue.

**Comment by aslafy-z** [comment]
@aashishpanthi thank you for reporting, I already updated the URL earlier today.
