### ISSUE TITLE
[Hacktoberfest] Add Swag Opportunity for Depth's 30 Days Open Source Learning Challenge

### ISSUE THREAD

**Issue by BandhiyaHardik** [swapagarwal/swag-for-dev#1077]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. :   <a href=https://www.depths.so/>Depths</a>

Q. Where have you seen the announcement (URL)?  
A. :  https://www.depths.so/30daysopensource

Q. What kind of swag (clothing, stickers, ...)?  
A. :  Clothing,Stickers....

Q. Have you received swag from this?  
A. :  No

Q. How long did it take?  
A. :  N/A

Q. Does it ship worldwide?  
A. :  Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
Is this challenge still open to public?
