### ISSUE TITLE
[Hacktoberfest] Add Swag Opportunity for HackSquad

### ISSUE THREAD

**Issue by BandhiyaHardik** [swapagarwal/swag-for-dev#1080]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : <a href="https://www.hacksquad.dev/">HackSquad</a> 

Q. Where have you seen the announcement (URL)?  
A. :  https://www.hacksquad.dev/#swag

Q. What kind of swag (clothing, stickers, ...)?  
A. : Clothing,Sticker,....

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. :   60-180 days after the event ends.

Q. Does it ship worldwide?  
A. : Yes

The top 60 squads will win awesome swag! around ~300 winners!

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by BandhiyaHardik** [comment]
Can anyone assign me this issue?

**Comment by aslafy-z** [comment]
I think there's no swag here..
