### ISSUE TITLE
[Hacktoberfest] Win swag from clik vote. 

### ISSUE THREAD

**Issue by rajeshkhadka200** [swapagarwal/swag-for-dev#1089]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Click vote

Q. Where have you seen the announcement (URL)?  
A. :  GitHub (https://github.com/clickvote/clickvote)

Q. What kind of swag (clothing, stickers, ...)?  
A. : Clothing (T-shirt)

Q. Have you received swag from this?  
A. : NO

Q. How long did it take?  
A. :  3-4 weeks

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by rajeshkhadka200** [comment]
P.S  Can you please assign me this issue?

**Comment by sarojregmi200** [comment]
I Think this issue is inactive, can I be assigned to this issue instead? @aslafy-z.

**Comment by aslafy-z** [comment]
@sarojregmi200 I've seen you opened a ton of new issues, you can start working on one of these and open PRs and I will assign you the issues. Let's wait for @rajeshkhadka200 a bit longer :+1:

**Comment by sarojregmi200** [comment]
@aslafy-z, thanks for the  response. I know @rajeshkhadka200 he is out for a festival he will be on it  soon, if He is unable to do so, I will be happy to take over. 

I am on to the issues, that I have raised.

**Comment by aslafy-z** [comment]
I just assigned you to the issue :+1:

**Comment by BandhiyaHardik** [comment]
@aslafy-z  it's been 4days since you assigned the issue to @sarojregmi200  and there is no PR for this issue. 

can i work on this issue ?

**Comment by aslafy-z** [comment]
Sure, feel free to open PRs for the other open issues if you want :)

**Comment by BandhiyaHardik** [comment]
@aslafy-z  there are some open issues and PR by @rajeshkhadka200  in which the erros are not resolved yet can i open PR for them?

**Comment by BandhiyaHardik** [comment]
@aslafy-z  I think we should not add this swag opportunity. it is limited to 10 person only.


Here's snapshot :
![image](https://github.com/swapagarwal/swag-for-dev/assets/110784317/ec67dce0-cb2c-4c66-b535-a563faf94545)

**Comment by aslafy-z** [comment]
Nice catch @BandhiyaHardik
