### ISSUE TITLE
Share your expreience (Rant) and get free swag. (Stickers and squishy balls)

### ISSUE THREAD

**Issue by sarojregmi200** [swapagarwal/swag-for-dev#1098]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : devRant ()

Q. Where have you seen the announcement (URL)?  
A. : https://devrant.com/free-stickers

Q. What kind of swag (clothing, stickers, ...)?  
A. : stickers and squishy ball

Q. Have you received swag from this?  
A. : No, I don't have enough rant.

Q. How long did it take?  
A. : at most 6 weeks.

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by sarojregmi200** [comment]
And can this issue be assigned to me?

**Comment by aslafy-z** [comment]
Thank you for the proposal, however this opportunity is  already present on the website.
