### ISSUE TITLE
Give your shipping address and participate in the rafle get win a sticker pack.

### ISSUE THREAD

**Issue by sarojregmi200** [swapagarwal/swag-for-dev#1099]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Redwoodjs (https://redwoodjs.com)

Q. Where have you seen the announcement (URL)?  
A. : https://redwoodjs.com/stickers

Q. What kind of swag (clothing, stickers, ...)?  
A. : Stickers

Q. Have you received swag from this?  
A. : No, I have not won the giveaway yet.

Q. How long did it take?  
A. : Unknown.

Q. Does it ship worldwide?  
A. : 

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
Thank you for the proposal, however this opportunity is  already present on the website.
