### ISSUE TITLE
Give a review on DEV's original podcasts and get free stickers.

### ISSUE THREAD

**Issue by sarojregmi200** [swapagarwal/swag-for-dev#1100]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Airtable 

Q. Where have you seen the announcement (URL)?  
A. : https://airtable.com/appfmsPIpnv1la87k/shr8oKAIMZgdYnBxx

Q. What kind of swag (clothing, stickers, ...)?  
A. : Stickers

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : No information.

Q. Does it ship worldwide?  
A. : Yes.
 

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by sarojregmi200** [comment]
And can this issue be assigned to me?

**Comment by aslafy-z** [comment]
Thank you for the proposal, however this opportunity is  already present on the website.
