### ISSUE TITLE
Akto's Swag [Unit Test Failing]

### ISSUE THREAD

**Issue by BandhiyaHardik** [swapagarwal/swag-for-dev#1102]
## Issue with an existing swag opportunity

- [x] I've checked that this isn't a duplicate issue.

Q. Which opportunity?  
A. :  https://github.com/swapagarwal/swag-for-dev/pull/1092

@aslafy-z  Please resolve this issue.

![image](https://github.com/swapagarwal/swag-for-dev/assets/110784317/aa71bf92-e0a4-48ce-8d3f-e1c0c3b86c29)

![image](https://github.com/swapagarwal/swag-for-dev/assets/110784317/e7c6efeb-663a-4a61-921d-ab57750a3057)

**Comment by aslafy-z** [comment]
@BandhiyaHardik it looks like it was a transient error. You can ignore it. Your opportunity is deployed to the website and your contribution is confirmed and will count for the hacktoberfest challenge.

**Comment by BandhiyaHardik** [comment]
Thank You @aslafy-z
