### ISSUE TITLE
Add DagsHub swags

### ISSUE THREAD

**Issue by aashishpanthi** [swapagarwal/swag-for-dev#1104]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : DagsHub

Q. Where have you seen the announcement (URL)?  
A. : Here: https://dagshub.com/blog/hacktoberfest-2023/

Q. What kind of swag (clothing, stickers, ...)?  
A. : Clothing, stickers, bottles

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : Yes

Register to [DagsHub](https://dagshub.com/user/sign_up) and Hacktoberfest and contribute to any of the DagsHub hosted projects with the topic 'hacktoberfest'.

- The first 10 participants whose initial 10 PR/MR on the Intermediate and Advanced challenges are accepted will get a DagsHub swag package!
- The first 10 participants whose initial 10 PR/MR on the Noe-code and Beginner challenges are accepted will get a DagsHub stickers.

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aashishpanthi** [comment]
If you assign me this issue, I will add the swag.

**Comment by aslafy-z** [comment]
I believe these swag packs are already done. I'd not add this opportunity as it has a low stock of actual swag. Thank you for the proposal
