### ISSUE TITLE
[Hacktoberfest] Add Swag Opportunity for EMQ

### ISSUE THREAD

**Issue by BandhiyaHardik** [swapagarwal/swag-for-dev#1108]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : <a href='https://www.emqx.com/en'>EMQ</a> 

Q. Where have you seen the announcement (URL)?  
A. :  https://www.emqx.com/en/blog/join-hacktoberfest-2023-with-emq-community

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Yes

contributors who have had 2 or more pull requests accepted in the eKuiper or NanoMQ projects will receive a custom EMQ t-shirt!

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by BandhiyaHardik** [comment]
i would like to work on this issue

**Comment by aslafy-z** [comment]
done with https://github.com/swapagarwal/swag-for-dev/pull/1161
