### ISSUE TITLE
Add Flyte swag opportunity

### ISSUE THREAD

**Issue by aashishpanthi** [swapagarwal/swag-for-dev#1110]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Flyte

Q. Where have you seen the announcement (URL)?  
A. : Here: https://flyte.org/blog/flyte-at-hacktoberfest-2023

Q. What kind of swag (clothing, stickers, ...)?  
A. : Clothing, water bootles, stickers, sweatshirt

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : Yes

## Hackathon prizes
- 2 merged/accepted PRs*: t-shirt and sticker
- 3 merged/accepted PRs*: water bottle and sticker
- Plugin*: Amazon Gift Card
- 3+ merged/accepted PRs*: Flyte crewneck sweatshirt and sticker

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aashishpanthi** [comment]
Assign me this issue

**Comment by aslafy-z** [comment]
@aashishpanthi assigned :)
