### ISSUE TITLE
Add the swags opportunity from Hasura

### ISSUE THREAD

**Issue by aashishpanthi** [swapagarwal/swag-for-dev#1111]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Hasura

Q. Where have you seen the announcement (URL)?  
A. : Here: https://hasura.io/blog/the-hasura-hacktoberfest-fiesta-build-a-supergraph-and-win-1000/

Q. What kind of swag (clothing, stickers, ...)?  
A. : Clothing, stickers

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : Yes

Contribute to the Hasura Docs this hacktoberfest to win swags. A t-shirt and a sticker pack is sent to everyone who submits an accepted contribution.

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
Superseeds https://github.com/swapagarwal/swag-for-dev/issues/677
Assigned @aashishpanthi
