### ISSUE TITLE
Contribute to opensource and win swags (digital and physical stickers)

### ISSUE THREAD

**Issue by sarojregmi200** [swapagarwal/swag-for-dev#1113]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : ILLA Cloud. 

Q. Where have you seen the announcement (URL)?  
A. : https://blog.illacloud.com/hacktoberfest2023/

Q. What kind of swag (clothing, stickers, ...)?  
A. : Stickers

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : Yes
 

- [X] I've checked that the promotion is legit.
- [X] I've checked that it's still available to the public.
 
Ps : Can I be  assigned to this issue??

**Comment by aslafy-z** [comment]
Thank you for the contribution, feel free to open a PR.

**Comment by sarojregmi200** [comment]
Done, waiting for the review.

**Comment by aslafy-z** [comment]
Replaced by #1172

**Comment by aslafy-z** [comment]
This swag offering works with a contest, only the 30% most ranked people will get swag. Closing it.
