### ISSUE TITLE
Contribute to Bitcoin Open-Source Projects this Hacktoberfest and winsome swags.

### ISSUE THREAD

**Issue by sarojregmi200** [swapagarwal/swag-for-dev#1115]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Alby 

Q. Where have you seen the announcement (URL)?  
A. : https://blog.getalby.com/contribute-to-the-bitcoin-open-source-this-hacktoberfest-2023/

Q. What kind of swag (clothing, stickers, ...)?  
A. : Alby merchandise (stickers, socks, gadgets)

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

PS: Can I be assigned to this issue?

**Comment by aslafy-z** [comment]
Thank you for the contribution, feel free to open a PR.

**Comment by aslafy-z** [comment]
Fixed by #1171
