### ISSUE TITLE
HACKTOBERFEST IS OPEN! Submit a project for Passwordless.dev for a chance to win!

### ISSUE THREAD

**Issue by sarojregmi200** [swapagarwal/swag-for-dev#1117]
## Wild swag opportunity appeared!

- [X] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Bitwarden

Q. Where have you seen the announcement (URL)?  
A. : https://community.bitwarden.com/t/hacktoberfest-is-open-submit-a-project-for-passwordless-dev-for-a-chance-to-win/58642/1

Q. What kind of swag (clothing, stickers, ...)?  
A. : Cash Prize:
    -  1st place: $1000
    - 2nd place: $500
    - 3rd place: $250

Q. Have you received swag from this?  
A. : No

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

Ps: Can I be assigned to this issue.

**Comment by aslafy-z** [comment]
Thanks for your submission, 🙏, but we can't list opportunities tied to contests or raffles with exclusive eligibility requirements. We want to keep the experience open and enjoyable for everyone. Unfortunately, we can't proceed with this one.
