### ISSUE TITLE
Participate in devICT Hacktouberfest and win stickers. 

### ISSUE THREAD

**Issue by sarojregmi200** [swapagarwal/swag-for-dev#1119]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : devICT 

Q. Where have you seen the announcement (URL)?  
A. : https://hacktoberfest.devict.org/

Q. What kind of swag (clothing, stickers, ...)?  
A. : stickers

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

Ps: Can I work on this issue??

**Comment by aslafy-z** [comment]
Thank you for your submission! Feel free to open a PR for this issue!
