### ISSUE TITLE
twilio doesn't provide free t-shirts anymore

### ISSUE THREAD

**Issue by arnas** [swapagarwal/swag-for-dev#112]
- [X] I've checked that this isn't a duplicate issue.

(Current Promotion)
Please describe your concern here:
It seems that the promotion has ended as there is no form to fill in the twilio website

**Comment by aslafy-z** [comment]
Are you sure? Have you been through the [twilio.com/quest](https://twilio.com/quest)?
They [tweeted](https://twitter.com/twilio/status/1049472017639051269) about it yesterday, I have a doubt they already closed it.

**Comment by arnas** [comment]
Well atleast I can't find it in the position that is shows in the youtube video https://youtu.be/r9MPBJjPQdA?t=54 . Though I may need to complete first set of objectives. Though I am not sure what first set of objectives is

**Comment by aslafy-z** [comment]
The first set is the first quest. Yes, you have to do it and it will ask you if you want a t-shirt at the end 😉

**Comment by kevin51jiang** [comment]
It's basically everything under the "getting started" heading

**Comment by arnas** [comment]
It seems everything is alright, the form showed up.
