### ISSUE TITLE
dyrector.io Hacktoberfest Swag 2023 🏆

### ISSUE THREAD

**Issue by sarojregmi200** [swapagarwal/swag-for-dev#1120]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : dyrector.io 

Q. Where have you seen the announcement (URL)?  
A. : https://github.com/dyrector-io/dyrectorio/issues/837

Q. What kind of swag (clothing, stickers, ...)?  
A. : stickers and clothes

Q. Have you received swag from this?  
A. : No

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

Ps: Can I work on this issue??

**Comment by aslafy-z** [comment]
Thank you for your submission! Feel free to open a PR for this issue! 
I assigned you the issue.

**Comment by BandhiyaHardik** [comment]
i would like to work on this issue
