### ISSUE TITLE
Swag opportunity for hyperswitch!!!

### ISSUE THREAD

**Issue by sarojregmi200** [swapagarwal/swag-for-dev#1124]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. :Hyperswitch 

Q. Where have you seen the announcement (URL)?  
A. : https://hyperswitch.io/hacktoberfest

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing, and stickers.

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

Ps: Can I work on this issue??

**Comment by aslafy-z** [comment]
Thank you for your submission! Feel free to open a PR for this issue! 
I assigned you the issue

**Comment by aashishpanthi** [comment]
I've resolved the error. You can merge the changes
