### ISSUE TITLE
New Swag opportunity for Javascript Today 

### ISSUE THREAD

**Issue by sarojregmi200** [swapagarwal/swag-for-dev#1127]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : [JavaScript Today](https://blog.javascripttoday.com/)

Q. Where have you seen the announcement (URL)?  
A. : https://blog.javascripttoday.com/blog/hacktoberfest-2023/

Q. What kind of swag (clothing, stickers, ...)?  
A. : stickers

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

PS: Can I work on this issue.

**Comment by aslafy-z** [comment]
Thank you for your submission! Feel free to open a PR for this issue!

**Comment by BandhiyaHardik** [comment]
i would like to work on this issue
