### ISSUE TITLE
New swag opportunity for Leap Frog

### ISSUE THREAD

**Issue by sarojregmi200** [swapagarwal/swag-for-dev#1128]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. :[Leapfrog Technology](https://www.lftechnology.com/) 

Q. Where have you seen the announcement (URL)?  
A. : https://frogtoberfest.lftechnology.com/

Q. What kind of swag (clothing, stickers, ...)?  
A. : Clothing and stickers.

Q. Have you received swag from this?  
A. : No.

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

PS: Can I work on this issue???

**Comment by aslafy-z** [comment]
Thanks for your submission, 🙏, but we can't list opportunities tied to contests or raffles with exclusive eligibility requirements. We want to keep the experience open and enjoyable for everyone. Unfortunately, we can't proceed with this one.
