### ISSUE TITLE
New swag opportunity for loft labs

### ISSUE THREAD

**Issue by sarojregmi200** [swapagarwal/swag-for-dev#1129]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : loft.sh

Q. Where have you seen the announcement (URL)?  
A. :https://loft.sh/blog/celebrating-the-spirit-of-hacktoberfest-at-loft 

Q. What kind of swag (clothing, stickers, ...)?  
A. : One merged PR gets you a Loft exclusive T-shirt, two merged PRs get you a brand new Keyboard, and four or more merged PRs get you a Loft Exclusive Swag Box.

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

Ps: Can I work on this issue.

**Comment by aslafy-z** [comment]
Thank you for your submission! Feel free to open a PR for this issue!

**Comment by aslafy-z** [comment]
Fixed by #1167
