### ISSUE TITLE
Install GreenKeeper to keep dependencies up-to-date

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#113]
https://github.com/apps/greenkeeper

GreenKeeper is a GitHub app that constantly check if node dependencies has to be updated. It automaticaly creates pull-requests when it found an update and thus would allow us to keep our dependencies allways up to date. It's totally free for opensource project.

**Comment by aslafy-z** [comment]
See #114

**Comment by swapagarwal** [comment]
Thanks for the suggestion. Merged! 🎉
