### ISSUE TITLE
Turbot swag opportunity

### ISSUE THREAD

**Issue by aashishpanthi** [swapagarwal/swag-for-dev#1141]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Turbot

Q. Where have you seen the announcement (URL)?  
A. : Here: https://turbot.com/blog/2023/10/hacktoberfest-2023

Q. What kind of swag (clothing, stickers, ...)?  
A. : Turbot stickers and t-shirts

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : Yes

For no-code, low-code and high-code contributions, you can win swags from turbot.

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
Thank you for sharing this swag opportunity. Would you like to open a PR for it?

**Comment by aashishpanthi** [comment]
Yes, I will do
