### ISSUE TITLE
Umbraco swag opportunity

### ISSUE THREAD

**Issue by aashishpanthi** [swapagarwal/swag-for-dev#1142]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Umbraco

Q. Where have you seen the announcement (URL)?  
A. : Here: https://umbraco.com/blog/umbraco-hacktoberfest-2023/

Q. What kind of swag (clothing, stickers, ...)?  
A. : t-shirts

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : Yes

Submit a PR to solve one or more issues in different Umbraco repo. You can win t-shirts

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
Thank you for sharing this swag opportunity. Would you like to open a PR for it?

**Comment by edwincarrot** [comment]
Can I take this issue? First time contributor here. Thanks!

**Comment by aslafy-z** [comment]
@edwincarrot I just assigned you the issue. Feel free to ask if you have any questions 😊

**Comment by aslafy-z** [comment]
Fixed with #1162
