### ISSUE TITLE
Answer swag opportunity

### ISSUE THREAD

**Issue by edwincarrot** [swapagarwal/swag-for-dev#1147]
## Wild swag opportunity appeared!

- [V] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Answer

Q. Where have you seen the announcement (URL)?  
A. : https://answer.dev/blog/2023/09/27/celebrate-answer-first-anniversary-with-hacktoberfest-2023/

Q. What kind of swag (clothing, stickers, ...)?  
A. : digital badge for all accepted PR, and a bag and stickers for top 3 contributors.

Q. Have you received swag from this?  
A. : Not yet

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Yes

- [V] I've checked that the promotion is legit.
- [V] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
Hello @edwincarrot 
Thank you for opening this issue. However, this swag opportunity was already rejected in https://github.com/swapagarwal/swag-for-dev/issues/1087#issuecomment-1761194426.
Please search for existing issues before creating a new one.
Feel free to open a PR for any non-assigned existing issues!
