### ISSUE TITLE
[Hacktoberfest] Add Swag Opportunity for OVHcloud

### ISSUE THREAD

**Issue by BandhiyaHardik** [swapagarwal/swag-for-dev#1149]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : <a href='https://www.ovhcloud.com/en/'>OVH Cloud</a>

Q. Where have you seen the announcement (URL)?  
A. : https://blog.ovhcloud.com/ovhcloud-and-hacktober-fest-2023/

Q. What kind of swag (clothing, stickers, ...)?  
A. : Lottery

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Yes

Have at least 4 PRs merged into the principal branch of the OVH Repos below to be eligible to a lottery to win a prize.

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by BandhiyaHardik** [comment]
i would like to work on this issue

**Comment by aslafy-z** [comment]
This is a lottery, we do not accept lotteries. Closing this issue and the associated pr.

**Comment by BandhiyaHardik** [comment]
@aslafy-z  okay i understand i will make sure to only add swag opportunity related to clothing,stickers,....etc like this.

**Comment by BandhiyaHardik** [comment]
Thank You @aslafy-z

**Comment by aslafy-z** [comment]
Thank you to you!
