### ISSUE TITLE
[Hacktoberfest] Add Swag Opportunity for TBD

### ISSUE THREAD

**Issue by BandhiyaHardik** [swapagarwal/swag-for-dev#1154]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : <a href='https://developer.tbd.website/'>TBD</a>

Q. Where have you seen the announcement (URL)?  
A. : https://dev.to/tbdevs/preptember-diaries-gearing-up-for-hacktoberfest-2023-8o2

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Yes

Exclusive swag from the TBD shop for the Top 20 contributors and custom Hacktoberfest swag for the Top 3 contributors.

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by BandhiyaHardik** [comment]
i would like to work on this issue

**Comment by aslafy-z** [comment]
This opportunity also offers swag to the top 20 contributors. We don't accept these here.
