### ISSUE TITLE
[Hacktoberfest] Add Swag Opportunity for Modtoberfest

### ISSUE THREAD

**Issue by BandhiyaHardik** [swapagarwal/swag-for-dev#1159]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : <a href='https://modtoberfest.com/'>Modtoberfest</a>

Q. Where have you seen the announcement (URL)?  
A. : https://modtoberfest.com/modtoberforest

Q. What kind of swag (clothing, stickers, ...)?  
A. : Stickers

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Yes 

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by BandhiyaHardik** [comment]
i would like to work on this issue

**Comment by DevanshKyada27** [comment]
Hey @aslafy-z could you please assign me this issue want to work on it.

**Comment by BandhiyaHardik** [comment]
@DevanshKyada27  i am actually working on it right now.

**Comment by DevanshKyada27** [comment]
OK @BandhiyaHardik no problem you can raise the PR. :)

**Comment by BandhiyaHardik** [comment]
@DevanshKyada27 Thank you for your understanding and please close your pr about modtoberfest.
