### ISSUE TITLE
[Hacktoberfest] Add Swag Opportunity for Sia Foundation

### ISSUE THREAD

**Issue by BandhiyaHardik** [swapagarwal/swag-for-dev#1186]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : <a href='https://sia.tech/'>Sia Foundation</a> 

Q. Where have you seen the announcement (URL)?  
A. : https://twitter.com/Sia__Foundation/status/1712134476149448778

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Yes

Be the first 20 to contribute to any [Sia Foundation repo](https://github.com/SiaFoundation).

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by BandhiyaHardik** [comment]
i would like to work on this issue

**Comment by aslafy-z** [comment]
Only the first 20 people, I think this offer should not be added.

**Comment by BandhiyaHardik** [comment]
@aslafy-z  yes you are right. it's 22oct and most of the people have contributed to it so this opportunity is not availaible.

when i add new swags I will make sure to look into it and then i will add issue and PRs
