### ISSUE TITLE
[Hacktoberfest] Add Swag Opportunity for Treblle

### ISSUE THREAD

**Issue by BandhiyaHardik** [swapagarwal/swag-for-dev#1187]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : <a href='https://hacked.treblle.com/'>Treblle</a>

Q. Where have you seen the announcement (URL)?  
A. : https://blog.treblle.com/treblle-hacktoberfest/

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing,stickers...

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Yes

Sign up for [Treblle Hacktoberfest](https://docs.google.com/forms/d/e/1FAIpQLSfC_8mX8lpQNhksqQGUhsQ0zTvRzMC5YzufVVbVkPksxouLFw/viewform)

 Participate as a solo developer or a team of 2-4 to build a SDK for the platform.

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by BandhiyaHardik** [comment]
i would like to work on this issue

**Comment by aslafy-z** [comment]
Closing as it is already too late to apply

You have until the 15th of October 2023 to submit your entry via the Google Form, any entries from the 15th onwards will not be taken into consideration.

**Comment by BandhiyaHardik** [comment]
Sorry, i didn't know about that. 

I will look into it and make sure it is still open.
