### ISSUE TITLE
Adopt awesome list conventions

### ISSUE THREAD

**Issue by jgierer12** [swapagarwal/swag-for-dev#12]
The format of this project is very similar to the [awesome](https://awesome.re) lists originally started by Sindre Sorhus. That's why I think it would be a good idea to turn this project into an awesome list as well.

Benefits of being an awesome list:
* Be part of a huge network of hundreds of awesome lists
* Get a place in [sindresorhus/awesome](https://github.com/sindresorhus/awesome), an 'awesome list of awesome lists' and one of GitHub's most starred projects
* Get included in tools that scrape awesome lists, such as [Pretty Awesome Lists](https://www.prettyawesomelists.com)
* Adopt a clearly defined set of guidelines that make it easy to read and contribute to the list

[Requirements](https://github.com/sindresorhus/awesome/blob/master/awesome.md):
* Rename the project to `awesome-swag` (or `awesome-dev-swag` or similar)
* Display the awesome badge in the readme
* Add a suitable license (like `CC0`)
* Add a contribution guide
* Add a code of conduct (optional but recommended)
* Adopt the stylistic guidelines (*this is mostly fulfilled already*)
* After the project is at least 30 days old, submit a PR to [sindresorhus/awesome](https://github.com/sindresorhus/awesome) to add it to the 'awesome list of awesome lists'

Most of this could be easily done using the [official Yeoman generator](https://github.com/dar5hak/generator-awesome-list).

This could also be used as an opportunity to clean up and categorize the swag into different categories, such as free/paid, difficulty level, active/inactive etc.

**Comment by swapagarwal** [comment]
I'm definitely looking forward to add it to the `awesome` list.
However, I don't see the requirement of renaming it to start with `awesome-` prefix. Check out https://github.com/ripienaar/free-for-dev and https://github.com/tvvocold/FOSS-for-Dev and let me know your thoughts on this. 😇

**Comment by jgierer12** [comment]
It says so on https://github.com/sindresorhus/awesome/blob/master/create-list.md but seeing as the repos you linked are named differently they're likely don't enforce it

**Comment by sindresorhus** [comment]
It's just a recommendation. We accept lists without the `awesome-` prefix too.

**Comment by swapagarwal** [comment]
Closing as it's no longer a Markdown list.
