### ISSUE TITLE
Add swag opportunity for Layer5

### ISSUE THREAD

**Issue by dalvishruti14** [swapagarwal/swag-for-dev#1205]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Layer5

Q. Where have you seen the announcement (URL)?  
A. : https://layer5.io/community/events/hacktoberfest-prep-2023-easing-into-cncf-open-source-projects

Q. What kind of swag (clothing, stickers, ...)?  
A. :   Hacktoberfest Contributor badge

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : 

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

Can I work on this?

**Comment by aslafy-z** [comment]
Thank you for the proposal @dalvishruti14 
However, this company is not offering physical swag but digital badges. We voted to exclude these opportunities from this list. 
Feel free to work on some other issue or propose something else. Thank you for your understanding.
