### ISSUE TITLE
Nexmo Swag Opportunity requires merged Pull Request

### ISSUE THREAD

**Issue by Vibhu-Agarwal** [swapagarwal/swag-for-dev#122]
- [X] I've checked that this isn't a duplicate issue.

Referring to [Nexmo Swag Opportunity](https://www.nexmo.com/blog/2018/10/09/join-nextoberfest-tis-the-season-to-be-hacking-dr/),
Currently, the [devSwag website](https://devswag.io/) shows that we have to make a pull request.
But the condition states that the pull request has to be merged to be counted for a swag opportunity.
In the third paragraph, it clearly states that:
![sss](https://user-images.githubusercontent.com/27439964/46972649-9b331980-d0dc-11e8-957b-102aaaf24898.png)
<br>
Also, their google form asks for link for **merged** pull request.
![sss](https://user-images.githubusercontent.com/27439964/46972772-f6fda280-d0dc-11e8-8e42-c40aa7f20736.png)
<br>
So we can add this information on the homepage of [devSwag](https://devswag.io/).
And we can also consider increasing the difficulty for this swag opportunity,

**Comment by swapagarwal** [comment]
Thanks @Vibhu-Agarwal for taking the time to add a detailed description! 🎉
