### ISSUE TITLE
[image] In EMQ the image is not fitting in frame.

### ISSUE THREAD

**Issue by BandhiyaHardik** [swapagarwal/swag-for-dev#1230]
## Issue with an existing swag opportunity

- [x] I've checked that this isn't a duplicate issue.

Q. Which opportunity?  
A. : EMQ

There is no issue with swag opportunity.

i was looking into the website and i found in many swags the images are not fitting in the frame.

Snapshot of image on website:
![image](https://github.com/swapagarwal/swag-for-dev/assets/110784317/21873cbc-444f-4e42-a3dc-66c941c96253)

The Actual Image:
![image](https://github.com/swapagarwal/swag-for-dev/assets/110784317/c962161d-d95c-4c49-88d9-61555c02f6b9)

## Solution:
By resizing the image.

**Comment by BandhiyaHardik** [comment]
i would like to work on this issue

**Comment by dalvishruti14** [comment]
Can I work on this?
