### ISSUE TITLE
✨ Add a new swag opportunity

### ISSUE THREAD

**Issue by JatinPhogat** [swapagarwal/swag-for-dev#1246]
## Wild swag opportunity appeared!

- [X] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Gatsby

Q. Where have you seen the announcement (URL)?  
A. : YES

Q. What kind of swag (clothing, stickers, ...)?  
A. : mixed items from the there store including tshirts,socks,notebooks etc.

Q. Have you received swag from this?  
A. : Not me

Q. How long did it take?  
A. : Depend on individual

Q. Does it ship worldwide?  
A. : yes

- [X] I've checked that the promotion is legit.
- [X] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
Please check the website, this opportunity is already live. Feel free to contribute again!
