### ISSUE TITLE
✨ Add a new swag opportunity

### ISSUE THREAD

**Issue by JatinPhogat** [swapagarwal/swag-for-dev#1250]
## Wild swag opportunity appeared!

- [X] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : JSBin

Q. Where have you seen the announcement (URL)?  
A. : yes

Q. What kind of swag (clothing, stickers, ...)?  
A. : Stickers

Q. Have you received swag from this?  
A. : Not me

Q. How long did it take?  
A. : Depend on Country

Q. Does it ship worldwide?  
A. : Yes

- [X] I've checked that the promotion is legit.
- [X] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
It looks like they re-opened the offering. Feel free to open a PR to remove the expired: true flag.

**Comment by JatinPhogat** [comment]
Thamks a lot , i am working on it

**Comment by JatinPhogat** [comment]
Hi , @aslafy-z i have done the task please review it
