### ISSUE TITLE
Add TensorFlow swag

### ISSUE THREAD

**Issue by nadasuhailAyesh12** [swapagarwal/swag-for-dev#1256]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Google offers this swag in collaboration with the TensorFlow project.

Q. Where have you seen the announcement (URL)?  
A. https://www.instagram.com/buyswags/

Q. What kind of swag (clothing, stickers, ...)?  
A. : The swag offered includes a limited edition TensorFlow hoodie.

Q. Have you received swag from this?  
A. : Developers who contribute to TensorFlow eligible to receive the swag.

Q. How long did it take?  
A. :  The time taken to receive the swag may vary depending on the individual's contribution and the processing time of the swag distribution process.

Q. Does it ship worldwide?  
A. : yes it does

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by Choon38** [comment]
@nadasuhailAyesh12 Regarding #1256 issue, could you please provide URL where you found the announcement about this swag.

**Comment by Tejas-Sharma-dev** [comment]
Hi @Choon38, I tried to search about this swag in official website and its community page, i did not find anything as such.
we can close this issue, by marking expired or invalid.
