### ISSUE TITLE
RedwoodJS Stickers 404

### ISSUE THREAD

**Issue by thecodefodder** [swapagarwal/swag-for-dev#1258]
## Issue with an existing swag opportunity

- [x] I've checked that this isn't a duplicate issue.

Q. Which opportunity?  
A. : RedwoodJS Stickers

I went to the page, and it shows a 404 error. I assume they aren't running this promotion anymore. I felt like I should open an issue.

**Comment by Tejas-Sharma-dev** [comment]
yes, this issue still exist (provided link redirects to Error 404) and this swap opportunity is expired/Invalid. I request maintainers to mark this opportunity as expired and remove from the main page

**Comment by aslafy-z** [comment]
PRs are welcome !
