### ISSUE TITLE
The whats new to devSwag button

### ISSUE THREAD

**Issue by tannmaysgupta** [swapagarwal/swag-for-dev#126]
- [x] I've checked that this isn't a duplicate issue.

Is it regarding the current promotions or something new?
Fill the corresponding section below:

(Current Promotion)
Please describe your concern here:
The New to devSwag button isn't very noticeable in the desktop version and at the same time its tooo huge in the mobile version.

(New Promotion)
Reference Link:
- [ ] I've confirmed that the promotion is legit.
- [ ] I've verified that it's still available to the public.

**Comment by aslafy-z** [comment]
Duplicate, see https://github.com/swapagarwal/swag-for-dev/issues/95

**Comment by sorianog** [comment]
@tannmaysgupta Was this issue reported before or after the "megaphone" icon for the button was added instead?
