### ISSUE TITLE
Airbyte Swag Opportunity

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#1279]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Airbyte

Q. Where have you seen the announcement (URL)?  
A. : https://airbyte.com/community/connector-hackathon

Q. What kind of swag (clothing, stickers, ...)?  
A. : cash

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : -

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by Tejas-Sharma-dev** [comment]
Hi @aslafy-z ,

this oppurtunity is limited till 31st oct, shall i raise a PR for the same.

**Comment by aslafy-z** [comment]
We can update the previous entry, yes.
