### ISSUE TITLE
JavaScript Today free sticker

### ISSUE THREAD

**Issue by username1001** [swapagarwal/swag-for-dev#1282]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : JavaScript Today 

Q. Where have you seen the announcement (URL)?  
A. : https://javascripttoday.com/blog/hacktoberfest-2024-free-sticker/

Q. What kind of swag (clothing, stickers, ...)?  
A. : Stickers

Q. Have you received swag from this?  
A. : I've sent them out around the world, yes. 

Q. How long did it take? 
A. : Not sure. 

Q. Does it ship worldwide?  
A. : Yes.

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by Tejas-Sharma-dev** [comment]
Hi @username1001,

In JavaScriptToday git repo (https://github.com/JavaScriptToday/hacktoberfest), they have mentioned its only limited to first 50 people worldwide, and already number of submission is exceeded.

![image](https://github.com/user-attachments/assets/7759cfbc-412f-4e59-bd7b-f2cdcdd34c4c)
 
So this swag is not available anymore.

**Comment by username1001** [comment]
@aslafy-z @Tejas-Sharma-dev Whoops. Just updated the README. I have like a thousand stickers to give away this year, haha. The swag is indeed available. The logo stickers, and some other random dev stickers as well.

**Comment by username1001** [comment]
Also, this isn't just for contributions to that repository, it can be any repository on GitHub! :D

**Comment by aslafy-z** [comment]
@username1001 thank you for the update! Feel free to open a PR to add the opportunity to the website!
