### ISSUE TITLE
Add paid swag?

### ISSUE THREAD

**Issue by jgierer12** [swapagarwal/swag-for-dev#13]
While the free/promotional swag featured on this list is great, there is also some paid swag that I find worthy of being listed here. Most notably, [Wes Bos' awesome sticker sales](https://bos.af/) and [freeCodeCamp's non-profit merch shop](https://shop.freecodecamp.org/).

Do you think these should be added to the list? Of course, they'd have to be separated from the free stuff in some way.

**Comment by kevin51jiang** [comment]
Looks interesting, but I personally think that the whole point of this list is for free swag, so having paid ones wouldn't really match up with the reason this list was created in the first place.

**Comment by UdoKifferbrehl** [comment]
By the way, does @wesbos have a newsletter where he informs about the next arrival?

**Comment by nikhilmufc7** [comment]
@UdoKifferbrehl you can signup here http://wesbos.com/email/
