### ISSUE TITLE
Add Aras to the list

### ISSUE THREAD

**Issue by sachincool** [swapagarwal/swag-for-dev#133]
- [x] I've checked that this isn't a duplicate issue.

Is it regarding the current promotions or something new?
Fill the corresponding section below:

Aras has started  with their campaign 
http://community.aras.com/en/join-aras-labs-hacktoberfest-2018/ 
You can add it to the list with proper difficulty and emoji's :100: 
Reference Link:
- [x] I've confirmed that the promotion is legit.
- [x] I've verified that it's still available to the public.

**Comment by ncallan2019** [comment]
Pull #135 should fix this.
