### ISSUE TITLE
Add Operation Code Hacktoberfest swag

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#137]
- [x] I've checked that this isn't a duplicate issue.

Company: Operation Code
Reference Link: https://github.com/OperationCode/START_HERE
Swag: Close 3 issues, get a t-shirt. Make a PR and get stickers.

- [x] I've confirmed that the promotion is legit.
- [x] I've verified that it's still available to the public.

**Comment by ssiddhantsharma** [comment]
@aslafy-z The swag option is still open for some stick stickers only. Better not close it and reopen with only stickers added as a part of the swag from Operation Code.
