### ISSUE TITLE
Add beginner friendly opportunities too

### ISSUE THREAD

**Issue by till-tomorrow** [swapagarwal/swag-for-dev#14]
It would be great if open source beginners get a platform to contribute on!

**Comment by swapagarwal** [comment]
@till-tomorrow You might be interested in https://github.com/MunGell/awesome-for-beginners! 🎉

**Comment by till-tomorrow** [comment]
These are not the opportunities to earn swags..

**Comment by swapagarwal** [comment]
Oh, I thought you were looking for open-source beginner issues.
In the list, there are varied difficulties of tasks. One other issue is looking to tag the issues with difficulty levels so I think you'd be able to get what you want in some time. 😄
