### ISSUE TITLE
Netlify does not build anymore?

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#143]
Review apps are not deployed and it looks that the production isn't updated too.

@swapagarwal you've got any thought?

**Comment by caioproiete** [comment]
GitHub has been down for several hours, and webhooks were affected.

https://status.github.com

[![image](https://user-images.githubusercontent.com/177608/47320982-7c2b0f00-d629-11e8-9d41-dd4c3802ce79.png)](https://status.github.com)

**Comment by swapagarwal** [comment]
GitHub has recovered.
I've triggered a rebuild of the site.
Individual PRs will be rebuilt with new commits.
