### ISSUE TITLE
Set swag item as done (locally)

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#151]
It would be great to be able to set an item as done. 

We could save it locally to the browser's localstorage, we only need a way to identify swag items (ie. have an unique id for each items).

Once flagged done, the item could be grayed out and pushed to the end of the list.

**Comment by NaveenDA** [comment]
It seems to be a good idea

**Comment by swapagarwal** [comment]
Possible future addition: Use [Netlify Identity](https://www.netlify.com/docs/identity/) to identify users and persist this data to be used across devices.

**Comment by aslafy-z** [comment]
Let's pray for netlify to give us a free plan for teams :(

**Comment by sseficha** [comment]
I think it would cool, if hovering over the pictures was interactive and clicking on them substituted the roll of the link. Then the link you be something like this instead: Check if completed [ ] <-- checkbox. What do you think?

**Comment by amhislop** [comment]
Sorry, I should have asked before submitting a PR #438. Can I be assigned to this issue?
