### ISSUE TITLE
Error launching website locally

### ISSUE THREAD

**Issue by sseficha** [swapagarwal/swag-for-dev#155]
So I have followed the ReadMe instructions and I keep facing this error:

![error](https://user-images.githubusercontent.com/32609628/48019873-2718ee00-e13d-11e8-9690-d0f71a1a0e4f.jpg)

I haven't been able to find a solution so far. Could anyone please help me? 🤔

**Comment by aslafy-z** [comment]
I just merged #121 that fixes it, you can pull or clone again to try it. Thanks for reporting!
