### ISSUE TITLE
Disable Hacktoberfest hellobar

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#157]
```
Looking for #Hacktoberfest opportunities?
Yes, show me filtered items!
``` 

It's not needed anymore as Hacktoberfest has ended.

@swapagarwal Maybe it's a good time to move advertising logic from netlify to this repo so it could be minified? (Proposed here https://github.com/swapagarwal/swag-for-dev/issues/152#issuecomment-433880919)

**Comment by aslafy-z** [comment]
I can't see it anymore but the JS script is still loaded. Is this on purpose @swapagarwal ?

**Comment by vikaspotluri123** [comment]
Is this good to close? I'm not entirely sure 👀

**Comment by aslafy-z** [comment]
@swapagarwal still needs to address https://github.com/swapagarwal/swag-for-dev/issues/157#issuecomment-438903610
But yeah, the hellobar has been disabled.
