### ISSUE TITLE
Remove Passenger

### ISSUE THREAD

**Issue by itaisteinherz** [swapagarwal/swag-for-dev#158]
- [x] I've checked that this isn't a duplicate issue.

The Passenger promotion has ended (since the livestream was on November 1st), and so it should be removed from the website.
I can open a PR if there are no objections.

**Comment by itaisteinherz** [comment]
@vikaspotluri123 According to #154 and #88, we shouldn't remove an entry which has expired.
I think we can either put the promotion in a new file (e.g. `data-expired.json`) as suggested in the issue, or add a tag `expired` to the entry in `data.json` (like the `hacktoberfest` tag, but for generally expired offers).

**Comment by vikaspotluri123** [comment]
> add a tag `expired` to the entry in `data.json` (like the `hacktoberfest` tag, but for generally expired offers).

This would be the initial implementation of #88, are you willing to work on it?

**Comment by itaisteinherz** [comment]
Sure. I think I'll be able to create a PR in a few hours.
