### ISSUE TITLE
Errors while using gulp watch

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#164]
- [x] I've checked that this isn't a duplicate issue.

`cachebust` task deletes `rev-manifest.json` while `gulp watch`ing.

**Steps to reproduce**:

- have a clean env: `gulp clean`
- run `gulp` and wait for build to finish
- edit any `src/js/*.js` `src/styl/**/*.styl` file and save
- the changes are picked up by gulp, but clean rule is called and so `rev-manifest.json` is deleted
- `cachebust` task can't recover image paths

**Output**:

```
[17:26:38] Starting 'clean'...
[17:26:38] Finished 'clean' after 18 ms
[17:26:38] Starting 'styl'...
[17:26:38] Finished 'styl' after 33 ms
[17:26:38] Starting 'cachebust'...
Unable to find image in manifest: swag-img/alexa-ae4c621281.jpg
Unable to find image in manifest: swag-img/codeship-44ee32c752.jpg
Unable to find image in manifest: swag-img/devrant-b5db1750ec.jpg
Unable to find image in manifest: swag-img/gatsby-e57212455c.jpg
Unable to find image in manifest: swag-img/google_assistant-0880ffbe3b.jpg
Unable to find image in manifest: swag-img/mullvad-960aef2001.jpg
Unable to find image in manifest: swag-img/netlify-7be19aa6f0.jpg
Unable to find image in manifest: swag-img/npm-16e8bc80de.jpg
Unable to find image in manifest: swag-img/passenger-2feca7e10f.jpg
Unable to find image in manifest: swag-img/whatismybrowser-96e64863b8.jpg
[17:26:38] Finished 'cachebust' after 17 ms
```

**`rev-manifest.json`**:

```json
{
  "css/index.css": "css/index-9159b10c46.css"
} 
```

How to solve this? Should we have a clean rule per file type?
Deleting the dependency to `clean` in each watch trigger does not work at all, some files are picked up multiple times if I do that:

```json
  "js/index-226706dba4.js": "js/index-226706dba4-226706dba4.js",
  "js/index.js": "js/index-226706dba4.js",
  "css/index-9159b10c46.css": "css/index-9159b10c46-9159b10c46.css",
  "css/index.css": "css/index-e18c66172d.css",
```

Any thoughts?

**Comment by aslafy-z** [comment]
cc @vikaspotluri123

**Comment by vikaspotluri123** [comment]
Cachebusting shouldn't happen during development 🙈

**Comment by itaisteinherz** [comment]
I experienced this issue as well.
Another problem I noticed is that after a reload is triggered by the `watch` / `webserver` tasks, the website reports that `index.js` can't be found (this may be related to https://github.com/swapagarwal/swag-for-dev/pull/159#issuecomment-439214190).

**Comment by aslafy-z** [comment]
Should we implement two build tasks to leverage this, one for production and one for development?

**Comment by vikaspotluri123** [comment]
I think we can use env vars to see if cachebust should run - what do you think?

However, now that I think about it, this doesn't fix the problem about swag images being deleted.

What I think should happen is when the `data.json` file changes, if there's a new image url, swag-img is rerun. I think the requirements to fix this issue are as follows:

1. Implement #98 - It's a very simple fix and we don't need to leech out of the gulp root to read the data.json file

3. In production, run cachebust normally. By default, save rev-manifest as k=v json file (i.e. `'assets/css/dist.css': 'assets/css/dist.css'`)

2. Add a `clean:assets` (pls help me name things 🙈) task which _only_ cleans up scripts and styles. Make any required changes to keep functionality

3. By default, only clean assets

4. Watch `data.json`; only if the image list changes, re-run the download
