### ISSUE TITLE
Add Keen.io swag

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#172]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : [Keen.io](https://keen.io)

Q. Where have you seen the announcement (URL)?  
- https://ramptshirts.com/blog/2017/06/02/keen-ios-brilliant-t-shirt-easter-egg/

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing (t-shirt)

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : It seems, yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by swapagarwal** [comment]
This Easter egg is pretty cool!
I have received this; found it while going through the documentation.
However, I don't think we should add this to the list as it would pretty much defeat the purpose of being it an Easter egg. Thoughts? 


---- On Mon, 19 Nov 2018 20:00:49 +0530 notifications@github.com wrote ----


Wild swag opportunity appeared!
I've checked that this isn't a duplicate issue.

Q. Which company offers it?
 A. : Keen.io

Q. Where have you seen the anouncement (URL)?

https://ramptshirts.com/blog/2017/06/02/keen-ios-brilliant-t-shirt-easter-egg/
https://keen.io/docs/api/#wardrobe-resource

Q. What kind of swag (clothing, stickers, ...)?
 A. : clothing (t-shirt)

Q. Have you received swag from this?
 A. : No

Q. Does it ship worldwide?
 A. : It seems, yes

I've checked that the promotion is legit.
I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
I'm ok with that. I think we can close (and delete, [it's now possible](https://help.github.com/articles/deleting-an-issue/) for you :tada:) this issue so.

**Comment by GuyKh** [comment]
Any chance of helping with the EasterEgg? :P

**Comment by andreathniah** [comment]
Anyone faced the issue of having a reply of "The content-type of the request must be application/json or text/plain."? I'm pretty sure I got the cURL request right from the documentation.

**Comment by aslafy-z** [comment]
@andreathniah 

Your error speaks by itself. You want to set the `Content-Type` header of your POST request to `application/json` (if your payload, basically the JSON where you put your home address, is in JSON)  in order for the server to understand it. I think you misscopied from the doc, as it's specified in the curl command.

```
curl -X POST -H 'Content-Type: application/json' -d '{"The", "JSON"}'
```

**Comment by aslafy-z** [comment]
You can try to add `-vv` to your `curl` command to see if the header is present in the Request. We really need this community chat! Feel free to check out #177 and help us choose which platform to use!

**Comment by vikaspotluri123** [comment]
Gonna go ahead and close this issue as we're all in agreement to limit the exposure 🦊

Feel free to continue any discussion that's been going on 😁

**Comment by ssiddhantsharma** [comment]
@andreathniah @vikaspotluri123  @aslafy-z  I got it right the very first time, and it was a success but as I was contacting a past recipient of the swag from Indonesia. He told me he had to wait for 7 months for the swag to arrive. Well I guess they are a bit slow when it comes to S.E Asia.
