### ISSUE TITLE
Add jKool swag

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#173]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : [jKool](https://www.jkoolcloud.com/)

Q. Where have you seen the announcement (URL)?  
A. : https://www.jkoolcloud.com/free-t-shirt/

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing (t-shirt)

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : It looks like they do

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by ssiddhantsharma** [comment]
@aslafy-z Not working out man! I contacted their team, the promo ended way before. Also, the signup page is dead. Better close this issue.

**Comment by aslafy-z** [comment]
Thanks for the feedback. Closing it.
