### ISSUE TITLE
Add Free Tee 4 It swag

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#174]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : [Luxoft](https://www.luxoft.com/)

Q. Where have you seen the announcement (URL)?  
A. : https://freeteefor.it/

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing (t-shirt)

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : No, only Republic of Poland, Bulgaria, Ukraine, Romania, Poland, Germany, Russia, USA, Mexico

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
So sad it's over :/

**Comment by vikaspotluri123** [comment]
😟

**Comment by ssiddhantsharma** [comment]
@aslafy-z @vikaspotluri123 I managed to snag it at the right time. Had it shipped to the US for my folks to bring over. All we needed to do was solve high school level c++/java problem and syntax errors. They have some pretty sweet t shirts!
