### ISSUE TITLE
Add Google Code-In swag

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#175]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : [Google Code-In](https://codein.withgoogle.com/)

Q. Where have you seen the announcement (URL)?  
A. : https://medium.com/@itsjzt/get-free-t-shirt-from-google-even-when-you-dont-know-coding-9477a828174e

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing (t-shirt)

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : Yes

Only for 13-17 year old students.

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by Stevo99** [comment]
Hey Im new to contributing.  Would love to help with the project.  What exactly do you need?

**Comment by aslafy-z** [comment]
Hi @Stevo99, thanks for your interest! The 2018 Code-In edition is over. We'll wait for 2019 edition and see what we can do :wink:
Closing this from now.
