### ISSUE TITLE
Add ClickFunnel swag

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#176]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : [ClickFunnel](https://www.clickfunnels.com/)

Q. Where have you seen the announcement (URL)?  
A. : https://www.clickfunnels.com/tshirt_onboarding

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing (t-shirt)

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : Yes, it looks like 

This is not really developer swag, it's more business oriented.

Requirements:
- Subscribe for Free Trial, cancelable any time
- Watch 4 videos (~ 30 minutes total)
- Play ClickFunnel Game from the old dashboard: https://help.clickfunnels.com/hc/en-us/articles/360020781894-Claim-Your-Free-T-Shirt-Plus-MORE-

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by swapagarwal** [comment]
Hey Siddhant. Let's not be aggressive. The open PRs don't guarantee anything. If we were 100% sure, it'd already have been merged! 😇

---- On Thu, 06 Dec 2018 08:57:06 +0530 notifications@github.com wrote ----

@aslafy-z Hey man, it is not working. I went through all the process and in the end the link for not there. I contacted them but no reply. Better remove this, or first try once for yourself.
I had no success with this one.

**Comment by aslafy-z** [comment]
I've personally been through it and they sent me a T-shirt. 
I had to start a free trial, 
Watch the videos and then play their game as I stated in the description. It's pretty hidden, you have to go to the old dashboard version. There is a link in their new dashboard to it.
And then you'll see a Play game button. The first journey in their game is about looking to another video and then have a free shirt sent your way.
Don't forget to CANCEL THE TRIAL, you don't want to pay that much (it can be done right after the sign-up).

**Comment by ssiddhantsharma** [comment]
@aslafy-z Thanks for the information!

**Comment by berry120** [comment]
Interesting, but doesn't really fit the bill for dev swag IMHO.

**Comment by aslafy-z** [comment]
Finally got the shirt! Had to ask again but they sent it to me!
It looks like that 
https://banner2.kisspng.com/20180604/tbt/kisspng-t-shirt-funnel-hacking-sleeve-top-design-t-shirt-5b15e59a32c5e8.738916581528161690208.jpg

**Comment by sohailg** [comment]
Is it still available?

**Comment by aslafy-z** [comment]
I updated the links in OP. It looks that it's still open.

**Comment by aslafy-z** [comment]
Closing as it's not dev swag.
