### ISSUE TITLE
Suggestion: Create a community chat

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#177]
- [x] I've checked that this isn't a duplicate issue.

Create an instant chat channel (at least one) to allow more agile communication with contributors and githubers.

Here's some options:
- Slack 
- gitter 
- Discord

Let's discuss it!

Here's some links:
- https://github.com/neuecc/UniRx/issues/327
- https://www.quora.com/What-are-the-pros-and-cons-of-Gitter-vs-Slack

**Comment by arshadkazmi42** [comment]
How about creating a slack community? I feel slack is better option

**Comment by arshadkazmi42** [comment]
I think other than this `Easy to access (no need for custom sign ups etc)`.
The best thing about slack is like is the `channels`.

I think both has its drawbacks. I will still go with slack. I think we should do some voting and get feedback from all contributors on their thoughts, and then can decide which one to go with. I think there are some more options other than slack and gitter.

**Comment by aslafy-z** [comment]
There are `channels` in gitter, they're called `rooms` (I think it's new).
Yes! We should certainly get more feedbacks, that's why I opened an issue! I updated OP to reflect this :wink:

**Comment by swapagarwal** [comment]
Having a communication channel would be quite beneficial for collaborators as well as newcomers.
Let's start with Gitter? We can always move towards Slack / Discord if required in future.

**Comment by vikaspotluri123** [comment]
Sounds good 👍
