### ISSUE TITLE
Add Vultr swag

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#178]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : [Vultr](https://www.vultr.com/)

Q. Where have you seen the announcement (URL)?  
A. : https://www.vultr.com/swag/

Q. What kind of swag (clothing, stickers, ...)?  
A. : stickers

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : Yes

Requirements:
- Have to create an account before completing the form

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by vikaspotluri123** [comment]
Closing - https://github.com/swapagarwal/swag-for-dev/pull/180#issuecomment-453762882
