### ISSUE TITLE
Add ThousandEyes swag

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#179]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : [ThousandEyes](https://www.thousandeyes.com/)

Q. Where have you seen the announcement (URL)?  
A. : https://www.thousandeyes.com/tshirt

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing (t-shirt)

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : No, only US, Canada, UK, Japan and Portugal

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
Do we want to add only worldwide shipped swag?

**Comment by swapagarwal** [comment]
Let's keep this open for now. If there are enough of these, we can create a separate section in the website.

**Comment by debsmita1** [comment]
I am taking this up :)

**Comment by Yash-Garg** [comment]
It's sad that it doesn't ships worldwide :(

**Comment by debsmita1** [comment]
okay :(

**Comment by jordanmcdougall** [comment]
Confirmed shipping to UK.

**Comment by ChrisKatsaras** [comment]
Confirmed shipping to Canada. @gpavlovic and I have both received our swag

**Comment by wad3g** [comment]
I can confirm your is legit. Received my t-shirt a month or two ago.

**Comment by aviral14112001** [comment]
I don't understand what we have to do to close this issue

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
