### ISSUE TITLE
Add JS Bin swag

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#184]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : [JS Bin](https://jsbin.com/)

Q. Where have you seen the announcement (URL)?  
A. : https://jsbin.com/help/stickers/

Q. What kind of swag (clothing, stickers, ...)?  
A. : stickers

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Yes

Note:
> There’s no cost to you, but we will be restricting the send outs to bi-monthly or quaterly depending on demand.

Requirements:
- Have a JS Bin account (has Github Sign-up)

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by swapagarwal** [comment]
How do you find all these @aslafy-z? Please teach us, master! 😇

**Comment by aslafy-z** [comment]
Haha, they come from various sources. Typically digging into Google, Medium and Twitter  using '+', quotes and google dorks to refine the search. Keywords like: giveaway, freebies, free t-shirt, free stickers, free developers and stuff x).
There also tons of freebies list that are not specialized into dev things but has some as JsBin and Vultr.

**Comment by ssiddhantsharma** [comment]
@swapagarwal I have some tricks to find cool swag items which even @aslafy-z misses at time. I use Linkedin, Instagram, Reddit and twitter and search on them by using various keywords he mentioned. I look for blogs and tweets and usually they have some companies mentioned in them. I plug those companies with a "+ free t-shirt/stickers/socks" in my search bar and viola! There is a ton of swag available this way.

Try using twitter for finding swag, it is much better!
