### ISSUE TITLE
Suggestion: Use a opinionated linter

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#188]
## Issue regarding the website

- [x] I've checked that this isn't a duplicate issue.

Ref @vikaspotluri123 at https://github.com/swapagarwal/swag-for-dev/pull/186#issuecomment-441652111

I'd go for [`xo`](https://github.com/xojs/xo) with the `space: true` option enabled to use spaces instead of tabs, what do you think?

**Comment by swapagarwal** [comment]
`xo` looks great!

**Comment by aslafy-z** [comment]
You're right @vikaspotluri123, I moved the config to spaces.

**Comment by aslafy-z** [comment]
@vikaspotluri123 We have to edit https://github.com/swapagarwal/swag-for-dev/blob/master/.editorconfig#L4 if we go with tabs, or I'll revert the change.

**Comment by vikaspotluri123** [comment]
Go ahead and edit the editorconfig file, that was added during hacktoberfest to limit the spread of files with a mix of tabs and spaces 😄
