### ISSUE TITLE
Suggestion: Use Renovate instead of Greenkeeper

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#194]
- [x] I've checked that this isn't a duplicate issue.

Here some discussion about this:

- https://github.com/googleapis/nodejs-common/issues/59
- https://github.com/magento-research/pwa-studio/issues/286
- https://bugzilla.mozilla.org/show_bug.cgi?id=1409778

**Comment by aslafy-z** [comment]
Greenkeeper glitches, we may want to switch to renovate @swapagarwal

![](https://i.imgur.com/TsulXMJ.jpg)

![](https://i.imgur.com/k0YJZpI.jpg)

**Comment by aslafy-z** [comment]
Here's the related discussion: https://github.com/greenkeeperio/greenkeeper/issues/317

Thanks @plibither8

**Comment by aslafy-z** [comment]
@swapagarwal What do you think of that switch? Greenkeeper did its greenkeeper one more time https://github.com/swapagarwal/swag-for-dev/pull/276

**Comment by aslafy-z** [comment]
Hello @swapagarwal. Can you get an eye on it?

**Comment by swapagarwal** [comment]
Let's switch to Renovate. Greenkeeper is a pain anyway.

**Comment by aslafy-z** [comment]
@swapagarwal Can you install the Renovate app on the repo and delete the Greenkeeper one? Thanks!

**Comment by swapagarwal** [comment]
Done.

**Comment by vikaspotluri123** [comment]
Closing, renovate has been set up and is working. We will probably update the configuration to auto-merge if CI passes without a PR in the future
