### ISSUE TITLE
Add Codefresh Fixvember swag

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#195]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Codefresh

Q. Where have you seen the announcement (URL)?  
A. : https://codefresh.io/fixvember/

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing (t-shirt)

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Yes

The event is already done, so we missed it :(
I add it here for reference, maybe we can merge it with an expired label as It will be renewed next year (https://codefresh.io/fixvember/sign_up/).

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by gatarelib** [comment]
It's no longer available

**Comment by aslafy-z** [comment]
Closing this from now
