### ISSUE TITLE
Add SimbaChain swag

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#196]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : SimbaChain

Q. Where have you seen the announcement (URL)?  
A. : https://simbachain.com/community/join-our-community/

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing (t-shirt)

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Yes

Comes from this discussion: https://github.com/ethereum/go-ethereum/issues/2104#issuecomment-399721639

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by berry120** [comment]
👍  This is an easy t-shirt steal if it works.
