### ISSUE TITLE
Dropdown selector arrow not working

### ISSUE THREAD

**Issue by ardaald** [swapagarwal/swag-for-dev#199]
## Issue regarding the website

- [x] I've checked that this isn't a duplicate issue.

In the dropdown menu for the difficulty level and the listing order the arrows are not clickable. It is working instead on the "Choose tags" button

**Comment by SemperDisco** [comment]
@ardaald Can I work on this issue?

**Comment by ardaald** [comment]
@SemperDisco yes, thank you!

**Comment by vikaspotluri123** [comment]
I can't reproduce this! Could you please post your device + browser information as well as a screen shot? Thanks!

**Comment by ardaald** [comment]
Basically these dropdown arrows are not selectable when i hover, so the menu doesn't drop down but you have to click on the text. It works perfectly instead for the "Choose tags" menu.
![untitled-4-01](https://user-images.githubusercontent.com/44159669/49520227-10cc9200-f8a3-11e8-8e7e-ad48d2954dc2.png)

**Comment by vikaspotluri123** [comment]
Aah, gotcha! It's just the dropdown arrows, not the dropdown itself 👍

**Comment by vikaspotluri123** [comment]
You just need to remove pointer events from the `:before` pseudoselector
