### ISSUE TITLE
Add viral loops swag

### ISSUE THREAD

**Issue by jishvi** [swapagarwal/swag-for-dev#201]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Viral Loops

Q. Where have you seen the announcement (URL)?  
A. : https://vrlps.co/9fzpGHg/cp

Q. What kind of swag (clothing, stickers, ...)?  
A. : Stickers, t-shirt, socks, etc

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Yes

I hope it is okay to submit a referral link.

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by swapagarwal** [comment]
@vikaspotluri123 Take a call (undisclosed referral) here 👀

**Comment by vikaspotluri123** [comment]
Welp my IP was banned? On it, just need a few mins 🏃‍♂️

**Comment by vikaspotluri123** [comment]
I originally thought this was fine - people wouldn't know about this unless we spread the word, and @jishvi was the one to tell us about it. However, now that I think about it, you can't get the swag unless you refer someone, and by us listing it on devSwag, that gives one person many referrals.

Overall, while I personally don't like referral links, I think they're completely acceptable, including as part of devSwag. I think this particular case is niche in that the focus of the company is referrals which is really meta

Please let me know if I misunderstood anything, I feel like I might be missing something here!

**Comment by berry120** [comment]
Meh, this isn't really *dev* for swag, so it doesn't really belong IMHO. Referrals are a bit of a pain, and just result in spam.

**Comment by vikaspotluri123** [comment]
I think we're all in agreement, so I'm closing this
