### ISSUE TITLE
Show pointer cursor instead of default when hovering over filters

### ISSUE THREAD

**Issue by SemperDisco** [swapagarwal/swag-for-dev#206]
## Issue regarding the website

- [x] I've checked that this isn't a duplicate issue.

I think it would be nice to show a pointer instead of the default cursor when hovering over the filters. With a pointer it is more clear that the filter is clickable.

**Comment by vikaspotluri123** [comment]
Point of discussion (I have no preference): We're using native browser elements here so we shouldn't interfere with it as there's a reason for the design

**Comment by SemperDisco** [comment]
I noticed that the tag select box does have a pointer. I think it would be neat if there is one way in which the same kind of elements respond to user interaction.

**Comment by vikaspotluri123** [comment]
Just FYI in terms of implementation, the tag select box is not native and uses the [Selectr](https://github.com/Mobius1/Selectr) library to allow for multiple selections - so standardizing could also include disabling the cursor for the tag selector

Again, I'm fine either way, it's just something to think about / discuss 🙂

**Comment by SemperDisco** [comment]
I think either way is fine, the only important thing is that the filters are uniform in interaction. Who is qualified in making a decision about this?

**Comment by SemperDisco** [comment]
I went ahead and added the pointer cursor. I made a pull request #209.

**Comment by swapagarwal** [comment]
Thanks @SemperDisco! 👍
