### ISSUE TITLE
Add opsdroid sticker pack!

### ISSUE THREAD

**Issue by ssiddhantsharma** [swapagarwal/swag-for-dev#216]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : opsdroid

Q. Where have you seen the announcement (URL)?  
A. : https://medium.com/opsdroid/contributor-sticker-packs-738058ceda59

Q. What kind of swag (clothing, stickers, ...)?  
A. :  Sticker pack (2-3 stickers)

Q. Have you received swag from this?  
A. : Yes

Q. How long did it take?  
A. :  A month or so!

Q. Does it ship worldwide?  
A. : Yes

**Please do not bombard these guys with a fake request, contribute good content and make some meaningful contributions and not just changing 4 lines of documentation. Please be easy on the company and don't let open source down!** 

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aayushbisen** [comment]
Can I work on this?

**Comment by aayushbisen** [comment]
#242

**Comment by aayushbisen** [comment]
I think we can close this now.

**Comment by aslafy-z** [comment]
Fixes #216
