### ISSUE TITLE
Add alligator.io stickers!

### ISSUE THREAD

**Issue by ssiddhantsharma** [swapagarwal/swag-for-dev#217]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Alligator.io

Q. Where have you seen the announcement (URL)?  
A. : https://alligator.io/write-for-us/

Q. What kind of swag (clothing, stickers, ...)?  
A. :  Stickers (only 1)

Q. Have you received swag from this?  
A. : Nopes!

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Yes

Please make meaningful contribution to their blogs!

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by olessiap** [comment]
heyooo, I submitted a pull request for this [here](https://github.com/swapagarwal/swag-for-dev/pull/232)

Please let me know if I did it correctly, it's my first time! 
Thank you,
Olessia

**Comment by ssiddhantsharma** [comment]
@olessiap Thanks for the PR for my issue! Just check the comments on your PR and resolve them. You did great, welcome to the world of Open Source.
