### ISSUE TITLE
Make images interactive

### ISSUE THREAD

**Issue by sseficha** [swapagarwal/swag-for-dev#245]
- [x] I've checked that this isn't a duplicate issue.

When I saw the website the first thing I tried to do was a click on an image. How about we made the pictures interactive (and maybe clicking them served the purpose of a link)?

**Comment by wanderdust** [comment]
Hey! I want to give this a go. Is there anyone currently working on it?

**Comment by aslafy-z** [comment]
@wanderdust I think before giving this a go we need to define what needs to be done.
@sseficha I understood you wanted to use images as links but, what do you mean by interactive?

**Comment by sseficha** [comment]
Get a response when hovering, something like a highlighted border, maybe change the transparency of the image etc. Something simple which can be implemented just with css.

**Comment by vikaspotluri123** [comment]
How about scaling up a bit when the card is hovered?

**Comment by wanderdust** [comment]
I was thinking to keep it simple, with a light gray color when the card is hovered. Also I would make the whole card a link rather than just the image.

**Comment by sseficha** [comment]
However, if we decide to implement it should have some function. I thought it should serve the role of a link, but we already have "check it out", so there is no point in having a duplicate link. That's why I mentioned in #151 that "check it out", could serve a different role, something less frequently used, while having a bigger, more obvious response from the image.
