### ISSUE TITLE
Order alphabetically within difficulties  (categories) 

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#253]
## Issue regarding the website

- [x] I've checked that this isn't a duplicate issue.

When ordering by difficulty, items aren't shown in a alphabetical order. We might want to order alphabetically within each difficulty to keep it clean.

![2019-01-17-000331_756x245_scrot](https://user-images.githubusercontent.com/8191198/51284303-583e5600-19eb-11e9-9461-cae55867ffc1.png)

Steps to reproduce:
- Set `Show` to `All difficulties`
- Set `In` to `Difficulty` 

Issue: Items aren't shown in alphabetical order

**Comment by co16353sidak** [comment]
@aslafy-z would love to work on this if anyone isn't

**Comment by vikaspotluri123** [comment]
@co16353sidak go ahead 👍

**Comment by co16353sidak** [comment]
I would love some clarification here as to how the ordering has to take place because as I can infer from the website the following:- 

> We can firstly choose a difficulty category, and then we can choose whether to sort the listing in that particular category in alphabetical or reverse order.

<img width="1146" alt="screenshot 2019-02-13 at 12 42 21 am" src="https://user-images.githubusercontent.com/35738138/52661510-3cfe3200-2f28-11e9-981c-3a81fd358aaa.png">

I don't seem to understand @aslafy-z 's issue here.

(_haven't tested locally._)
(@vikaspotluri123 )

**Comment by aslafy-z** [comment]
@co16353sidak 

> Steps to reproduce:
> - Set `Show` to `All difficulties`
> - Set `In` to `Difficulty` 
> 
> Issue: Items aren't shown in alphabetical order

**Comment by thethomasz** [comment]
@aslafy-z I think I've got a working solution to this issue. Is it okay for me to write a PR for it? If so, are there any conventions I should follow on branch naming or PR format?

**Comment by vikaspotluri123** [comment]
@thethomasz feel free to PR, I've assigned you to the issue 😄 We don't have any specifics you need to follow 👍

**Comment by thethomasz** [comment]
Awesome, thanks @vikaspotluri123!

**Comment by thethomasz** [comment]
#296
