### ISSUE TITLE
NativeScript First-Time Contribution Program

### ISSUE THREAD

**Issue by etabakov** [swapagarwal/swag-for-dev#257]
## Wild swag opportunity appeared!

- [X] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : [Progress Software](https://www.progress.com/)

Q. Where have you seen the announcement (URL)?  
A. : [NativeScript First-Time Contribution Program](https://www.nativescript.org/blog/nativescript-first-time-contribution-contest-continued-and-extended)

Q. What kind of swag (clothing, stickers, ...)?  
A. : Stickers + extra bonus for exceptional contributions

Q. Have you received swag from this?  
A. : No, since I'm one of the organisers.

Q. How long did it take?  
A. : Several a weeks, depending on how far the destination country is from Europe.

Q. Does it ship worldwide?  
A. : Yes

I'm one of the organisers of the program.

- [X] I've checked that the promotion is legit.
- [X] I've checked that it's still available to the public.

**Comment by Yash-Garg** [comment]
Great!

**Comment by sohailg** [comment]
Is it still available?
