### ISSUE TITLE
Dribbble Free Sticker Pack

### ISSUE THREAD

**Issue by sidhyatikku** [swapagarwal/swag-for-dev#265]
## Wild swag opportunity appeared!

- [X] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Dribbble

Q. Where have you seen the announcement (URL)?  
A. : [Dribbble Survey Popup](https://dribbble-feedback.typeform.com/to/WXhskq)

Q. What kind of swag (clothing, stickers, ...)?  
A. : Sticker Pack

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : Idk

Q. Does it ship worldwide?  
A. : Yes

### Complete the Survey and get free Dribbble Swag.

- [X] I've checked that the promotion is legit.
- [X] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
Thanks @sidhyatikku ! It took 6 weeks for my pack to arrive in France after I got the confirmation email. :-)

**Comment by sidhyatikku** [comment]
@aslafy-z mine took 12 days 😄

**Comment by Yash-Garg** [comment]
@sidhyatikku In which country do you live ?

**Comment by sidhyatikku** [comment]
@Yash-Garg India

**Comment by Yash-Garg** [comment]
Damn that is fast!

**Comment by AnushPatel** [comment]
They have run out of stickers :(

**Comment by tonyvince** [comment]
Received sticker-pack in Germany within 1 week of filling survey.
