### ISSUE TITLE
Codeship do not send t-shirts anymore

### ISSUE THREAD

**Issue by greybax** [swapagarwal/swag-for-dev#269]
## Issue with an existing swag opportunity

- [x] I've checked that this isn't a duplicate issue.

Q. Which opportunity?  
A. : Codeship

I've got codeship swags yesterday and they do not send t-shirts anymore. Only stickers.

**Comment by hexandcube** [comment]
I can confirm this. I received my stickers 2 weeks ago.

**Comment by KartSriv** [comment]
I can confirm this too. Just got three stickers today.
