### ISSUE TITLE
Create Google code-in swag oppertunity

### ISSUE THREAD

**Issue by vmr1532** [swapagarwal/swag-for-dev#270]
## Wild swag opportunity appeared!

- [ ] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : GOOGLE CODE IN

Q. Where have you seen the announcement (URL)?  
A. : https://codein.withgoogle.com/archive/

Q. What kind of swag (clothing, stickers, ...)?  
A. : TSHIRT,STICKERS

Q. Have you received swag from this?  
A. : NO

Q. How long did it take?  
A. : 1 MONTH

Q. Does it ship worldwide?  
A. : 

- [ ] I've checked that the promotion is legit.
- [ ] I've checked that it's still available to the public.

**Comment by Yash-Garg** [comment]
2019 one has not started yet, why creating an issue now?

**Comment by vmr1532** [comment]
just created this for reference for letting others know such opportunity exists

**Comment by Yash-Garg** [comment]
Oh okay, great then !

**Comment by sidhyatikku** [comment]
@vmr1532 this seems misleading. Imo you should've created a post after 2019 GCI started.

**Comment by aslafy-z** [comment]
Closing this as it's a duplicate of #175 

Thanks anyway @vmr1532
