### ISSUE TITLE
 Wild swag opportunity appeared: Free Software Foundation Europe

### ISSUE THREAD

**Issue by KartSriv** [swapagarwal/swag-for-dev#271]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Free Software Foundation Europe

Q. Where have you seen the announcement (URL)?  
A. : devRant

Q. What kind of swag (clothing, stickers, ...)?  
A. : Stickers, Booklets, Posters, etc

Q. Have you received swag from this?  
A. : Yes

Q. How long did it take?  
A. : 2 Weeks

Q. Does it ship worldwide?  
A. : Yes

Refer: https://fsfe.org/contribute/spreadtheword.en.html

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by tonyvince** [comment]
Received swag in Germany in 2 days

**Comment by KartSriv** [comment]
@tonyvince cause FSFE is based in Germany. Took two weeks to arrive in India. I actually submitted multiple times and I got two packages. You can try it.

**Comment by KartSriv** [comment]
@swapagarwal I actually thought you abandoned this repo until I saw your mail today.

**Comment by KartSriv** [comment]
@swapagarwal what's up with not responding to this issue?

**Comment by KartSriv** [comment]
@swapagarwal I lost hope on this repo.

**Comment by aslafy-z** [comment]
Please don't, sorry for not responding promptly! 
We need to add this the list, are you up to open a PR for it? 
Thank you!

**Comment by KartSriv** [comment]
@aslafy-z Okay, I'll create a PR :+1:

**Comment by KartSriv** [comment]
PR approved. 
Waiting for merger.

**Comment by crweiner** [comment]
It seems like the FSFE doesn't really want to be listed here. Clicking the link from devswag.io as a refer redirects you to here: https://fsfe.org/contribute/spreadtheword-freebie.html

**Comment by swapagarwal** [comment]
@crweiner Thanks for notifying! I've removed it in https://github.com/swapagarwal/swag-for-dev/commit/a66c6cacfb3a51b6f026f973cd7c61a9f0471c77.
