### ISSUE TITLE
Mullvad Sticker link changed

### ISSUE THREAD

**Issue by vantezzen** [swapagarwal/swag-for-dev#272]
## Issue with an existing swag opportunity

- [x] I've checked that this isn't a duplicate issue.

Q. Which opportunity?  
A.: Mullvad 

The current Mullvad stickers link (https://www.mullvad.net/en/guides/mullvad-stickers-and-merchandise/) doesn't work anymore (404 - Not Found).
Mullvad does however still offer stickers through the process described in their blog article at https://mullvad.net/en/blog/2017/6/30/mullvad-merch-available/.

PR #273 will fix the Mullvad link in `data.json`

**Comment by swapagarwal** [comment]
Thanks Bennett for taking the time to report and fix this. 😇
