### ISSUE TITLE
DigitalOcean Currents Survey 2019

### ISSUE THREAD

**Issue by tonyvince** [swapagarwal/swag-for-dev#275]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. :  DigitalOcean

Q. Where have you seen the announcement (URL)?  
A. : https://digitalocean.getfeedback.com/r/t382vCPz/

Q. What kind of swag (clothing, stickers, ...)?  
A. : Sticker

Q. Have you received swag from this?  
A. : Not Yet

Q. How long did it take?  
A. : NA

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by swapagarwal** [comment]
Broadcasted this to our 1000+ newsletter subscribers in the morning. 🙂
Seems like this would be short-lived so not adding it to the website.

**Comment by KartSriv** [comment]
Thanks, @tonyvince! Just filled the form today.

**Comment by Yash-Garg** [comment]
Filled it, thanks @tonyvince <3

**Comment by swapagarwal** [comment]
@zac-garby @vikaspotluri123 The form is still open. Should we merge this?

**Comment by zac-garby** [comment]
I would say so. Not sure how much longer it will be open for.

**Comment by vikaspotluri123** [comment]
I don't see any issues 👍

**Comment by zeeshanofficial** [comment]
Looks like it's closed. 🚪
