### ISSUE TITLE
Open links in new tab.

### ISSUE THREAD

**Issue by TorRydberg** [swapagarwal/swag-for-dev#277]
- [x] I've checked that this isn't a duplicate issue.

It's easy for users to get lost on sites that redirect when opening links. Would it be ok to add functionality that opens swag opportunities in a new tab? I have a fix ready to go.

**Comment by swapagarwal** [comment]
Makes sense. Please go ahead! 


---- On Thu, 23 May 2019 23:11:23 +0530 notifications@github.com wrote ----


 I've checked that this isn't a duplicate issue.

It's easy for users to get lost on sites that redirect when opening links. Would it be ok to add functionality that opens swag opportunities in a new tab? I have a fix ready to go.

**Comment by TorRydberg** [comment]
Done and done.

**Comment by swapagarwal** [comment]
🚀
