### ISSUE TITLE
Suggestion: add Issue and Pr templates

### ISSUE THREAD

**Issue by butlerx** [swapagarwal/swag-for-dev#28]
Might be an idea to add [issue and pr templates](https://github.com/blog/2111-issue-and-pull-request-templates)
the pr templates could give a checklist for adding new swag 
issue template could give things to check such as is it a duplicate

**Comment by swapagarwal** [comment]
Sure, go for it! 💯

**Comment by swapagarwal** [comment]
The template definitely needs to have a field which asks "Have you received swag from this?" 😅

**Comment by swapagarwal** [comment]
Anyone wants to take a shot at this?

**Comment by TooPlain** [comment]
I’ll give it a shot when I get off work. 
What would you like to see in the templates?

**Comment by swapagarwal** [comment]
Some basic questions, like does it ship worldwide? Have you received swag from this? How much time did it take? etc. Feel free to add your own questions! 😄

**Comment by TooPlain** [comment]
Okay sounds good I’ll submit a pull request as soon as possible 👍

**Comment by swapagarwal** [comment]
Closed in #41
