### ISSUE TITLE
Add navigation bar

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#286]
Add a bootstrap navbar which will enable page viewers to maneuver the webpages. 
`<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">DevSwag</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="#">About Us</a>
      <a class="nav-item nav-link" href="#">Projects</a>
      <a class="nav-item nav-link disabled" href="#">Contact Us</a>
    </div>
  </div>
</nav>`

_Originally posted by @Ernst-Wong in https://github.com/swapagarwal/swag-for-dev/pull/267#issuecomment-465521325_

**Comment by ashannon1990** [comment]
If this task is still available, I'd like to help with it.

**Comment by vikaspotluri123** [comment]
@ashannon1990 go for it!

**Comment by Hardik500** [comment]
Is this still open?

**Comment by vikaspotluri123** [comment]
@Hardik500 I'm going to give @ashannon1990 a few days before opening the opportunity to you 😄

**Comment by ashannon1990** [comment]
@vikaspotluri123 you can open it for @Hardik500, I am currently working on my final project for school, so I need to focus my time on that.

**Comment by gonpeche** [comment]
hi! is this feature being develop by @Hardik500 ? If not, I would be happy to assist.

**Comment by wale-bant** [comment]
Hi, i'd like to implement this feature if it's still up for grabs. Thanks.

**Comment by Hardik500** [comment]
Yeah sure go for it.

**Comment by Pradyumn-S** [comment]
Is it still open? I'd like to implement it.

**Comment by vikaspotluri123** [comment]
@wale-bant are you currently working on this? If not, I'll assign @Pradyumn-S 😄

**Comment by ritesh-pandey** [comment]
Is the issue still open? @wale-bant hasn't replied. I'd like to take it up.

**Comment by vikaspotluri123** [comment]
Go for it @ritesh-pandey
