### ISSUE TITLE
 ✨ Stackbit Swag ✨ 

### ISSUE THREAD

**Issue by gatarelib** [swapagarwal/swag-for-dev#287]
## Wild swag opportunity appeared!

- [X] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : [Stackbit](http://stackbit.com)

Q. Where have you seen the announcement (URL)?  
A. : [Swag Form](https://docs.google.com/forms/d/e/1FAIpQLScbrv5cQlX7xx-W2h66r1FsJp_uZw5OPNby1OUR0WelG_lPXw/viewform?usp=send_form)

Q. What kind of swag (clothing, stickers, ...)?  
A. : T-Shirt and Stickers

Q. Have you received swag from this?  
A. : Still Shipping

Q. How long did it take?  
A. : Depends on your location

Q. Does it ship worldwide?  
A. : Yep

- [X] I've checked that the promotion is legit.
- [X] I've checked that it's still available to the public.

**Comment by swapagarwal** [comment]
It'd be great if you could mention the source as well, i.e. where / how did you find it? This is to ensure that the form is legit and not just trying to collect data. 😇

**Comment by gatarelib** [comment]
I get your concern,
I asked them on twitter, I can send you a screenshot if you like

**Comment by gatarelib** [comment]
![stackbit](https://user-images.githubusercontent.com/29035759/58622661-ccabce80-82d4-11e9-8d7b-a3255ff31f22.png)

**Comment by swapagarwal** [comment]
Please remove the bit.ly link.

**Comment by gatarelib** [comment]
On it

**Comment by swapagarwal** [comment]
@gatarelib Thanks for taking the time to contribute! ❤️ 
I just have one last concern, regarding the last item in the issue template: It seems more like a personalized offering, i.e. it's not available to the public. What are your thoughts on this?

**Comment by gatarelib** [comment]
I thought so too, until I came across this [tweet](https://twitter.com/stackbithq/status/1104094100855259136) from Stackbit

**Comment by swapagarwal** [comment]
Awesome! 💯

**Comment by aayushbisen** [comment]
Hey @swapagarwal should we merge this?

**Comment by swapagarwal** [comment]
Have you received this swag? 


---- On Thu, 20 Jun 2019 20:03:43 +0530 notifications@github.com wrote ----



Hey @swapagarwal should we merge this?

**Comment by aayushbisen** [comment]
No.

**Comment by swapagarwal** [comment]
@aayushbisen Let's wait for someone to confirm they received it. 
@gatarelib Have you received this swag? 😇

**Comment by gatarelib** [comment]
Not yet, will update you when I do so

**Comment by shanirub** [comment]
Hi there,
I've received two letters with stickers, but sadly no shirts.

**Comment by gatarelib** [comment]
Thx for the info
Tees are not assured due to shipping fees

**Comment by wulforr** [comment]
The form is no longer available

**Comment by aslafy-z** [comment]
Thanks for reporting @wulforr. Thanks for the opportunity @gatarelib!

**Comment by robotshateme** [comment]
Hmm still haven't received.
