### ISSUE TITLE
Waffle.io swag

### ISSUE THREAD

**Issue by Ishaan28malik** [swapagarwal/swag-for-dev#288]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Waffle.io

Q. Where have you seen the announcement (URL)?  
A. : On there Website 

Q. What kind of swag (clothing, stickers, ...)?  
A. : Stickers

Q. Have you received swag from this?  
A. : Yes

Q. How long did it take?  
A. : a month 

Q. Does it ship worldwide?  
A. : Yup

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
The website looks to be offline :/

**Comment by Ishaan28malik** [comment]
No it's online and received them recently @aslafy-z

**Comment by Ishaan28malik** [comment]
Yes you are write @aslafy-z it's being taken over now , so don't know the updates
