### ISSUE TITLE
Jetbrains 

### ISSUE THREAD

**Issue by Ishaan28malik** [swapagarwal/swag-for-dev#289]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Jetbrains

Q. Where have you seen the announcement (URL)?  
A. : 
https://surveys.jetbrains.com/s3/Get-your-complimentary-JetBrains-stickers

Q. What kind of swag (clothing, stickers, ...)?  
A. : Stickers

Q. Have you received swag from this?  
A. : Yes

Q. How long did it take?  
A. : 3 weeks

Q. Does it ship worldwide?  
A. : Yes

- [ ] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by Yash-Garg** [comment]
Can u provide the link ?

**Comment by V0lk3n** [comment]
https://surveys.jetbrains.com/s3/Get-your-complimentary-JetBrains-stickers

**Comment by V0lk3n** [comment]
I've send the request of those stickers right now, let you know if i will receive them :)

**Comment by Ishaan28malik** [comment]
U will be receiving them as I received them so pls update this to the
website and except the issue .

**Comment by V0lk3n** [comment]
Didnt receive it yet so...

**Comment by aslafy-z** [comment]
I opened a PR implementing this swag offer. Do not hesitate to propose change if needed.

**Comment by aslafy-z** [comment]
It's live now at https://devswag.io
