### ISSUE TITLE
Google Cloud Platform Quest Leader 2019

### ISSUE THREAD

**Issue by Souvik-py** [swapagarwal/swag-for-dev#290]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Google

Q. Where have you seen the announcement (URL)?  
A. : http://tiny.cc/qwiklabs-hero

Q. What kind of swag (clothing, stickers, ...)?  
A. : Probably Stickers (They haven't mentioned)

Q. Have you received swag from this?  
A. : Not Yet

Q. How long did it take?  
A. : Not Yet 

Q. Does it ship worldwide?  
A. : May be

Expirey date : 31/06/2019

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by Anant016** [comment]
I think this is fake since the form is not collecting any of our info- such as mail id, address or even phone no.

**Comment by swapagarwal** [comment]
Closing this as swag items aren't mentioned. 🙁

**Comment by Souvik-py** [comment]
You'll receive exclusive GCP goodies straightaway from Google..

**Comment by Anant016** [comment]
I completed more than what mentioned there, submit google form, but didn't receive any acknowledgment message nor any response

**Comment by Souvik-py** [comment]
Wait till 30th of this month.. they will roll out the further details after deadline..

**Comment by Souvik-py** [comment]
Hi @Anant016 , hope you got your mail to redeem the swag..
