### ISSUE TITLE
Add autoprefixer to build system

### ISSUE THREAD

**Issue by vikaspotluri123** [swapagarwal/swag-for-dev#297]
As part of this, we also need to remove prefixed code

_Originally posted by @aslafy-z in https://github.com/swapagarwal/swag-for-dev/pull/264_

**Comment by plibither8** [comment]
Fairly simple, we can use one of the two ways: PostCSS or a direct autoprefixing module. If we use PostCSS, we can use other plugins to optimise CSS output and ease development.
