### ISSUE TITLE
Remove Mullvad swag opportunity

### ISSUE THREAD

**Issue by roshanadh** [swapagarwal/swag-for-dev#298]
## Issue with an existing swag opportunity

- [x] I've checked that this isn't a duplicate issue.

Q. Which opportunity?  
A. :  Mullvad

Mullvad does not send out stickers anymore. They will mail you back informing that they only handout stickers at conferences or other events

**Comment by imarchit19** [comment]
Yes, they reply, they are not sending out stickers anymore. They currently only hand out stickers at conferences and other events where they attend.

**Comment by santiblanko** [comment]
sexo anall que rico

**Comment by vikaspotluri123** [comment]
closed in #228, thanks!
