### ISSUE TITLE
Should we include non-tangible swag as well?

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/swag-for-dev#3]
e.g. Submitting an app for Google Assistant entitles you to receive up to $200 of Google Cloud services a month - for a full year!
Should we add this to the list? What do you think?

**Comment by pladaria** [comment]
I wouldn't consider that swag, otherwise this is going to be flooded with coupon codes, discounts, etc.

**Comment by BitpopCoin** [comment]
I consider it swag if there's no purchase required, discounts wouldn't be allowed nor limited time trials.

**Comment by BrianLima** [comment]
If it is a license for a free software, os Steam wallet codes or similar things it could be added maybe.

**Comment by y-mehta** [comment]
Why don't we make a separate branch or directory for that?

**Comment by kevin51jiang** [comment]
Oh crap, this project is gonna end up _real_ complicated.

**Comment by till-tomorrow** [comment]
Don't add discount coupons, instead add free services in the non-tangible swags.

**Comment by kevin51jiang** [comment]
I don't think non-tangible stuff should be added _at all_.

This is because [there's already a repo for free services/non-tangible swag.](https://github.com/ripienaar/free-for-dev)
