### ISSUE TITLE
IPFS Swag package.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [swapagarwal/swag-for-dev#300]
## Wild swag opportunity appeared! :o

- [✔️] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : IPFS

Q. Where have you seen the announcement (URL)?  
A. : https://github.com/ipfs/community/#swag

Q. What kind of swag (clothing, stickers, ...)?  
A. : I´ve received a T-shirt with the IPFS logo, and 50 IPFS logo stickers.

Q. Have you received swag from this?  
A. : Yes.

Q. How long did it take?  
A. : Around less than one week.

Q. Does it ship worldwide?  
A. : Yes. It looks like it. I´m from France for reference.

I don’t even feel that confortable to post this opportunity as free T-shirts seems expensive for me, but hey, It's merchandising, and its public!
Also, More swag could potentially be obtained, as no precise description is done in the post. So, I was quite a bit hesitant as I was just expecting to receive only some stickers.

- [✔️] I've checked that the promotion is legit.
- [✔️] I've checked that it's still available to the public.

You´re welcome, template people.

**Comment by Soundug** [comment]
@PoorPocketsMcNewHold The swag is a sticker as mentioned in the Readme, how did you manage to get a t-shirt?

**Comment by PoorPocketsMcNewHold** [comment]
![BURST20190824102618103](https://user-images.githubusercontent.com/13170204/63634719-9a530880-c65a-11e9-9937-05a70564d1e8.jpg)
Well as you can see, I’ve did get one with that set of Stickers.
Our conversation went a bit like this:

> -So do you have any particular piece of merch that you would want to request ?
> - Well... I was expecting just some stickers, so i suppose anything with the main IPFS logo atleast.
> - Sure, I´ll throw a T-shirt for you.

Despite i’m a user of IPFS myself, I’m not a dev who has used this technology (You can check this, by looking to my profile), so I was indeed surprised (But extremely proud and happy) to receive a T-shirt.
As they don’t explicitly really tell what you could get (Just as you’ve said, old mentions of stickers from their old provider), I can’t really say for sure if everyone could get a T-shirt, and if they were some others things IPFS branded that you could get.
As I was obviously, more than happy to receive my swag package from them, I didn’t research more.

**Comment by aslafy-z** [comment]
Thanks @PoorPocketsMcNewHold. Could you please open a PR for it? Thanks!
