### ISSUE TITLE
DigitalOcean Currents Survey Open Source 2019

### ISSUE THREAD

**Issue by shanirub** [swapagarwal/swag-for-dev#304]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : DigitalOcean

Q. Where have you seen the announcement (URL)?  
A. : https://digitalocean.getfeedback.com/r/p44ADlqG/

Q. What kind of swag (clothing, stickers, ...)?  
A. : a sticker ("a limited edition open source "Sammy Shark" sticker!")

Q. Have you received swag from this?  
A. : not yet (but i did receive a sticker for answering the last survey)

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by swapagarwal** [comment]
This survey has ended.
