### ISSUE TITLE
DigitalOcean Hacktoberfest 2019  opportunity

### ISSUE THREAD

**Issue by GuyKh** [swapagarwal/swag-for-dev#307]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : DigitalOceal

Q. Where have you seen the announcement (URL)?  
A. : https://hacktoberfest.digitalocean.com/

Q. What kind of swag (clothing, stickers, ...)?  
A. : Clothing

Q. Have you received swag from this?  
A. : no

Q. How long did it take?  
A. : --

Q. Does it ship worldwide?  
A. :  --

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

#306

**Comment by swapagarwal** [comment]
Merged in #306
