### ISSUE TITLE
Remove JetBrains opportunity

### ISSUE THREAD

**Issue by ZAfricanDev** [swapagarwal/swag-for-dev#308]
## Issue with an existing swag opportunity

- [ X] I've checked that this isn't a duplicate issue.

Q. Which opportunity?  
A. : Jetbrains

Jetbrains Swag no longer offered, they will be updating their swag offerings according to their site.
<img width="1195" alt="Screen Shot 2019-09-25 at 9 02 33 PM" src="https://user-images.githubusercontent.com/55801467/65631459-dd94f400-dfd7-11e9-8770-2cc556d0e51e.png">

**Comment by swapagarwal** [comment]
Thanks for notifying! Updated.
