### ISSUE TITLE
Hacktoberfest 2019 CircleCI swag

### ISSUE THREAD

**Issue by alistairholmes** [swapagarwal/swag-for-dev#310]
## Circle CI Swag!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Circle CI

Q. Where have you seen the announcement (URL)?  
A. : https://circleci-public.github.io/hacktoberfest/?mkt_tok=eyJpIjoiT1RSbE5qZGhNRGMwTVRSaSIsInQiOiJKQW9cL0d1eUxaTTdkTTZCK0hxUDlIZGs3dklGXC9La2E5R3FxS0dwWnREcmZXcGVxZ05DOThTMUtSNFlXdXhPK0tBNXhZNXhNcEsyYUtjSVVZTFhWRm9JY2M0NHpxbU9cL1d5ZXFFU1czSytsS28zTXZabTVsK3lCVVZ2cW1xZG9zeCJ9#/

Q. What kind of swag (clothing, stickers, ...)?  
A. : T-shirt

Q. Have you received swag from this?  
A. : Nope

Q. How long did it take?  
A. : 

Q. Does it ship worldwide?  
A. : 

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by swapagarwal** [comment]
Awesome! Can you submit a PR?

**Comment by alistairholmes** [comment]
Sure will do :wink:

**Comment by swapagarwal** [comment]
Added!
