### ISSUE TITLE
Hacktoberfest 2019: Hasura

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#314]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Hasura

Q. Where have you seen the announcement (URL)?  
A. : https://blog.hasura.io/hasura-joins-hacktoberfest-2019/

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing, stickers

Q. Have you received swag from this?  
A. : no

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Dunno

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by rchavarria** [comment]
Hi! I'll take this one. I'll update last year Hasura's entry.

**Comment by vikaspotluri123** [comment]
closed in #356
