### ISSUE TITLE
Hacktoberfest 2019: Uno

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#317]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Uno

Q. Where have you seen the announcement (URL)?  
A. : https://platform.uno/uno-is-joining-hacktoberfest-2019/

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing, non-disclosed

Q. Have you received swag from this?  
A. : no

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Dunno

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by ayoola-solomon** [comment]
@aslafy-z do you mind if I work on this?

**Comment by vikaspotluri123** [comment]
@ayoola-solomon I've assigned you to this, thanks!
