### ISSUE TITLE
Hacktoberfest 2019: MayaData (OpenEBS & Litmus)

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#318]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : MayaData

Q. Where have you seen the announcement (URL)?  
A. : https://twitter.com/mayadata_inc/status/1177725829138305029

Q. What kind of swag (clothing, stickers, ...)?  
A. : TBD

Q. Have you received swag from this?  
A. : no

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Dunno

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by GuyKh** [comment]
It's `MyData.io`
Opened a PR: #348
