### ISSUE TITLE
Hacktoberfest 2019: Umbraco

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#320]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Umbraco

Q. Where have you seen the announcement (URL)?  
A. : https://umbraco.com/blog/hacktoberfest-2019/

Q. What kind of swag (clothing, stickers, ...)?  
A. : TBD

Q. Have you received swag from this?  
A. : no

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Dunno

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by MasterKN48** [comment]
I want to take this issue.

**Comment by duydosomething** [comment]
Submitted #346 :)

**Comment by crweiner** [comment]
Umbraco has asked not to be on these swag lists, see [here](https://github.com/crweiner/hacktoberfest-swag-list/issues/44#issuecomment-535131859) for links to tweets from some of the devs who don't like what we do....
