### ISSUE TITLE
Hacktoberfest 2019: LBRYio

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#322]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : LBRYio

Q. Where have you seen the announcement (URL)?  
A. : https://lbry.com/news/hacktoberfest-2019

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing

Q. Have you received swag from this?  
A. : no

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Dunno

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
Updated with the official article!

**Comment by yesh0907** [comment]
I see that the PR has been merged. Does this mean this issue can be closed? If not I would like to help make my first contribution!
Thanks

**Comment by vikaspotluri123** [comment]
Thanks @yesh0907, closing!
