### ISSUE TITLE
Hacktoberfest 2019 : Parity

### ISSUE THREAD

**Issue by crashoverloaded** [swapagarwal/swag-for-dev#326]
## Wild swag opportunity appeared!

- [ Yes ] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Parity Technologies 

Q. Where have you seen the announcement (URL)?  
A. : https://www.parity.io/hacktoberfest-2019-parity/

Q. What kind of swag (clothing, stickers, ...)?  
A. : Limited edition gym bag

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : Don't Know

Q. Does it ship worldwide?  
A. : Yes

- [ Yes ] I've checked that the promotion is legit.
- [ Yes ] I've checked that it's still available to the public.

Thanks

**Comment by OpeOnikute** [comment]
Hello @aslafy-z, I want to add this.

**Comment by aslafy-z** [comment]
Closed with #428
