### ISSUE TITLE
BlockStack Swag

### ISSUE THREAD

**Issue by fzs1994** [swapagarwal/swag-for-dev#329]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : BlockStack

Q. Where have you seen the announcement (URL)?  
A. : https://community.blockstack.org/stickers

Q. What kind of swag (clothing, stickers, ...)?  
A. : Stickers

Q. Have you received swag from this?  
A. : Not yet, but it's shipped. I got tracking id from them.

Q. How long did it take?  
A. : Usually after a week, they shipped

Q. Does it ship worldwide?  
A. : Yes

P.S. I'll we working on PR for this 😎

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
Closed as per https://github.com/swapagarwal/swag-for-dev/pull/335#issuecomment-538419706
