### ISSUE TITLE
Setup metadata tags (OpenGraph)

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#333]
## Issue regarding the website

- [x] I've checked that this isn't a duplicate issue.

Currently the website doesn't have any Sharing tags (OpenGraph, Twitter...)
When I share it, it shows the 7PHP logo every time which is not pretty. 

We should add some metadata tags with an image in order to have a clean share preview.

Tools:
https://metatags.io/
https://htmlhead.dev/

**Comment by sarscode** [comment]
Hello, @swapagarwal may I fix this?

**Comment by vikaspotluri123** [comment]
@sarscode go for it!

**Comment by sarscode** [comment]
Thanks, @vikaspotluri123 I have submitted a PR.

**Comment by varunseth5788** [comment]
i would like to contribute to this issue.
or need any other help.

**Comment by dhruvkaravadiya** [comment]
is this issue still open? I would like to contribute to this
