### ISSUE TITLE
Website: Change the text header

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#337]
## Issue regarding the website

Change the text headers to match the new "directives".

(All of them ship worldwide!)

**Comment by maybebored** [comment]
Hi what do you mean by text headers? I feel a screenshot would help.

**Comment by Yash-Garg** [comment]
> Hi what do you mean by text headers? I feel a screenshot would help.

![Capture](https://user-images.githubusercontent.com/33605526/66051856-38d16400-e54d-11e9-9449-32cc5ee1ba2d.PNG)

He means to change the last line in this screenshot i.e **All of them ship worldwide!**

**Comment by swapagarwal** [comment]
Which ones do not?

**Comment by Yash-Garg** [comment]
> Which ones do not? 🤔

Codeship doesn't xD

**Comment by swapagarwal** [comment]
Yes, and that's why we have mentioned that in the description.

**Comment by Yash-Garg** [comment]
> Yes, and that's why we have mentioned that in the description.

Yeah, i know. Blame @aslafy-z for issue xP
