### ISSUE TITLE
Website: Change default sorting to newest first

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/swag-for-dev#338]
## Issue regarding the website

- [x] I've checked that this isn't a duplicate issue.

Let's change the default sorting from alphabetical to newest first so that new opportunities are easily discoverable. 🙂

**Comment by versavale** [comment]
Can I try this?

**Comment by itnug987** [comment]
@swapagarwal Can I work on this issue?

**Comment by vikaspotluri123** [comment]
@itnug987 #343 is already in progress
