### ISSUE TITLE
Change 404ing links to webarchive

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#340]
Instead of using the Google Search cache, we should use the web.archive.org project at http://web.archive.org/

**Comment by swapagarwal** [comment]
Or we can just skip checking the items tagged as expired.

Originally posted by @Glennmen in https://github.com/swapagarwal/swag-for-dev/pull/362#issuecomment-538082559

**Comment by Glennmen** [comment]
I noticed you are already using cloudfront for image caching so that shouldn't be an issue, only issue would be that `Check it out` will link to an non existing page but then again this isn't abnormal for expired events.

**Comment by vikaspotluri123** [comment]
> I noticed you are already using cloudfront for image caching so that shouldn't be an issue

FWIW _we_ don't use cloudfront, our host (Netlify) does this for us. This does bring up an interesting question - should we add the downloaded assets to the build cache, so we only need to download new ones 🤔

**Comment by Glennmen** [comment]
@vikaspotluri123 Good point, not sure about the build/deploy fase. But is it okay to skip expired events in the testing fase?

**Comment by vikaspotluri123** [comment]
I'm waiting for @swapagarwal to get back to me - we discussed it when working on #228 and ultimately decided against it

**Comment by swapagarwal** [comment]
As discussed, we shall be removing the entries containing 404ing links from data.json
