### ISSUE TITLE
Start merging new offers?

### ISSUE THREAD

**Issue by kevin51jiang** [swapagarwal/swag-for-dev#36]
There's been quite a lot of pull requests, and most new offers were even tagged.

Should they start being merged soon?

**Comment by remram44** [comment]
Creating new issues is probably not the best way to reduce the backlog of tickets 😅

**Comment by kevin51jiang** [comment]
True... Just thought it would be more organized than commenting in a thread. :P

**Comment by swapagarwal** [comment]
So basically, I'm waiting for the community to provide their feedback on whether they received swag from the mentioned sites. Once a PR reaches a certain level of engagement, I'll merge it in! 😅

**Comment by swapagarwal** [comment]
Mullvad (#29) was merged in! 🎉

**Comment by mislavcimpersak** [comment]
@swapagarwal perhaps you should explain that in the readme file. People are probably using the offers from the PRs, but are not commenting.

**Comment by alokvnair** [comment]
No point of pull request when they never get merged. In this repo people will find more swags in pending pull requests than in main repo...

**Comment by swapagarwal** [comment]
Updated README.md https://github.com/swapagarwal/swag-for-dev/commit/eb7d5e051266011acf210b9a2b613e477025ddff
