### ISSUE TITLE
Hacktoberfest 2019: Devfolio

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#363]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Devfolio 

Q. Where have you seen the announcement (URL)?  
A. : https://devfolio.co/blog/hacktoberfest-2019-devfolio/

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing, stickers

Q. Have you received swag from this?  
A. : no

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Dunno

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by anabellaspinelli** [comment]
Hello! I can add this if nobody else is doing it. Will create a PR today 😉
