### ISSUE TITLE
Hacktoberfest 2019: QMK

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#368]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : QMK

Q. Where have you seen the announcement (URL)?  
A. : https://hacktoberfest.qmk.fm/

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing

Q. Have you received swag from this?  
A. : no

Q. How long did it take?  
A. : N/A

Q. Does it ship worldwide?  
A. : Dunno

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by jrwiegand** [comment]
@aslafy-z @vikaspotluri123 Would you all be fine with me opening another PR for this one as it seems the current PR (#370) has staled?
