### ISSUE TITLE
Hacktoberfest 2019: LadyBug

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#369]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : LadyBug

Q. Where have you seen the announcement (URL)?  
A. : https://discourse.ladybug.tools/t/celebrate-hacktoberfest-2019-with-ladybug-tools/7314

Q. What kind of swag (clothing, stickers, ...)?  
A. : stickers

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by mpaarating** [comment]
I can work on this

**Comment by aayushbisen** [comment]
@aslafy-z We can close this issue! 😁
