### ISSUE TITLE
Hacktoberfest 2019: SAP

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#371]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : SAP

Q. Where have you seen the announcement (URL)?  
A. : https://blogs.sap.com/2019/10/04/lets-code-share-and-learn.-calling-abapers-to-next-edition-of-hacktoberfest/

Q. What kind of swag (clothing, stickers, ...)?  
A. : accessories

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by CoderJolly** [comment]
What is this issue about, can @aslafy-z pls explain it ?
