### ISSUE TITLE
Hacktoberfest 2019: Python Discord

### ISSUE THREAD

**Issue by Akashd7** [swapagarwal/swag-for-dev#373]
## Wild swag opportunity appeared!

- [✔ ] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Python Discord

Q. Where have you seen the announcement (URL)?  
A. : https://www.reddit.com/r/Python/comments/dbj0vh/python_discord_hacktoberfest_2019/

Q. What kind of swag (clothing, stickers, ...)?  
A. : Tshirt or 1 Year JetBrains License

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : Yes

- [✔ ] I've checked that the promotion is legit.
- [✔ ]I've checked that it's still available to the public.

**Comment by vikaspotluri123** [comment]
Closing as per @swapagarwal's comment in the corresponding PR
