### ISSUE TITLE
Difficulty label gets distorted with long titles 

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#393]
## Issue regarding the website

- [x] I've checked that this isn't a duplicate issue.

Difficulty indicator gets distorted on mobile with long titles :

![Screenshot_20191006_014007_com android chrome](https://user-images.githubusercontent.com/8191198/66262144-51ef4480-e7db-11e9-8b7a-6d0e5689b9ba.jpg)

Chime on Android

**Comment by mpaarating** [comment]
I'll start working on this.

**Comment by aslafy-z** [comment]
Fixed by #401
