### ISSUE TITLE
Don't test dataset if it haven't changed

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#405]
- [x] I've checked that this isn't a duplicate issue.

It might be good idea to avoid technical PRs being blocked by broken swag ones that need to be rebased.

Get a list of the files that changed in current branch since the base branch split:

```sh
git diff --name-only master...
# since 2.22, or
git diff --name-only $(git merge-base master HEAD)
```

**Comment by vikaspotluri123** [comment]
I thought part of the reason for testing them was to make sure they're still active?
