### ISSUE TITLE
Hacktoberfest 2019: Aqua

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#406]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Aqua

Q. Where have you seen the announcement (URL)?  
A. : https://blog.aquasec.com/aqua-open-source-security-hacktoberfest

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing, stickers, books

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by maybebored** [comment]
Working on this :)
