### ISSUE TITLE
Home Page Redesign

### ISSUE THREAD

**Issue by anhek** [swapagarwal/swag-for-dev#407]
- [X] I've checked that this isn't a duplicate issue.

Hello,
I'm doing the #hacktoberfest and I'd like to propose a visual redesign for the home page.

In my opinion the website right now is a bit bland, I'd like to add more swag to the landing page, to give it a fresh and clean style. I'm planning to leave the html structure untouched as much as possible. 

I'll fork the repo and work on the redesign, and it's up to you whether or not you merge my proposition 😃

**Comment by swapagarwal** [comment]
Hi @anhek! It'll be great if you could post a sketch / mock of the redesign here to get feedback from the community. 😇

**Comment by anhek** [comment]
Alright I'll do that :)

**Comment by aslafy-z** [comment]
Related: https://github.com/swapagarwal/swag-for-dev/issues/92 https://github.com/swapagarwal/swag-for-dev/issues/108

**Comment by anhek** [comment]
Hello :)

Here's the sketch as previously asked.

 I restructured the layout to give it a better readability. My first intention was to create a logo but I've found out someone already worked on this part, so I imported the chosen one (from the poll that was made back in December). 

I aimed to create a visual style that is playful and colorful (e.g for the background tags colors) as getting swag is something joyful 😄

I used a mix of Source Sans Pro and Source Code Pro for the fonts. I emphasized the newsletter block to make it more visible.

On the item structure, I put forward the image block before the title because I think the image catch the eye first rather than the title.

I think there's some work to do on the footer but I'll keep that for later.

Now it's feedback time ! I hope you guys like it ^^

![Desktop HD@1x](https://user-images.githubusercontent.com/1397483/66572254-f02f3180-eb70-11e9-9d83-25e526d038ab.png)

**Comment by swapagarwal** [comment]
This looks great! I've posted it in the Telegram group for feedback from the community. 😇

**Comment by Yash-Garg** [comment]
Looks amazing ! Good work 🔥

**Comment by aslafy-z** [comment]
#351

**Comment by swapagarwal** [comment]
Some feedback:
- Oh gosh the ui looks cleaner
- This is lit 🔥🔥
- Looks 🔥
- Cool
@anhek Let's go ahead! 💯

**Comment by anhek** [comment]
Thank you for the feedbacks 🤓 
My laptop just died today (need to bring it Wednesday for reparation), I’ll restart the integration work on another laptop and I’ll stay in touch with you guys 👌

**Comment by aslafy-z** [comment]
Dark mode draft https://github.com/swapagarwal/swag-for-dev/pull/214

**Comment by aslafy-z** [comment]
Closed with #443 :100:
