### ISSUE TITLE
Hacktoberfest 2019: CodingBlocks

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#411]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : CodingBlocks

Q. Where have you seen the announcement (URL)?  
A. : https://blog.codingblocks.com/2019/cb-hacktoberfest-2019/

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing, bag

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by driver-by** [comment]
I'd like to contribute. Will add soon.
