### ISSUE TITLE
Issue with swag image links style

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#412]
## Issue regarding the website

- [x] I've checked that this isn't a duplicate issue.

Following #336, the UI behavior changed. swag images are now underlined as other links when not hovered. When they are, hovered, the line goes away for both the image link and the text link (`Check it out`). Also, it reacts to the card hovering, not the links. 

![2019-10-09 19_57_52-Window](https://user-images.githubusercontent.com/8191198/66507296-3df35d80-eacf-11e9-8643-6b899939090a.png)
![2019-10-09 19_58_11-Window](https://user-images.githubusercontent.com/8191198/66507297-3df35d80-eacf-11e9-9a82-f9c90f58dd53.png)
![2019-10-09 19_58_37-Window](https://user-images.githubusercontent.com/8191198/66507298-3df35d80-eacf-11e9-8626-0b496715b8d9.png)

**Comment by AlexandruBuhai** [comment]
I would like to work on this. Is the intended behavior for the image to not to have an underline?

**Comment by sanjpareek** [comment]
Hi, I am a beginner at OS. I am interested in fixing this bug. I tried running this project locally but am encountering errors when running gulp command. 

Node: v6.5.0
npm: 3.10.3


/Users/sanjanapareek/personal/swag-for-dev/node_modules/del/index.js:55
module.exports = async (patterns, {force, dryRun, cwd = process.cwd(), ...options} = {}) => {
                                                                       ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sanjanapareek/personal/swag-for-dev/gulpfile.js:1:75)
    at Module._compile (module.js:556:32)


Is there anything wrong with the node/npm versions?

**Comment by vikaspotluri123** [comment]
@sanjpareek yep, node v6 was deprecated in April. You're best off upgrading to v10.x or v8.x
