### ISSUE TITLE
Hacktoberfest 2019: Globo.com

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#418]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Globo.com

Q. Where have you seen the announcement (URL)?  
A. : https://opensource.globo.com/hacktoberfest/

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by AlexandruBuhai** [comment]
I would like to contribute

**Comment by hugovk** [comment]
> Os 200 primeiros inscritos ganharão uma
camiseta exclusiva a ser entregue dentro
do território brasileiro.

Google Translate:

> The first 200 registrants will win an
exclusive t-shirt to be delivered within
the Brazilian territory.

**Comment by AlexandruBuhai** [comment]
@hugovk is right, seems to just be in Brazil. Should I add it with the text `Delivery only in Brazil` or not since the swag must be able to be shipped worldwide?
