### ISSUE TITLE
Postman swags

### ISSUE THREAD

**Issue by Souvik-py** [swapagarwal/swag-for-dev#424]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Postman

Q. Where have you seen the announcement (URL)?  
A. : https://www.surveymonkey.com/r/8SKGPCG

Q. What kind of swag (clothing, stickers, ...)?  
A. : T-shirts, socks, mug, stickers

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : NA

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by Souvik-py** [comment]
I would like to contribute a PR for this issue.

**Comment by vikaspotluri123** [comment]
It looks like the swag is not guaranteed, can you confirm?

**Comment by Souvik-py** [comment]
I think they will choose random winners for the prizes..

**Comment by Souvik-py** [comment]
okey then, I'm closing this issue. Thanks for your time..
