### ISSUE TITLE
Find a cool domain name

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/swag-for-dev#43]
We can find a cool domain (maybe something like `swag.*`), and redirect it to this page. e.g. `swag.online`, `swag.dev`, etc.

**Comment by zac-garby** [comment]
`swag.info`?

**Comment by swapagarwal** [comment]
Not available: https://www.namecheap.com/domains/registration/results.aspx?domain=swag.info

**Comment by TooPlain** [comment]
We can go for something like maybe swag.io? I doubt it would be available unfortunately. I’ll see what I can find. Would you guys be open to any type tld as long as there is swag in it?

**Comment by TooPlain** [comment]
Devswag doesn’t sound bad, anyone else like that domain? Let’s do a vote on it.

**Comment by swapagarwal** [comment]
@mgaruccio +1
Let's wait for a few more members to chime in! 😇

**Comment by remram44** [comment]
I really must recommend against `.io`, not only because of [the political controversy](https://gigaom.com/2014/06/30/the-dark-side-of-io-how-the-u-k-is-making-web-domain-profits-from-a-shady-cold-war-land-deal/) around it, but also because it has a history of breakage.

`.org`, `.info` might be a better choice (`devswag.info`?)

**Comment by zac-garby** [comment]
>  and redirect it to this page

It might be better to make an actual website for it, even if it's just a GitHub pages thing.

**Comment by swapagarwal** [comment]
@remram44 Now that I think about it, I definitely remember hearing about multiple .io outages.
@zac-garby Currently, it's this: https://swapagarwal.github.io/swag-for-dev/ Feel free to improve on it! 🎨

**Comment by zac-garby** [comment]
@swapagarwal Oh right, I didn't realise it was already set up lol

**Comment by mgaruccio** [comment]
Personally, I'm a fan of devswag.tech if the plan is to stay away from .io

**Comment by MartinHennrich** [comment]
swag.fans  🤔

**Comment by MartinHennrich** [comment]
swag.supplies  🤔

**Comment by notonewith** [comment]
I would say devswag.tech would be awesome!

**Comment by TooPlain** [comment]
So look at a few of the suggestions. I would say we should find more domains closer to our subject/objective which is tech related swag.

**Comment by mgaruccio** [comment]
It seems like the consensus is for "devswag" with some debate about the TLD.  Not sure who will actually be registering but I did some quick pricing on namecheap and  devswag.io is about $32 while devswag.tech is about $18.  Not sure if that matters but figured I'd include it.

**Comment by antonio6643** [comment]
What about devswag.zone ?

**Comment by bharathvaj1995** [comment]
how about dev.swag ?

**Comment by wad3g** [comment]
A little pricey, but http://devsw.ag would be my pick. 

If there later is out of your price range I'd go with http://👨‍💻👕.ws

**Comment by TooPlain** [comment]
I kind of like what @wad3g suggested, what’s the price on it?

**Comment by wad3g** [comment]
@TooPlain `.ag` is around ~$85-$95.

**Comment by swapagarwal** [comment]
Going with the flow, I'm also sold on `devswag.*`. 💯
The only thing that remains is to decide on the TLD (`info`, `io`, `tech`, etc.) as @mgaruccio  mentioned!

I've set up a [Patreon page](https://www.patreon.com/swapnilagarwal) to gather support from the community to go for the pricier TLDs.
Feel free to share what extra features would you like to see on the website. Cheers! 🎉

**Comment by swapagarwal** [comment]
@zac-garby @TooPlain @mgaruccio @remram44 @austriker27 @MartinHennrich @antonio6643 @bharathvaj1995 @wad3g How about `devswag.xyz`?

**Comment by zac-garby** [comment]
Yeah Ilike that one (devswag.xyz)

**Comment by MartinHennrich** [comment]
`devswag.xyz` sounds great 😎

**Comment by swapagarwal** [comment]
I had a discussion with a couple of folks regarding the TLD.
Going with the popular opinion (devswag.io), we're [live on Product Hunt right now](https://www.producthunt.com/posts/devswag-2)!!
(Just in case, we also have devswag.xyz pointing to devswag.io)
