### ISSUE TITLE
Operation Code marked 'EASY'

### ISSUE THREAD

**Issue by KillMonger1** [swapagarwal/swag-for-dev#435]
## Issue with an existing swag opportunity

- [x] I've checked that this isn't a duplicate issue.

Q. Which opportunity?  
A. : Operation Code

The Operation Code Swag opportunity is marked as easy. I feel that resolving 3 issues or merging 2 PR's aren't less than 'medium' difficulty for any newbie.

**Comment by wuworkshop** [comment]
Just submitted a quick PR for this one.
