### ISSUE TITLE
Hacktoberfest 2019: Flutterwave

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#441]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Flutterwave

Q. Where have you seen the announcement (URL)?  
A. : https://twitter.com/Ace_KYD/status/1183738026511519745

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by kyle-copeland** [comment]
I'd like to grab this one as well
