### ISSUE TITLE
Hacktoberfest 2019: Les tilleuls

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#442]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Les tilleuls

Q. Where have you seen the announcement (URL)?  
A. : https://les-tilleuls.coop/fr/blog/article/celebrate-hacktoberfest-with-api-platform

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by kyle-copeland** [comment]
I'd like to contribute and add this
