### ISSUE TITLE
Fix image generation 

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#447]
This upgrade changed the way images are generated in some way. The generated images aren't the same. We might need to adjust some settings.

_Originally posted by @aslafy-z in https://github.com/swapagarwal/swag-for-dev/pull/440#issuecomment-543343226_

**Comment by ajitsinghkaler** [comment]
@aslafy-z Can I work on this.

**Comment by aslafy-z** [comment]
Nice, I assigned it to you. Have a look to the linked description :arrow_up:

**Comment by ajitsinghkaler** [comment]
I need to know the change we need to make to the images. Can you please attach some screenshots. I downgraded the gulp-responsive version but the images were still the same.

**Comment by ajitsinghkaler** [comment]
@aslafy-z This is not an image generation issue most of it occurs because most images are not 300*300 so for that either we can change the CSS or reduce the size of images to width:300 px. I'm making both changes please review and tell which is more appropriate.

**Comment by ajitsinghkaler** [comment]
What you think is an appropriate solution I can create a pull request for that.
