### ISSUE TITLE
mullvad swags

### ISSUE THREAD

**Issue by vyaspranjal33** [swapagarwal/swag-for-dev#45]
- [x] I've checked that there isn't a duplicate issue.

Is it regarding the current promotions or something new?  
Uncomment the corresponding section below.

mullvad isn't responding nor shipped swags @swapagarwal what to do

**Comment by vyaspranjal33** [comment]
ok may be 6 month or more ?
@shivdhwaj

**Comment by shivdhwaj** [comment]
@vyaspranjal33 I will check the duration exactly but approx 2-3 months it took to deliver to Mumbai.

**Comment by vyaspranjal33** [comment]
so i can expect 4 month for gujarat right ? @shivdhwaj

**Comment by Asjas** [comment]
Took about 3 to 4 months for mine to arrive in South Africa. But I did receive it.

**Comment by shivdhwaj** [comment]
@vyaspranjal33 Lets see when it reaches you

**Comment by vyaspranjal33** [comment]
thanks for information @shivdhwaj

**Comment by shivdhwaj** [comment]
@vyaspranjal33  Welcome :)

**Comment by ssiddhantsharma** [comment]
@vyaspranjal33 @shivdhwaj I got it within 2 weeks, the guys there are awesome. Want me to post some pics?

**Comment by swapagarwal** [comment]
@ssiddhantsharma Yeah sure! Why not? 😉

**Comment by vyaspranjal33** [comment]
@swapagarwal Thank you so much for creating this Repo

**Comment by swapagarwal** [comment]
@vyaspranjal33 Cheers! ❤️
