### ISSUE TITLE
Sense/Net difficulty set to 'easy'

### ISSUE THREAD

**Issue by KiranAkadas** [swapagarwal/swag-for-dev#453]
## Issue with an existing swag opportunity

- [x] I've checked that this isn't a duplicate issue.

Q. Which opportunity?  
A. : Sense/Net 

I feel that making a pull request to a repo isn't that easy for a beginner and that the swag opportunity needs to be marked at a 'medium' level

**Comment by swapagarwal** [comment]
You can send a documentation PR as well and from the blog, it need not be merged to count.
