### ISSUE TITLE
Remove HacktoberFest related Swags

### ISSUE THREAD

**Issue by KillMonger1** [swapagarwal/swag-for-dev#468]
## Issue with an existing swag opportunity

- [x] I've checked that this isn't a duplicate issue.

Q. Which opportunity?  
A. : Many 

There are many Hacktoberfest related Swag opportunities which seem to have expired as HacktoberFest has ended. Why not remove all those.

**Comment by swapagarwal** [comment]
Yes, we need to add the "expired" tag to all such items.

**Comment by manan2501** [comment]
check PR #473

**Comment by KiranAkadas** [comment]
Hello I feel that the CI error is occuring after the #457 PR
