### ISSUE TITLE
Blockstack - Can't be evil stickers 

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#476]
#107 Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Blockstack

Q. Where have you seen the announcement (URL)?  
A. : https://blockstack.myshopify.com/collections/frontpage/products/dont-be-evil-stickers

(Up to 5 free stickers)

Q. What kind of swag (clothing, stickers, ...)?  
A. : stickers

Q. Have you received swag from this?  
A. : no

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by crashoverloaded** [comment]
I've received it and it does ship worldwide !!

**Comment by fzs1994** [comment]
https://github.com/swapagarwal/swag-for-dev/pull/335#issuecomment-537033676

**Comment by vikaspotluri123** [comment]
@fzs1994 these stickers are not advertised specifically for a community ~ your PR linked to a form which says

> Stickers for events and community

We don't want to advertise community offerings like that since it's not in the spirit of devSwage 😄

**Comment by cybrefox** [comment]
This has been open for over 8 months now
