### ISSUE TITLE
Blockstack Zero to Dapp t-shirt

### ISSUE THREAD

**Issue by C0D2D** [swapagarwal/swag-for-dev#491]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Blockstack

Q. Where have you seen the announcement (URL)?  
A. : https://community.blockstack.org/z2d-shirt

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing

Q. Have you received swag from this?  
A. : Yes

Q. How long did it take?  
A. : Took around a week or so

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by GuyKh** [comment]
I couldn't find anywhere a mention of the shirt for the link you wrote

**Comment by C0D2D** [comment]
I used the wrong link, the link mentioning it is https://community.blockstack.org/z2d-shirt
