### ISSUE TITLE
Add Product Hunt

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/swag-for-dev#5]
Suggested by Amrith Shanbhag (@shnbhg) from PH team:

> you can even add Product Hunt to the list – Devs have to host a Product Hunt meetup or hackathon for PH and we ship swag to everyone who attends 😉

Take images from https://blog.producthunt.com/host-a-product-hunt-meetups-in-your-city-6db988197144

**Comment by KerstinMaur** [comment]
By the way, did you have to pay @producthunt to [list](https://www.producthunt.com/posts/swag-for-dev) you?

**Comment by HammyHavoc** [comment]
@KerstinMaur Listing things on Product Hunt is free. I can't speak for the devs, but I've submitted plenty of products to it, for free, including one recently.

**Comment by KerstinMaur** [comment]
How did you do that? I just come to the attached screen. 🤔

![ph](https://user-images.githubusercontent.com/32022034/36618232-a7441b70-18ea-11e8-8861-7a4afaa2e4b1.PNG)

**Comment by vintagesucks** [comment]
@KerstinMaur Posting your product on Product Hunt (https://www.producthunt.com/) is free, see the requirements here: https://help.producthunt.com/posting/how-can-i-get-access-to-postcomment

The pricing table on your screenshot is for _**Ship**_ subscriptions (https://www.producthunt.com/ship).

---

![gfdgdfg](https://user-images.githubusercontent.com/13335308/36619684-f9b084f2-18ef-11e8-9332-398f4b4b0995.png)

**Comment by KerstinMaur** [comment]
Thanks for the instructions, @vintagesucks. 😎

**Comment by EvangelinePetersen** [comment]
@shnbhg & @swapagarwal, where can I find a list of @producthunt meetups?
[https://www.producthunt.com/meetups](https://www.producthunt.com/meetups) seems to be dead? 🤔

**Comment by jsmayo** [comment]
Hmm, try filtering this list: https://www.producthunt.com/events

**Comment by RalphPfeiffer** [comment]
Why is this issue closed?
