### ISSUE TITLE
Extend Contributing.MD

### ISSUE THREAD

**Issue by sampoder** [swapagarwal/swag-for-dev#512]
- [x] I've checked that this isn't a duplicate issue.

What do you think of adding a simple section on how to add a swag opportunity to the Contributing file? I could do it and it would be pretty small but helpful for people not experienced with the technologies used as well as the project.

**Comment by aslafy-z** [comment]
Oops, it misses a link on the readme. Can you add that one? Thank you @sampoder 🔥

**Comment by sampoder** [comment]
Ok, will do!

**Comment by sampoder** [comment]
@aslafy-z done!
