### ISSUE TITLE
Issue with Pagerduty Swag

### ISSUE THREAD

**Issue by sampoder** [swapagarwal/swag-for-dev#515]
## Issue with an existing swag opportunity

- [x] I've checked that this isn't a duplicate issue.

Q. Which opportunity?  
A. : Pagerduty

The website link is no longer valid: https://community.pagerduty.com/t/free-pagerduty-stickers-are-back-and-here-to-stay/4520

**Comment by aslafy-z** [comment]
Well spotted. Can you open a PR to set this opportunity as expired?

**Comment by sampoder** [comment]
Sure. I'll open one!

-- 
This email and any attachments are confidential and may also be privileged. 
If you have received this message in error, please (a) notify the sender 
immediately, (b) destroy this email and any attachments, and (c) do not 
use, copy, store and/or disclose to any person this email and any 
attachments. The sender gives no representation or guarantee with respect 
to the integrity of any emails or attached files and the recipient should 
check the integrity of and scan this email and any attached files for 
viruses prior to opening.
