### ISSUE TITLE
Design the website

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/swag-for-dev#52]
We shall be hosting this on either `devswag.xyz` or `devswag.io` domain.

(Moving this from #43 to its separate thread)
What extra features would you like to see on the website?

One example I can think of is the ability to filter swag opportunities by the level of difficulty. Feel free to share more!

Also, it'd be great if someone volunteers to get the initial design of the website in place. Cheers!

**Comment by zac-garby** [comment]
I’d like to design the website :)

**Comment by cozyplanes** [comment]
`io` seems easier to remember

**Comment by swapagarwal** [comment]
@zac-garby Awesome! How about you take the lead on this? Let's keep it minimalistic and get it out before Hacktoberfest. 😇

**Comment by zac-garby** [comment]
Cool! I'll start it a bit later today when I get home. Do we want it to automatically fetch the swag opportunities from the repo?

**Comment by swapagarwal** [comment]
@zac-garby I can export the list in json format if that helps?
Something like:
```
{
    "name": "Alexa",
    "difficulty": "hard",
    "description": "Publish a skill, get a hoodie (varies by country) and an Echo Spot (if 1,000 unique customers use your skill in its first 30 days of publication)!",
    "reference": "https://developer.amazon.com/alexa-skills-kit/alexa-developer-skill-promotion",
    "image": "https://images-na.ssl-images-amazon.com/images/G/01/mobile-apps/dex/alexa/alexa-skills-kit/ASM0761-Dev-LP-Goodiepage-UK-March._CB501585903_.png"
}
```

**Comment by zac-garby** [comment]
@swapagarwal Yeah, that would be very useful - thanks

**Comment by swapagarwal** [comment]
Your wish, is my command: https://github.com/swapagarwal/swag-for-dev/blob/master/data.json
The website can load data from https://raw.githubusercontent.com/swapagarwal/swag-for-dev/master/data.json

**Comment by plibither8** [comment]
Hey @swapagarwal @zac-garby, if possible, I'd like to help too :)

**Comment by swapagarwal** [comment]
@plibither8 Sure! It'd be great if you can sketch up a quick mock and share the design that's on your mind.

**Comment by plibither8** [comment]
Sure, I'll start work late at night. I'll try to share it by tonight (IST) itself

**Comment by zac-garby** [comment]
@swapagarwal I've made a quick design of what the site might look like. I was thinking for the colour scheme we could keep it really simple, maybe just black and white.

<img width="1123" alt="screenshot 2018-09-20 at 17 14 08" src="https://user-images.githubusercontent.com/19708658/45832011-ae7ae100-bcf8-11e8-8f59-e5e9a495c552.png">

Let me know what you think :)

**Comment by plibither8** [comment]
@zac-garby Are you going to use PaperCSS?

**Comment by swapagarwal** [comment]
@zac-garby Black and white looks good for v1.
👍 for the minimalistic design.
Let's wait for @plibither8 to pitch in, and then we can start!

**Comment by swapagarwal** [comment]
And @plibither8 is here! 🎉

**Comment by zac-garby** [comment]
@plibither8 Never heard of it, but just looked it up. Probably not - it just looks like that because of the program I used to design it. I probably should've been more clear

**Comment by zac-garby** [comment]
I'm wondering whether to use some framework like Vue or React or something, or just plain HTML, JS, CSS. On the one hand, it will be a lot easier using a framework, but the page will take longer to load. What do you think?

**Comment by plibither8** [comment]
@swapagarwal My idea was more or less what @zac-garby has suggested: minimalistic and clean. I would probably lose out the borders, make the name more prominent and above the image, and add a separate line for the link to quickly access the details and reference. @zac-garby I like your way to mark the difficulty - with the colours.

**Comment by zac-garby** [comment]
@plibither8 Definitely, that's a good point about a more prominent name. Which borders would you get rid of?

**Comment by swapagarwal** [comment]
I don't suspect the page will take a long time to load (irrespective of framework) as there is very limited data as of now! So it essentially boils down to your comfort levels: use whatever you're comfortable in! (unless, of course, you want to use this as an opportunity to try out a new framework! 😉)

**Comment by plibither8** [comment]
@zac-garby I don't think it will be that much of a problem to use vanilla JS, since it's mostly a static website and our key focus is minimalism. Fetching the data from the JSON file and mapping over its elements to create the HTML divs for each swag item should be fairly simple.

**Comment by plibither8** [comment]
@zac-garby I was referring to the borders around the entire swag item

**Comment by zac-garby** [comment]
I've done a little bit of Vue before, and I reckon that might be a good option. The main thing I'm thinking of here is the sorting/filtering when the options are changed, which is a perfect use of Vue. It probably would be slightly easier to just do plain JS though, because it saves having to set up a whole build system and all that stuff.

**Comment by swapagarwal** [comment]
@zac-garby I run a local Vue community, so I can help in setting up the build process.
@plibither8 Vanilla / Vue?

**Comment by plibither8** [comment]
Personally, I am more comfortable working with vanilla, but I have done one project using Vue, so its not alien to me.

**Comment by zac-garby** [comment]
Okay, I say we should use vanilla just because it's a lot simpler

**Comment by swapagarwal** [comment]
Great! How do you want to collaborate on this?

**Comment by zac-garby** [comment]
<img width="743" alt="screenshot 2018-09-20 at 17 45 24" src="https://user-images.githubusercontent.com/19708658/45833620-fac82000-bcfc-11e8-85d4-d074f5da9704.png">

Here's an updated design with the changes you suggested.

**Comment by zac-garby** [comment]
I'm not really sure, I don't do a huge amount of projects with other people. How does it usually work?

**Comment by plibither8** [comment]
@zac-garby it looks great

**Comment by zac-garby** [comment]
@plibither8 Thanks :) Oh, and any idea of what we should write under the title?

**Comment by swapagarwal** [comment]
We usually divide into short tasks and then assign amongst ourselves.

**Comment by plibither8** [comment]
@swapagarwal Maybe create a new branch (something akin to gh-pages) where we can start work on the website. Later you can merge the branch to master and deploy using (I recommend) Netlify

**Comment by swapagarwal** [comment]
@zac-garby I'll work on the text. You can use `Lorem Ipsum` for now.

**Comment by swapagarwal** [comment]
Netlify is ❤️

**Comment by plibither8** [comment]
> @plibither8 Thanks :) Oh, and any idea of what we should write under the title?

How about the type of swag we receive from them. Eg: Stickers, T-Shirts

**Comment by zac-garby** [comment]
Netlify looks awesome!

**Comment by swapagarwal** [comment]
I've added you two as collaborators: https://github.com/swapagarwal/swag-for-dev/invitations
You can work on the `website` branch (please don't touch the `master` branch), which I'll hook up with netlify at https://peaceful-chandrasekhar-efde8e.netlify.com. Data can be pulled from https://peaceful-chandrasekhar-efde8e.netlify.com/data.json

**Comment by zac-garby** [comment]
Sounds good. How are we going to divide the tasks up?

**Comment by swapagarwal** [comment]
@plibither8 Any suggestions?

**Comment by plibither8** [comment]
![group 3](https://user-images.githubusercontent.com/31861755/45834406-aa64b880-bd24-11e8-9cea-3e16b98227e9.jpg)
This is the sort of mockup I was thinking of.

**Comment by swapagarwal** [comment]
I see the following tasks:
1. CSS (layout) of a card
1. Remaining CSS of the website
1. Fetch data dynamically
1. Apply filters / sorting logic

**Comment by zac-garby** [comment]
I like it :) Not too keen on the box shadows around the images though

**Comment by zac-garby** [comment]
Yeah that works. I'd like to do 3 and 4 if possible, they sound fun

**Comment by swapagarwal** [comment]
@plibither8 Are you comfortable with CSS?

**Comment by plibither8** [comment]
Sure! I have a few suggestions if it's fine.
I am more comfortable with using Pug and Stylus for HTML and CSS respectively, for which I usually use Gulp as the task runner to compile the files. For JS, I write in ES6 and transpile the code to browser standards using Babel. Is that okay?

**Comment by zac-garby** [comment]
Yeah, that's a good idea

**Comment by plibither8** [comment]
Great. I'll set up the gulpfile and npm dependancies then.

**Comment by zac-garby** [comment]
Cool, I'll get started on the data fetching

**Comment by remram44** [comment]
Isn't it easier to have CI in this repo build a static website, rather than have a separate project that loads JSON from here and dynamically render for the user client-side? This seems unnecessarily inefficient.

Also :-1: on `.io` ([again](https://github.com/swapagarwal/swag-for-dev/issues/43#issuecomment-385735942)).

**Comment by plibither8** [comment]
@swapagarwal Please configure Netlify to deploy from the `site/dist` folder of the

**Comment by plibither8** [comment]
@zac-garby Take a look at the directory structure, I'll be following that, is it okay?

**Comment by zac-garby** [comment]
@plibither8 Looks good to me

**Comment by swapagarwal** [comment]
@plibither8 `site/dist` configured!

**Comment by zac-garby** [comment]
@plibither8 The website doesn't seem to be able to load `index.js`: "Loading failed for the <script> with source “file:///assets/js/index.js”. Am I doing something wrong? (I have the gulp task running and I'm viewing dist/index.html on my browser)

**Comment by plibither8** [comment]
Since the file names have absolute paths, simply loading the html file on the browser won't work, you'll require a web server who's root is the `dist` directory. I'll  update the gulpfile to include code that starts a webserver.

**Comment by plibither8** [comment]
@zac-garby Pull the latest commit and restart gulp. It should open a live web server now

**Comment by zac-garby** [comment]
Ah okay, thanks

**Comment by zac-garby** [comment]
It's now getting a `require is not defined` error. Looks like gulp isn't joining all the script files into one (which it should do?)

**Comment by plibither8** [comment]
Sorry for the late reply, you should probably run `npm install` again, maybe it will work(?). It won't concat the script files as of now, do you want it to?

**Comment by zac-garby** [comment]
`npm install` didn't fix it. It would probably be useful to concat the script files - I could do it but I didn't want to mess up anything lol

**Comment by plibither8** [comment]
Oh darn, could you maybe send a screenshot of the error you're facing?

**Comment by zac-garby** [comment]
<img width="561" alt="screenshot 2018-09-20 at 20 16 16" src="https://user-images.githubusercontent.com/19708658/45841557-1689f100-bd12-11e8-85f2-fcba7f2d71e6.png">

It might be something to do with my code -- I don't use ES6 syntax a huge amount so I may have done something wrong. Here's `fetch.js`:

```js
const DATA_URL = "https://peaceful-chandrasekhar-efde8e.netlify.com/data.json"

// Fetches the JSON swag list. Once it has got the data, it will call the given callback function
// with one argument: a list of objects.
export function fetchSwag(callback) {
    var req = new XMLHttpRequest()

    req.onreadystatechange = function() {
        if (this.readyState == 4 && this.status == 200) {
            var responseText = req.responseText
            var swag = JSON.parse(responseText)
            callback(swag)
        }
    }

    req.open("GET", DATA_URL, true)
    req.send()
}
```

And here's `index.js`:

```js
import { fetchSwag } from "./fetch"

fetchSwag(console.log)
```

**Comment by zac-garby** [comment]
Now it's all in the same file, it works fine

**Comment by plibither8** [comment]
Thank you!

Also, I've push the latest commit which I think will fix your problem (I think it was due to incorrect configuration of babel presets :| )

**Comment by zac-garby** [comment]
The new commit just introduces a new error: `exports is not defined`... Very weird. But don't worry, I'll just put it all into one file.

**Comment by plibither8** [comment]
😞 Alright

**Comment by zac-garby** [comment]
@swapagarwal Is it possible to add a `Access-Control-Allow-Origin: *` to the JSON data? Otherwise, it's impossible to get the data through an `XMLHttpRequest` unless my request is being sent from the production server, making it really hard to test.

**Comment by plibither8** [comment]
If you're using Chrome, download [this](https://chrome.google.com/webstore/detail/moesif-origin-cors-change/digfbfaphojjndkpccljibejjbppifbc) extension, it's <3

**Comment by zac-garby** [comment]
Ah, that's very useful, thanks :)

**Comment by plibither8** [comment]
We should do something about the image sizes

**Comment by zac-garby** [comment]
I was thinking the same thing. Not sure what to do though, it would be a shame to crop them

**Comment by plibither8** [comment]
True. I'm working on a CSS solution to it. Nevertheless, we should certainly do something about the devRant image. It's too out of proportion

**Comment by zac-garby** [comment]
Yeah. We could just manually crop that one and in the future not allow pull requests where the image is too long

**Comment by swapagarwal** [comment]
@plibither8 The initial design looks good!
@zac-garby Instead of doing an HTTP call, you can just import the file locally as well.

**Comment by plibither8** [comment]
@swapagarwal anything to add/subtract/modify?

**Comment by swapagarwal** [comment]
The dropdowns can be more stylized.
Let's brighten up the difficulty colors.
Regarding images, let's try out center crop for larger images (devrant) and center align for smaller images (npm).

**Comment by plibither8** [comment]
Sure. Also, I think a link to the github repo should be added too, add the bottom. Any other footer text?

**Comment by zac-garby** [comment]
For the dropdowns, it might be nice to make them blend in with the text around them by styling them to look like the selected option with a thick underline, but no box or anything, if you know what I mean?

**Comment by plibither8** [comment]
Check the latest pushes

**Comment by zac-garby** [comment]
Nice! One thing: the `<select>` elements don't really fit in with the rest of the site.

![screenshot 2018-09-21 at 15 55 43](https://user-images.githubusercontent.com/19708658/45888786-d3ce2480-bdb6-11e8-97b7-488bc1b3a5ce.png)

**Comment by plibither8** [comment]
That looks odd, which browser are you using?

**Comment by plibither8** [comment]
That looks odd, which browser are you using?

**Comment by zac-garby** [comment]
Firefox

**Comment by swapagarwal** [comment]
Same with me.

**Comment by aslafy-z** [comment]
Glad you're working on this, it looks great! You need to add a `-moz-appearance: none` to ensure the select styling works on firefox. You can also use an autoprefixer to do that on compile-time (like https://gist.github.com/ayapi/26d299e4a61d9ac66036).

**Comment by plibither8** [comment]
Thanks @aslafy-z! I've pushed the changes in the latest commit, hopefully it looks OK now

**Comment by aslafy-z** [comment]
Nice! I'm personally inconfortable with non-draggable images, I would delete this `-wekkit-user-drag: none` which is also not portable as is.
What do you think ?

**Comment by plibither8** [comment]
Good point, non-draggable images should be implement for logos and icons only. I'll fix this, thanks

**Comment by swapagarwal** [comment]
Let me know if you need any help. 😇

**Comment by swapagarwal** [comment]
Once the image dimensions are sorted, we can merge it as an MVP. Other features (text / colors) can be added iteratively.
By brightening, I meant changing the RGB values of colors. See the easy difficulty color in the first mock and the website:
<img width="240" alt="screenshot 2018-09-27 08 57 29" src="https://user-images.githubusercontent.com/2833845/46121888-8da01780-c233-11e8-8ead-24a84b4363f4.png"><img width="240" alt="screenshot 2018-09-27 08 57 38" src="https://user-images.githubusercontent.com/2833845/46121890-90027180-c233-11e8-8f24-79d04c962d2e.png">

**Comment by plibither8** [comment]
Oh alright, will do that.

**Comment by plibither8** [comment]
@swapagarwal I'll require the description text which will go under the title

**Comment by swapagarwal** [comment]
You can use `A list of opportunities for developers to score some swag 😎` for now.
Were you able to resolve the image size issue? (We only have 1 day left! 😇)

**Comment by plibither8** [comment]
Done! I've implemented a pure-CSS solution that will limit the height of the image to 350px

**Comment by swapagarwal** [comment]
Nice!
The `npm` image looks so small compared to others. The height should be the same for all images to have a cleaner layout, right?

**Comment by swapagarwal** [comment]
Hmm. We can either `stretch` the image to fit or `center-crop` it. Let's try out both and see?

**Comment by plibither8** [comment]
Tried and tested, it doesn't look too good :/ I'll share the screenshots if you want it

Hacktoberfest has started, should I merge this into `master`?

**Comment by swapagarwal** [comment]
Okay, np.
Add the screenshots; I'll try to find a solution.
Can you raise a PR and add zac and me as reviewers?
I'll merge it before tomorrow. 

---- On Sun, 30 Sep 2018 20:57:02 +0530 notifications@github.com wrote ----

Tried and tested, it doesn't look too good :/ I'll share the screenshots if you want it

Hacktoberfest has started, should I merge this into master?

**Comment by plibither8** [comment]
The screenshot:
![image](https://user-images.githubusercontent.com/31861755/46259954-d0951000-c4fd-11e8-8eb6-80a37967e256.png)

**Comment by zac-garby** [comment]
IMHO that looks pretty good. Maybe a little bit of padding under the images would be nice.

**Comment by swapagarwal** [comment]
Thanks to everyone who pitched in to give suggestions and solutions. 😇
Special mention to @zac-garby and @plibither8 for getting this out right on time (Hacktoberfest starts today!)

**Comment by swapagarwal** [comment]
We're [live on Product Hunt right now](https://www.producthunt.com/posts/devswag-2)!!
