### ISSUE TITLE
RedisLabs free t-shirt

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#533]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : RedisLabs

Q. Where have you seen the announcement (URL)?  
A. : https://redislabs.com/try-redis-cloud-essentials-for-a-free-shirt/

Q. What kind of swag (clothing, stickers, ...)?  
A. : t-shirt

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : No, only US and Canada

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by GuyKh** [comment]
I've created an account and a DB, but still no T-Shirt offer :(

**Comment by brittbrouwer** [comment]
I've added Redis Cloud in a PR #537
