### ISSUE TITLE
Expose dataset on website

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#534]
- [x] I've checked that this isn't a duplicate issue.

Expose json dataset on the website, and add a link to it.
Url can look like: `https://devswag.io/data.json`

**Comment by hardik25** [comment]
I would like to take up this issue.

**Comment by sakkshm** [comment]
@aslafy-z You can still access it through https://raw.githubusercontent.com/swapagarwal/swag-for-dev/master/data.json

This is somewhat not the best fix but will work perfectly. Hope it doesn't violates any policy.

**Comment by aslafy-z** [comment]
Yep, we can eventually do a redirect with netlify to this url, it's one of our options. @hardik25 Sure, go on!

**Comment by sakkshm** [comment]
Any updates @hardik25 ?

**Comment by THE-VR7** [comment]
Hello. I am new  and would love to contribute.
I would like to fix this issue, if no one is already on it.
