### ISSUE TITLE
Add BuiltOn.dev swag opportunity

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#538]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : builton.dev

Q. Where have you seen the announcement (URL)?  
A. : https://twitter.com/BuiltOnDev/status/1195746603627405312

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing, stickers

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by Souvik-py** [comment]
Expired opportunity ☹️
