### ISSUE TITLE
Change difficulty of WhatIsMyBrowser

### ISSUE THREAD

**Issue by Mmaarten23** [swapagarwal/swag-for-dev#539]
## Issue with an existing swag opportunity

- [x] I've checked that this isn't a duplicate issue.

Q. Which opportunity?  
A. : WhatIsMyBrowser

The opportunity now needs a paid account which doesnt make it "easy" anymore

**Comment by TorRydberg** [comment]
What should the difficulty be changed to?

**Comment by vikaspotluri123** [comment]
If it requires a paid account, I think it should be marked as expired /cc @aslafy-z

**Comment by aslafy-z** [comment]
Ok to me!

**Comment by aslafy-z** [comment]
Thanks for reporting @Mmaarten23! Now live at https://devswag.io
