### ISSUE TITLE
Add TigerGraph opportunity 

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#541]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : TigerGraph 

Q. Where have you seen the announcement (URL)?  
A. : https://www.tigergraph.com/certification-gsql-101/

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing

Q. Does it ship worldwide?  
A. : to be checked

Image url: https://i.imgur.com/ub8tsdN.png

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
Source: https://github.com/Joonsang1994/free-tshirts-stickers-and-swag-for-developers/pull/36/commits/9e295ccd2417c7767867358e14d86f818cd06297

**Comment by ChrisKatsaras** [comment]
Received mine today. Different than the picture above though

**Comment by GuyKh** [comment]
@ChrisKatsaras - any chance for the answers to the test? :)

**Comment by aslafy-z** [comment]
@ChrisKatsaras Can you do a pic so we can replace the actual? Thanks!

**Comment by ChrisKatsaras** [comment]
@GuyKh I don't have them on me, sorry. @aslafy-z I'll try and upload one soon!

**Comment by rmorabia** [comment]
Is this still available? I'd like to make a PR for Hacktoberfest next week.

**Comment by aslafy-z** [comment]
It looks like this opportunity is now expired. Closing this from now. @rmorabia feel free to implement another entry ☺️
