### ISSUE TITLE
Add Deque opportunity

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#542]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Deque

Q. Where have you seen the announcement (URL)?  
A. : https://twitter.com/dequesystems/status/1182651282869362694

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing

Q. Does it ship worldwide?  
A. : to be checked

image url: https://i.imgur.com/t82DlcW.jpg

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by PoorPocketsMcNewHold** [comment]
The reference tweet seems to have been deleted.

**Comment by cybrefox** [comment]
Why isn't this closed yet?

**Comment by aslafy-z** [comment]
@cybrefox @PoorPocketsMcNewHold You're right. This has already been added to the website.
Thanks for the head up.
