### ISSUE TITLE
Daily Swag (Stickers + T-Shirt)

### ISSUE THREAD

**Issue by saqibameen** [swapagarwal/swag-for-dev#543]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : [Daily.dev](https://daily.dev) 

Q. Where have you seen the announcement (URL)?  
A. : [Twitter](https://twitter.com/dailydotdev/status/1232320892190871552) — I announced it.

Q. What kind of swag (clothing, stickers, ...)?  
A. : Stickers + Clothing

Q. Have you received swag from this?  
A. : I belong to the team and it is totally legit. 

Q. How long did it take?  
A. : May vary based on location

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by vikaspotluri123** [comment]
Hey @saqibameen 👋 if I understand correctly, not everyone is not guaranteed to get swag for following the steps? /cc @aslafy-z I think we decided against opportunities like these?

**Comment by aslafy-z** [comment]
Yep, correct. We cannot accept this kind of contest. Closing this.
