### ISSUE TITLE
Error running gulp command

### ISSUE THREAD

**Issue by stabee** [swapagarwal/swag-for-dev#551]
- [X] I've checked that this isn't a duplicate issue.

After following the guide to run a development environment locally, I get an issue after running `gulp`. I've attached the logs below. I believe it has to do with gulp optimizing google_assistant.jpeg.

<img width="817" alt="Screen Shot 2020-03-06 at 1 34 52 PM" src="https://user-images.githubusercontent.com/23332245/76124388-649abf00-5faf-11ea-84b2-3a51555aa6dd.png">

**Comment by vikaspotluri123** [comment]
Is that the only log that comes out? Usually when something like this happens, it's because one of the images failed to fetch 🤔

**Comment by stabee** [comment]
Hm.. yeah I get "An error occurred while loading that image" message when trying to view hacktoberfest_2019.jpeg from `dist/assets/swag-img` folder. Here's the full log :)

<img width="784" alt="Screen Shot 2020-03-07 at 11 45 43 AM" src="https://user-images.githubusercontent.com/23332245/76151420-d20b2600-6069-11ea-8421-c0309c294671.png">

**Comment by stabee** [comment]
I think it's because the link for the image for hacktoberfest_2019 from `data.json` is not an image anymore. Here's the link related to the image. Just redirects to the homepage:

https://hacktoberfest.digitalocean.com/assets/HF19_social-744d976f227e4aff6866443abcede8c651b309ec9c7c9f7410f5944f8e1299b9.png

**Comment by vikaspotluri123** [comment]
Aah that makes sense. Can you rebase your fork against this repo? If you don't know how, Github has a [great guide](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork)!

**Comment by stabee** [comment]
Hm.. I think my local repo is up to date with the master branch, but still getting the same error after running `gulp` :/

**Comment by vikaspotluri123** [comment]
You're right, I see the issue now... @aslafy-z do you have time to fix the broken image?

**Comment by vikaspotluri123** [comment]
@stabee I've fixed the image. Can you rebase and try again?

**Comment by stabee** [comment]
@vikaspotluri123 I think the hacktoberfest image is working now, thank you! I think there might be a similar issue with the JabRef image (line 237 of `data.json`)

**Comment by vikaspotluri123** [comment]
Third time's the charm 😄

**Comment by stabee** [comment]
Working for me now. Thank you for your help @vikaspotluri123 :)

**Comment by vikaspotluri123** [comment]
Not a problem, great to hear! 🎉
