### ISSUE TITLE
503 error after running gulp

### ISSUE THREAD

**Issue by stabee** [swapagarwal/swag-for-dev#555]
- [x] I've checked that this isn't a duplicate issue.

While running the `gulp` command, I get a 503 error from "https://partners.npmjs.com/weekly/weekly30/socks-1100x.jpg" I think partners.npmjs.com is down, but it's been like that for several days.

I'm interested in contributing to the project, but my build fails when trying to pass the tests on github.

![Screen Shot 2020-03-13 at 11 09 00 AM](https://user-images.githubusercontent.com/23332245/76648190-71716280-651b-11ea-9612-10e547913a48.png)

**Comment by vikaspotluri123** [comment]
hmm, [latest master](https://github.com/swapagarwal/swag-for-dev/blob/617f38aa5829b3af080cf63cca9fc4a56ab9f532/data.json) doesn't reference partners:

**Comment by stabee** [comment]
@vikaspotluri123 you're right, sorry I forgot to sync my fork. Completely my fault.
