### ISSUE TITLE
Getting error when building local with gulp

### ISSUE THREAD

**Issue by TorRydberg** [swapagarwal/swag-for-dev#577]
- [x] I've checked that this isn't a duplicate issue.

I've cloned the repo, installed everything, made sure everything is up to date but when I run gulp I get this error:

![Capture](https://user-images.githubusercontent.com/50177532/80756634-e7984b80-8b00-11ea-94ea-c9f61ff801b0.PNG)

npm update doesn't seem to be doing anything to fix the "caniuse-lite is outdated" issue
Does anyone know how to resolve this?

**Comment by vikaspotluri123** [comment]
Hey @TorRydberg can you sync your repository with ours? You're 96 commits behind, and one of the commits fixes the issue you're having

Here's a Github Guide to [syncing a fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)

**Comment by TorRydberg** [comment]
@vikaspotluri123 Thanks a lot, I'm all up to date now. I had cloned the repo and deleted it, so when I cloned again I thought it would be the latest stuff. I learned something today.
