### ISSUE TITLE
Code Curiosity?

### ISSUE THREAD

**Issue by chiragw15** [swapagarwal/swag-for-dev#6]
https://codecuriosity.org 
Contribute in open source projects and her points. Redeem them to get t-shirts, hoodies etc.

**Comment by swapagarwal** [comment]
This looks really cool! I'd put this up for the community to chime in. 😄

**Comment by Ibrahim-Islam** [comment]
Would not recommend. I have 210 points from over 6 months and they can't give me coupon for that because they are having financial problems

**Comment by BrianLima** [comment]
Look's cool, i'll try that!

**Comment by swapagarwal** [comment]
I also tried it but could not redeem the points.
