### ISSUE TITLE
Remove Expired Deque And Blockstack Opportunities

### ISSUE THREAD

**Issue by monizb** [swapagarwal/swag-for-dev#633]
## Issue with an existing swag opportunity

- [x] I've checked that this isn't a duplicate issue.

Q. Which opportunity?  
A. : Deque And Blockstack

Both the mentioned opportunities above have expired and they are no more giving away those Tees.

**Comment by cybrefox** [comment]
I've never received a tee from neither Blockstack nor Deque. Forms filled in January for blockstack, and in march or april for deque.

**Comment by monizb** [comment]
> I've never received a tee from neither Blockstack nor Deque. Forms filled in January for blockstack, and in march or april for deque.

Actually I got both of them :P
