### ISSUE TITLE
Developer Economics Swags

### ISSUE THREAD

**Issue by pgirikishore** [swapagarwal/swag-for-dev#649]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A.: Developer Economics

Q. Where have you seen the announcement (URL)?  
A. : https://developereconomics.net?member_id=6iRjAsCT&lang=en

Q. What kind of swag (clothing, stickers, ...)?  
A. : All kinds if swags. Visit the site for more info

Q. Have you received swag from this?  
A. : Not Yet 

Q. How long did it take?  
A. : I have not received it yet.

Q. Does it ship worldwide?  
A. : Yes, they do.

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by rmorabia** [comment]
This is a referral link. Request to close.

**Comment by aslafy-z** [comment]
Thanks for your contribution, however we can't accept it, you're right, see #201.
