### ISSUE TITLE
GitHub Actions Hackathon on DEV

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#650]
## Wild swag opportunity appeared!

- [ ] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : DEV

Q. Where have you seen the announcement (URL)?  
A. : https://dev.to/devteam/announcing-the-github-actions-hackathon-on-dev-3ljn

Q. What kind of swag (clothing, stickers, ...)?  
A. : stickers

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by shawnlobo96** [comment]
Please assign this to me

**Comment by GuyKh** [comment]
This is expired

**Comment by shawnlobo96** [comment]
@GuyKh can you close the expired issues or add an expired tag?
