### ISSUE TITLE
Hotjar t-shirt/hoodie

### ISSUE THREAD

**Issue by milanmeu** [swapagarwal/swag-for-dev#661]
## Refer friends to receive a Hotjar t-shirt and hoodie!

Refer 5 friends to receive an official Hotjar t-shirt.
Top 5 referrers every month receive a Hotjar hoodie.

![t-shirt](https://insights.hotjar.com/static/referrals_prize_3.hash-98cad1.png) ![hoodie](https://insights.hotjar.com/static/referrals_prize_2.hash-00c608.png)

Q. Which company offers it?  
A. : Hotjar

Q. Where have you seen the announcement (URL)?  
A. : https://insights.hotjar.com/profile/referrals (You must be logged in)

Q. What kind of swag (clothing, stickers, ...)?  
A. : Clothing: t-shirt and hoodie

Q. Have you received swag from this?  
A. : Yes

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that this isn't a duplicate issue.
- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
Hello @milanmeu. As stated before, we don't accept this kind of entry requiring users to refers others. See https://github.com/swapagarwal/swag-for-dev/issues/201 for details. Thank you for your contribution.
