### ISSUE TITLE
Add Hacktoberfest 2020 entry

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#665]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : DigitalOcean

Q. Where have you seen the announcement (URL)?  
A. : https://hacktoberfest.digitalocean.com/

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by Sudhee-bsp** [comment]
Just added new swag entry @aslafy-z , let's wait for the merging the PR :)
