### ISSUE TITLE
Hacktoberfest - Appwrite

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#669]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Appwrite

Q. Where have you seen the announcement (URL)?  
A. : https://github.com/appwrite/appwrite/issues/541

Q. What kind of swag (clothing, stickers, ...)?  
A. : ?

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by iTechsTR** [comment]
Announcement here

https://medium.com/appwrite-io/celebrate-hacktoberfest-20-with-appwrite-1356337e2159

**Comment by A-Scratchy** [comment]
Done a pull request for this one :-)
Thanks!
