### ISSUE TITLE
Hacktoberfest - LakeFS

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#670]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : LakeFS

Q. Where have you seen the announcement (URL)?  
A. : https://github.com/treeverse/lakeFS#get-ready-for-hacktoberfest https://twitter.com/lakeFS/status/1308374824528601088

Q. What kind of swag (clothing, stickers, ...)?  
A. : stickers, clothing

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by keivalya** [comment]
This is my first HacktoberFest. I'll be happy if I could contribute.

**Comment by achaljhawar** [comment]
@aslafy-z assign it to me

**Comment by dashang** [comment]
what has to be done in this?

**Comment by varunseth5788** [comment]
i would like to contribute to this issue.
or need any other help.

**Comment by Gurpreet-2602** [comment]
how can i contribute to it??

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
