### ISSUE TITLE
IHP - Integrated Haskel Platform

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#675]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : IHP (Integrated Haskel Platform)

Q. Where have you seen the announcement (URL)?  
A. : https://github.com/digitallyinduced/ihp#ihp-stickers
 

Q. What kind of swag (clothing, stickers, ...)?  
A. : stickers

Fill the form or write an email to hi@digitallyinduced.com

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by HellBender2011** [comment]
assign to me
