### ISSUE TITLE
Hasura Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#677]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Hasura

Q. Where have you seen the announcement (URL)?  
A. : https://hasura.io/blog/the-hasura-hacktoberfest-fiesta-build-a-supergraph-and-win-1000/

Q. What kind of swag (clothing, stickers, ...)?  
A. : ?

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by HellBender2011** [comment]
assign to me

**Comment by aslafy-z** [comment]
I updated the link in the issue. Feel free to open an issue!
