### ISSUE TITLE
Circle-CI Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#679]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Circle-CI

Q. Where have you seen the announcement (URL)?  
A. : https://hacktoberfest.circleci.com/

Q. What kind of swag (clothing, stickers, ...)?  
A. : t-shirt, stickers

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by Ameenrehman** [comment]
can you please tell me what we need to do in this issue

**Comment by vikaspotluri123** [comment]
@Ameenrehman you need to complete steps 2-5 from here:

https://github.com/swapagarwal/swag-for-dev/blob/master/CONTRIBUTING.md#how-do-i-add-a-swag-opportunity

**Comment by HellBender2011** [comment]
assign to me
