### ISSUE TITLE
Globo Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#680]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Globo

Q. Where have you seen the announcement (URL)?  
A. : https://opensource.globo.com/hacktoberfest/

Q. What kind of swag (clothing, stickers, ...)?  
A. : t-shirt

Q. Does it ship worldwide?  
A. : No, Brazil only

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by avantikasparihar** [comment]
Hey, can I work on this one?

**Comment by HellBender2011** [comment]
assign to me

**Comment by 5usana** [comment]
hi, i'd love a chance to tackle this issue if it's still needing attention!

**Comment by aslafy-z** [comment]
Hello, 
Hacktoberfest 2020 is over. You can still contribute to the overall website if you want so.
Regards,
