### ISSUE TITLE
MayaData Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#684]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : MayaData

Q. Where have you seen the announcement (URL)?  
A. : https://blog.mayadata.io/celebrate-hacktoberfest-2020-open-source-with-mayadata

Q. What kind of swag (clothing, stickers, ...)?  
A. : t-shirt

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by rmorabia** [comment]
Happy to take this on
