### ISSUE TITLE
Strawberry GraphQL Hacktoberfest

### ISSUE THREAD

**Issue by iTechsTR** [swapagarwal/swag-for-dev#690]
## Wild swag opportunity appeared!

- [X] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Strawberry GraphQL

Q. Where have you seen the announcement (URL)?  
A. : https://twitter.com/patrick91/status/1310931830695235584

Q. What kind of swag (clothing, stickers, ...)?  
A. : Stickers

Q. Have you received swag from this?  
A. : -

Q. How long did it take?  
A. : -

Q. Does it ship worldwide?  
A. : Yes

- [X] I've checked that the promotion is legit.
- [X] I've checked that it's still available to the public.

**Comment by HellBender2011** [comment]
assign to me

**Comment by prajalsharma** [comment]
assign to me

**Comment by Amritanshu02** [comment]
Hello ! I would like to work on this issue. Could you help me where to start?
