### ISSUE TITLE
Container Solutions Hacktoberfest

### ISSUE THREAD

**Issue by iTechsTR** [swapagarwal/swag-for-dev#691]
## Wild swag opportunity appeared!

- [X] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Container Solutions

Q. Where have you seen the announcement (URL)?  
A. : https://blog.container-solutions.com/container-solutions-does-hacktoberfest

Q. What kind of swag (clothing, stickers, ...)?  
A. : T-Shirt

Q. Have you received swag from this?  
A. : -

Q. How long did it take?  
A. : -

Q. Does it ship worldwide?  
A. : Yes

- [X] I've checked that the promotion is legit.
- [X] I've checked that it's still available to the public.

**Comment by HellBender2011** [comment]
assign to me
