### ISSUE TITLE
Update PR template

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#70]
It would be great to include company name, reference url and associated image right in the PR body. It's pretty annoying to have to open readme/data.json to get the swag details !

```diff
 - [ ] I've checked that this isn't a duplicate pull request.

Is it regarding a new swag proposal or something else?  
Fill the corresponding section below:

(New Swag Proposal)  
+ Company:
+ Reference URL: 
Q. Have you received swag from this?  
Q. How long did it take?  
Q. Does it ship worldwide?  

(Something else)  
Please describe your changes here: 
```

Something like this should be enouth

**Comment by swapagarwal** [comment]
Makes sense.

**Comment by aslafy-z** [comment]
GitHub now supports settings title and more in issue template 
https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/#adding-an-issue-template

**Comment by swapagarwal** [comment]
The label thing seems pretty useful.
