### ISSUE TITLE
Indeed Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#705]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Indeed

Q. Where have you seen the announcement (URL)?  
A. : https://engineering.indeedblog.com/indeed-hacktoberfest-2020/

Only shipping to US.

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by yash-m-agarwal** [comment]
Hi, @aslafy-z I want to take up this issue. Can you please elaborate on the task?

**Comment by aslafy-z** [comment]
@swapagarwal @vikaspotluri123 this does not ship worldwide, should we add it anyway?

Hello @yash-m-agarwal. You can follow steps 2-5 of this guide https://github.com/swapagarwal/swag-for-dev/blob/master/CONTRIBUTING.md#how-do-i-add-a-swag-opportunity to add this entry to the website.
You can also use Gitpod to do the change: https://github.com/swapagarwal/swag-for-dev/blob/master/CONTRIBUTING.md#start-one-click-with-gitpod

**Comment by yash-m-agarwal** [comment]
Thank you, I am taking up this issue and will send a PR for the same.
