### ISSUE TITLE
Jenkins Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#706]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Jenkins

Q. Where have you seen the announcement (URL)?  
A. : https://www.jenkins.io/events/hacktoberfest/

See https://www.jenkins.io/events/hacktoberfest/faq/#does-jenkins-project-send-special-swag

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by rmorabia** [comment]
Happy to take this one.

**Comment by HellBender2011** [comment]
assign to me
