### ISSUE TITLE
Hasura Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#708]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Hasura

Q. Where have you seen the announcement (URL)?  
A. : https://hasura.io/blog/hasura-joins-hacktoberfest-3rd-year-in-a-row/

Q. What kind of swag (clothing, stickers, ...)?  
A. : surprise, stickers

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by lucasqueiroz** [comment]
I'd like to take this one if it's not already claimed! :)
