### ISSUE TITLE
Tripal Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#709]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Tripal

Q. Where have you seen the announcement (URL)?  
A. : https://tripal.info/news/tripal-hacktoberfest-2020

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by avantikasparihar** [comment]
Hey, can I work on this one?

**Comment by aslafy-z** [comment]
Sure, go on!

**Comment by shindodkar** [comment]
Hi, I am new to open source project so would you like to give me some instruction like which file to make changes. I would gladly like to work on this project😊👍

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
