### ISSUE TITLE
MS Ignite Cloud

### ISSUE THREAD

**Issue by will-chow** [swapagarwal/swag-for-dev#712]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. :  Microsoft

Q. Where have you seen the announcement (URL)?  
A. :  https://csc.docs.microsoft.com/ignite/registration 

Q. What kind of swag (clothing, stickers, ...)?  
A. :  Earn a free Microsoft Certification exam and chances to win more prizes

Q. Have you received swag from this?  
A. :  Yes 

Q. How long did it take?  
A. :  One or more days

Q. Does it ship worldwide?  
A. :  Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by will-chow** [comment]
Please assign to me, thanks!

**Comment by vikaspotluri123** [comment]
This opportunity no longer exists
