### ISSUE TITLE
SpecFlow contributor package

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#716]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : SpecFlow

Q. Where have you seen the announcement (URL)?  
A. : https://specflow.org/contributer-package/
https://specflow.org/blog/hacktoberfest-2020-starts-soon/

Q. What kind of swag (clothing, stickers, ...)?  
A. : stickers

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by HellBender2011** [comment]
assign to me
