### ISSUE TITLE
DevFolio Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#717]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : DevFolio

Q. Where have you seen the announcement (URL)?  
A. : https://devfolio.co/blog/devfolio-hacktoberfest-2020/

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing, stickers

Q. Does it ship worldwide?  
A. : No, only India

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by ShivamPorwal02** [comment]
Can i work on this one?

**Comment by achaljhawar** [comment]
can I work on this one @aslafy-z

**Comment by RiyaMindhe23** [comment]
Can I work on this ?

**Comment by gitPiyushhh** [comment]
I want to work on this

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
