### ISSUE TITLE
OpenEBS hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#718]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : OpenEBS

Q. Where have you seen the announcement (URL)?  
A. : https://openebs.io/blog/hacktoberfest-2020-contribute-to-openebs/

Q. What kind of swag (clothing, stickers, ...)?  
A. : ❓ 

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by dennisgon** [comment]
can I  work for this one?
