### ISSUE TITLE
Mattermost swag for first-timers

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#719]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Mattermost

Q. Where have you seen the announcement (URL)?  
A. : https://mattermost.com/blog/hacktoberfest-2020/

Q. What kind of swag (clothing, stickers, ...)?  
A. : mug

- [X] I've checked that the promotion is legit.
- [X] I've checked that it's still available to the public.

**Comment by vikaspotluri123** [comment]
This was completed in #723

**Comment by yogeshsingh101200** [comment]
@vikaspotluri123 it's okay.
