### ISSUE TITLE
DX Heroes Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#720]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : DX Heroes

Q. Where have you seen the announcement (URL)?  
A. : https://github.com/DXHeroes/dx-scanner#hacktoberfest-2020-

Q. What kind of swag (clothing, stickers, ...)?  
A. : ❓ 

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by yogeshsingh101200** [comment]
Can I work on this one?

**Comment by achaljhawar** [comment]
please assign it to me I have resolved it in #772
