### ISSUE TITLE
Earthly Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#721]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Earthly

Q. Where have you seen the announcement (URL)?  
A. : https://blog.earthly.dev/hacktoberfest-2020/

Q. What kind of swag (clothing, stickers, ...)?  
A. : stickers

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by MaximeKoitsalu** [comment]
What is the issue about 😅?

**Comment by aslafy-z** [comment]
Hello @MaximeKoitsalu. The point is adding this entry to the swag list. You can follow steps 2-5 of this guide https://github.com/swapagarwal/swag-for-dev/blob/master/CONTRIBUTING.md#how-do-i-add-a-swag-opportunity to add this entry to the website.
You can also use Gitpod to do the change: https://github.com/swapagarwal/swag-for-dev/blob/master/CONTRIBUTING.md#start-one-click-with-gitpod

Let me know if you want to work on this.

**Comment by MaximeKoitsalu** [comment]
Thanks for the clarification! I'll leave this issue to someone else 😊

**Comment by panda311** [comment]
Hey @aslafy-z , Would be happy to take this one ...

**Comment by HellBender2011** [comment]
assign this to me

**Comment by aslafy-z** [comment]
@HellBender2011 this issue is already assigned. Feel free to take another one.

**Comment by achaljhawar** [comment]
please assign it to me I have resolved it in #772
