### ISSUE TITLE
Operation Code Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#722]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Operation Code

Q. Where have you seen the announcement (URL)?  
A. : https://github.com/OperationCode/START_HERE#-prizes-

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing, stickers

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by Vipul-Bajaj** [comment]
Can I work on this one?

**Comment by Vipul-Bajaj** [comment]
There is an existing entry for OperationCode for last's year hacktoberfest, should I modify that or create a new entry for this one?

**Comment by vikaspotluri123** [comment]
Please modify the existing opportunity 😄
