### ISSUE TITLE
7PHP Freeze Offer of Free Sticker

### ISSUE THREAD

**Issue by dennisgon** [swapagarwal/swag-for-dev#727]
## Issue with an existing swag opportunity

- [x] I've checked that this isn't a duplicate issue.

Q. Which opportunity?  
A. :  7PHP freeze their offer of free sticker

According to the 7PHP website, 7PHP freeze their offer of free sticker starting from 2020.04.01 until further notice

**Comment by HellBender2011** [comment]
😅 so what actually I have to do, is this an issue I can create a pr to ?

**Comment by HellBender2011** [comment]
assign to me
