### ISSUE TITLE
AquaSec Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#733]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : AquaSec

Q. Where have you seen the announcement (URL)?  
A. : https://blog.aquasec.com/hacktoberfest-2020-aqua-open-source

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing, stickers

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aryan040501** [comment]
Hi, I don't understand what I have to do in this?
