### ISSUE TITLE
Archives space Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#734]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : ArchivesSpace

Q. Where have you seen the announcement (URL)?  
A. : https://archivesspace.org/archives/6563

Not sure about this one...

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by Archis19** [comment]
Assign me this one please!

**Comment by aslafy-z** [comment]
Please wait until we validated it, if it passes, I'll assign it to you :thumbup:

@vikaspotluri should we close this as for others?

**Comment by vikaspotluri123** [comment]
Yeah, I think so - it's another be the best and we'll give you something opportunity
