### ISSUE TITLE
Appsmith Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#744]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : AppSmith

Q. Where have you seen the announcement (URL)?  
A. : https://github.com/appsmithorg/appsmith/discussions/863

Q. What kind of swag (clothing, stickers, ...)?  
A. : stickers, clothing, device

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by jmakhack** [comment]
Hey @aslafy-z, I can pick this one up. Can you assign it to me?
