### ISSUE TITLE
Switchblade Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#746]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Switchblade

Q. Where have you seen the announcement (URL)?  
A. : https://github.com/SwitchbladeBot/switchblade/issues/1203

Q. What kind of swag (clothing, stickers, ...)?  
A. : stickers

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by SuzannaWentzel** [comment]
Hi, I'm new to open source, but I'd like to give this one a try! Could you assign me to this one?
