### ISSUE TITLE
New Page Idea: devswag.io/hacktoberfest

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/swag-for-dev#75]
There are quite a lot of interesting hacktoberfest swag opportunities this year! I was thinking of having a quick way to access them.
What do you guys think of having a new page `/hacktoberfest` specifically for this purpose?

**Comment by aslafy-z** [comment]
I think it would be great. We will have to add labels to the swags to do so, right ?

**Comment by Jacob8765** [comment]
Would they still be visible on the main page, or would they only be accessible from the hacktoberfest page?

**Comment by plibither8** [comment]
It's a great idea, but, how are we going to _advertise_ it? Since this is a limited-time page, would the amount a traffic visiting that /hacktoberfest vs traffic visiting the main page be worth it? Just wondering

**Comment by zac-garby** [comment]
> Would they still be visible on the main page, or would they only be accessible from the hacktoberfest page?

They should definitely be visible on both pages.

**Comment by swapagarwal** [comment]
@aslafy-z Yes, we would need to add labels for this.
@Jacob8765 @zac-garby Everything would be visible on main page; filtered swag on hacktoberfest page for quick access. (Same can be achieved by adding a `show only hacktoberfest opportunities` checkbox on the main page but having a new page makes sharing easier.)
@plibither8 A button can be shown on main page linking to the hacktoberfest page. (Just thinking out loud here)

**Comment by plibither8** [comment]
> Yes, we would need to add labels for this.

I'm guessing labels in the data.json file, right?

**Comment by Jacob8765** [comment]
Maybe instead of adding a new page, it would be easier to use a URL query - something like devswag.io?filter=hacktoberfest.

**Comment by darshkpatel** [comment]
IMHO We can just have a hacktoberfest filter on the main page.

Also can have something like devswag.io/filter=hacktoberfest , in case we
need a sharable link

**Comment by swapagarwal** [comment]
@Jacob8765 @darshkpatel Makes sense.

**Comment by plibither8** [comment]
Should I start work on this?

**Comment by aslafy-z** [comment]
@plibither8 I think it would be better to add something like 
```diff
labels: ['hacktoberfest'],
```
To the data.json file as we could have other categories in the future

**Comment by plibither8** [comment]
That's a good idea, I'll initialise all swag items with an empty `labels` array, except the hacktoberfest ones

**Comment by swapagarwal** [comment]
Sure, go ahead!
How about using `tags` instead of `labels`?

**Comment by Jacob8765** [comment]
I can probably help implement this if you want

**Comment by plibither8** [comment]
@Jacob8765 @aslafy-z @swapagarwal I've just created the PR. Suggestions?

**Comment by swapagarwal** [comment]
This functionality is now live at https://devswag.io/?tags=hacktoberfest
Cheers! 🎉
