### ISSUE TITLE
Uno Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#754]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Uno

Q. Where have you seen the announcement (URL)?  
A. : https://platform.uno/blog/hacktoberfest-2020-contribute-to-uno-to-win-online-courses-and-t-shirts/

Q. What kind of swag (clothing, stickers, ...)?  
A. :  Udemy courses / enter in a draw to win a t-shirt

@vikaspotluri123 not sure if we should add this one

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by vikaspotluri123** [comment]
I don't think we should since it's a "win" op

**Comment by aslafy-z** [comment]
Ok!
