### ISSUE TITLE
Xamarin Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#755]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Xamarin (Microsoft)

Q. Where have you seen the announcement (URL)?  
A. : https://devblogs.microsoft.com/xamarin/hacktoberfest-xamarin-community-toolkit/

Q. What kind of swag (clothing, stickers, ...)?  
A. : undisclosed

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by Archis19** [comment]
can you please assign me this

**Comment by achaljhawar** [comment]
please assign it to me I have resolved it in #772

**Comment by aslafy-z** [comment]
@Archis19 I'll reassing this to @achaljhawar since he made a PR for it.

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
