### ISSUE TITLE
Ensure mime type of image resources

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#761]
Add test that checks if the image field is an accepted image format: https://sharp.pixelplumbing.com/#formats

**Comment by ritesh-pandey** [comment]
Can you share a link which has broken/non-acceptable format image?

**Comment by aslafy-z** [comment]
You can find some in this PR: https://github.com/swapagarwal/swag-for-dev/pull/736

**Comment by ritesh-pandey** [comment]
I am new to writing tests.

Here is how I plan to do it:
1. Read image via `got` (as `sharp` cannot open remote files)
2. Initialize `sharp` instance with above image. Use `Buffer` to minimize I/O
3. Try to convert image to `sharp` buffer. If the image is of incorrect mime type, this will raise an error.

Please let me know if I am on right track.
