### ISSUE TITLE
Update repository topics

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#762]
Add `hacktoberfest` topic to this repository so PRs counts. See https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by vikaspotluri123** [comment]
I'm not sure when it was done, but it's done

![image](https://user-images.githubusercontent.com/4383564/95021458-c2bb7d80-0636-11eb-8c5a-c0e7f4af6c35.png)

**Comment by swapagarwal** [comment]
Just added a few minutes ago. 😅
