### ISSUE TITLE
Zup IT Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#768]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Zup IT

Q. Where have you seen the announcement (URL)?  
A. : http://insights.zup.com.br/hacktoberfest

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing

Q. Have you received swag from this?  
A. : 

Q. How long did it take?  
A. : 

Q. Does it ship worldwide?  
A. : only Brazil

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by achaljhawar** [comment]
assign it to me @aslafy-z

**Comment by thekavikumar** [comment]
assign it to me @thekavikumar

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
