### ISSUE TITLE
BotKube Sticker and Tshirts for Hacktoberfest

### ISSUE THREAD

**Issue by chetanpdeshmukh** [swapagarwal/swag-for-dev#771]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. :  InfraCloud Technologies

Q. Where have you seen the announcement (URL)?  
A. :  https://www.infracloud.io/blogs/infracloud-joins-hacktoberfest-2020/

Q. What kind of swag (clothing, stickers, ...)?  
A. : Stickers
![Botkube sticker_gray](https://user-images.githubusercontent.com/60215917/95586492-62757300-0a5e-11eb-80dd-2bb30f117a56.png)

and Tshirts
![Botkube](https://user-images.githubusercontent.com/60215917/95586274-175b6000-0a5e-11eb-8487-c73e4f900571.jpg)

Q. Have you received swag from this?  
A. :  not yet (contributors who're participating in hacktoberfest and successfully able to merge PRs are eligible for swags)

Q. How long did it take?  
A. :  N.A.
Q. Does it ship worldwide?  
A. :  yes

category-  Hacktoberfest

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
Duplicate #681 
Already implemented in #701
