### ISSUE TITLE
Hacktoberfest with DeepSource

### ISSUE THREAD

**Issue by saif-deepsource** [swapagarwal/swag-for-dev#773]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : DeepSource

Q. Where have you seen the announcement (URL)?  
A. : https://deepsource.io/hacktoberfest/

Q. What kind of swag (clothing, stickers, ...)?  
A. : Open Source Grants

Q. Have you received swag from this?  
A. : 

Q. How long did it take?  
A. : 

Q. Does it ship worldwide?  
A. : 

Landing page: https://deepsource.io/hacktoberfest/ 

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
