### ISSUE TITLE
ActiveLoop Hactoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#774]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : ActiveLoop

Q. Where have you seen the announcement (URL)?  
A. : http://activeloop.ai/hacktoberbest

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by Kritip123** [comment]
### @aslafy-z 
I am working on this issue.

**Comment by aslafy-z** [comment]
I assigned you @Kritip123, however it looks like this company is not giving swag anymore. Can you check?

**Comment by Kritip123** [comment]
Even I am not able to find anything from their site but goodies are mentioned on the Hacktoberfest website. I also do not know much about it. Sending a pull request for the same by the way.

**Comment by aslafy-z** [comment]
I will close that one since there was no update to their offering for this year. Let's keep an eye on it.
