### ISSUE TITLE
Crio Hacktoberfest

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#775]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Crio

Q. Where have you seen the announcement (URL)?  
A. : https://www.crio.do/IBelieveInDoing/October/

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by Cosmeeeen** [comment]
I'm working on this!

**Comment by cptcrunchy** [comment]
There is an error with this link.
page resources for /IBelieveInDoing/October/ not found.

No 404 page as this is a missing React route.

Thoughts?

**Comment by harshkhodiar03** [comment]
There is an error with this link.
page resources for /IBelieveInDoing/October/ not found.

No 404 page as this is a missing React route.

Thoughts
