### ISSUE TITLE
Add Crio.do in the list !

### ISSUE THREAD

**Issue by sudhanshutiwari264** [swapagarwal/swag-for-dev#789]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : CrioDo

Q. Where have you seen the announcement (URL)?  
A. : https://www.crio.do/ibelieveindoing

Q. What kind of swag (clothing, stickers, ...)?  
A. : Clothing(T-shirts), stickers, and scholarships 

Q. Have you received swag from this?  
A. : 

Q. How long did it take?  
A. : Within 8 weeks of winning it!

Q. Does it ship worldwide?  
A. : No, Swags are for India only but scholarships are for all 

Swags are only given to the participants of the #IbelieveinDoing series!
[Register here](https://www.crio.do/ibelieveindoing)
and registration are open throughout the month !

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
This seems to be a more community-oriented swag offering. I think we should focus on swag offerings designed explicitly for individual contributors 🤔
