### ISSUE TITLE
Add automated tests

### ISSUE THREAD

**Issue by aslafy-z** [swapagarwal/swag-for-dev#79]
Need to check that

- code is linted
- the site builds
- data.json is well formated 
- data.json links are not dead 

What else ?

**Comment by swapagarwal** [comment]
I was thinking along those lines too!

**Comment by aslafy-z** [comment]
I seen this,

![2018-10-04-124736_174x47_scrot](https://user-images.githubusercontent.com/8191198/46469440-b4ca8c00-c7d3-11e8-942f-f6638d98bc22.png)

Are you using it Codeship ? Should we use it or another one (TravisCI, CircleCI, another one) ?
Could you grant me a read access to it (or turn it public) ?

**Comment by aslafy-z** [comment]
Some visual testing materials:
- https://percy.io/
- https://github.com/apps/reg-suit
- https://applitools.com/
- https://github.com/mojoaxel/awesome-regression-testing

**Comment by swapagarwal** [comment]
Yes, I was using CodeShip to test that the links are not dead. Since now we have a visual testing requirement, we'll need to explore the various options available. 😃

**Comment by swapagarwal** [comment]
Copied from #82 
`We need to have a test framework (not needed but better), add a test case for each platform we want to test on and use a CI to trigger them. As seen there: https://www.browserstack.com/automate/node#testing-frameworks`

**Comment by swapagarwal** [comment]
@vikaspotluri123 See if you get time?

**Comment by swapagarwal** [comment]
Closed in #228

**Comment by vikaspotluri123** [comment]
Did we want to add visual testing?

**Comment by swapagarwal** [comment]
It's probably over-engineering at this point. 😅
The most active time is October only, and the rest of the year is pretty much unhappening (as we saw last year!).
