### ISSUE TITLE
Add difficulty tags

### ISSUE THREAD

**Issue by eindiran** [swapagarwal/swag-for-dev#8]
It would be pretty helpful if there was a set of tags which listed the approximate difficulty of the tasks required to earn the swag. The tags could perhaps show how long the task would take or if the task was 'easy', 'medium' or 'hard'. At a minimum, the tag could show whether the task requires a non-trivial amount of programming to complete.

For example, the current Digital Ocean survey would get marked 'easy' as it can be finished approximately 10 minutes. The Hacktoberfest requirements would be marked as 'hard' as you have to write 4 separate PRs.

**Comment by swapagarwal** [comment]
Makes sense!
I was thinking along these lines when I started the list, but it was pretty small back then so didn't pursue it. 😅

**Comment by kevin51jiang** [comment]
Easy/med/hard would probably be the way to go because for a challenge like the google home, there's no telling how much time you need to spend on your applicaton.

**Comment by romangraef** [comment]
If we add the easy/med/hard, i would find it cool if we add badges in the style of https://shields.io e.g. [DIFFICULTY|EASY/MEDIUM/HARD] on green/orange/red background

**Comment by swapagarwal** [comment]
I'm in for shields.io styled badges!

**Comment by eindiran** [comment]
Those look great!

**Comment by swapagarwal** [comment]
Anyone wanna give an initial try on sorting the current list into these categories?
