### ISSUE TITLE
Add Mattermost to the list 

### ISSUE THREAD

**Issue by Jassi10000-zz** [swapagarwal/swag-for-dev#818]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Mattermost 

Q. Where have you seen the announcement (URL)?  
A. : https://forum.mattermost.org/t/limited-edition-mattermost-mugs/143

Q. What kind of swag (clothing, stickers, ...)?  
A. : Mug

Q. Have you received swag from this?  
A. : My friend got one

Q. How long did it take?  
A. : Approx 2 months

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
Hello,
We already have this opportunity but it was linked to hacktoberfest and automatically disabled.
Can you open a pull request to remove the `hacktoberfest` and `expired` tags? 
https://github.com/swapagarwal/swag-for-dev/blob/master/data.json#L432

**Comment by Jassi10000** [comment]
@aslafy-z  Ya sure

**Comment by aslafy-z** [comment]
fixed with https://github.com/swapagarwal/swag-for-dev/commit/c88312b9775582ee2dec3bff8bc5ca1005c14a0a
