### ISSUE TITLE
Bug: Website layout broken on mobile devices

### ISSUE THREAD

**Issue by plibither8** [swapagarwal/swag-for-dev#82]
- [x] I've checked that this isn't a duplicate issue.

The website layout is broken after the addition of the description. I've attached a screenshot:

![screenshot_20181004-141152](https://user-images.githubusercontent.com/31861755/46462859-20b2f180-c7e0-11e8-89e6-b0a44c190a92.png)

This is because of the flex display set on the div, which has been given a height of 40vh (to center the title and subtitle). We should consider removing the height attribute (or at least make it min-height).

**Comment by swapagarwal** [comment]
Ah, a classic case of it works on my machine (or in this case, my mobile).

![](https://dl2.pushbulletusercontent.com/X9htuza754xlIv6pDZ5jRVnw50Tza5rU/Screenshot_20181004-142527.jpg)

**Comment by hugovk** [comment]
Also broken for me (Chrome, Android).

**Comment by swapagarwal** [comment]
Oops. Is there a way to catch such things in development itself?

**Comment by aslafy-z** [comment]
Yep we could use tools like browserstack to check this kind of errors, at
ci time.
We need to create a ci pipeline (codeship is in the badges?).

Le jeu. 4 oct. 2018 à 11:03, Swapnil Agarwal <notifications@github.com> a
écrit :

**Comment by plibither8** [comment]
@swapagarwal what I do is open Chrome Dev Tools and enable responsive screen. There we are given the option of simulating mobile displays of various smartphones in the market currently.

**Comment by swapagarwal** [comment]
@aslafy-z I signed up for BrowserStack. How does it exactly fit into picture? Do we write a selenium test script and run it on different screen sizes? Or something else?

**Comment by aslafy-z** [comment]
We need to have a test framework (not needed but better), add a test case for each platform we want to test on and use a CI to trigger them. 
As seen there: https://www.browserstack.com/automate/node#testing-frameworks
Maybe we can discuss this on #79.

**Comment by swapagarwal** [comment]
@plibither8 Is this still an issue?

**Comment by plibither8** [comment]
#83 fixes it! Should we merge?

**Comment by swapagarwal** [comment]
I thought the issue was with the banner, no?

**Comment by plibither8** [comment]
Nope, it was because of the title div being set to an absolute height &mdash; nothing to do with the banner 😄

**Comment by plibither8** [comment]
#83 merged
