### ISSUE TITLE
Add opengraph meta tags.

### ISSUE THREAD

**Issue by pulbee** [swapagarwal/swag-for-dev#870]
## Issue regarding the website

The website **dosen't have metadata tags (OpenGraph)**, when it should be, It would be great for users to be able to **preview the website** messaging when shared across social networks.

**Comment by pulbee** [comment]
#871 I've added the meta tags

**Comment by pulbee** [comment]
#871

**Comment by aslafy-z** [comment]
Duplicate https://github.com/swapagarwal/swag-for-dev/issues/870
