### ISSUE TITLE
Bridgecrew

### ISSUE THREAD

**Issue by paulmowat** [swapagarwal/swag-for-dev#879]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Bridgecrew 

Q. Where have you seen the announcement (URL)?  
A. : https://bridgecrew.io/blog/happy-hacktoberfest-2021/

Q. What kind of swag (clothing, stickers, ...)?  
A. : 1 PR for Stickers, 2+ For Swag Pack of stickers and t-shirt

Q. Have you received swag from this?  
A. : Not Yet - PR pending review

Q. How long did it take?  
A. : Few hours work

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by akshitarora921** [comment]
Can I work on this?

**Comment by paulmowat** [comment]
I've already done it. PR just waiting to be reviewed and merged.

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
