### ISSUE TITLE
Blitz.js free stickers

### ISSUE THREAD

**Issue by martinsaxa** [swapagarwal/swag-for-dev#881]
## Wild swag opportunity appeared!

- [x ] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Prisma

Q. Where have you seen the announcement (URL)?  
A. : https://blitzjs.com/stickers

Q. What kind of swag (clothing, stickers, ...)?  
A. : stickers

Q. Have you received swag from this?  
A. : no

Q. How long did it take?  
A. : n/a

Q. Does it ship worldwide?  
A. : yes

- [ x] I've checked that the promotion is legit.
- [ x] I've checked that it's still available to the public.

**Comment by hyperhtml** [comment]
Added blitz.js stickers a PR #882

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
