### ISSUE TITLE
Mattermost Hacktoberfest bluetooth mechanical keyboard

### ISSUE THREAD

**Issue by piechowiakmichal** [swapagarwal/swag-for-dev#890]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Mattermost

Q. Where have you seen the announcement (URL)?  
A. : https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/hacktoberfest2021

Q. What kind of swag (clothing, stickers, ...)?  
A. : Mattermost Hacktoberfest bluetooth mechanical keyboard

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : All October (Hacktoberfest)

Q. Does it ship worldwide?  
A. : Yes

"We will select 1 MVP from each project listed above to receive an exclusive Mattermost Hacktoberfest bluetooth mechanical keyboard!
 - Board: Epomaker GK61XS Hot Swap Dual Wireless/Wired RGB
- Switch: Gateron Yellow Lubed with Krytox 205g0
- Switch Spring lubed with Krytox GPL 105
- Stabilizer clipped and lubed with Krytox XHT-BDZ
- Case Foam modded
- HK Gaming Halloween Edition ABS Pudding Keycaps"

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by piechowiakmichal** [comment]
Hi, can I add it?

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
