### ISSUE TITLE
MindsDB

### ISSUE THREAD

**Issue by ZoranPandovski** [swapagarwal/swag-for-dev#892]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : MindsDB

Q. Where have you seen the announcement (URL)?  
A. : https://mindsdb.com/hacktoberfest/

Q. What kind of swag (clothing, stickers, ...)?  
A. : Clothing, Stickers, Laptop

Q. Have you received swag from this?  
A. : Yes

Q. How long did it take?  
A. : 1 month

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
Added with #1084
