### ISSUE TITLE
Linkerd

### ISSUE THREAD

**Issue by aliariff** [swapagarwal/swag-for-dev#896]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Linkerd

Q. Where have you seen the announcement (URL)?  
A. : https://linkerd.io/dashboard/have-you-adopted-linkerd-let-us-know-and-we-ll-send-you-some-sweet-swag/

Q. What kind of swag (clothing, stickers, ...)?  
A. : clothing, stickers

Q. Have you received swag from this?  
A. : yes

Q. How long did it take?  
A. : few weeks

Q. Does it ship worldwide?  
A. : yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
