### ISSUE TITLE
Liquibase Swags

### ISSUE THREAD

**Issue by rakhi-agrawal** [swapagarwal/swag-for-dev#898]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Liquibase

Q. Where have you seen the announcement (URL)?  
A. : https://www.liquibase.org/community/liquibase-legends

Q. What kind of swag (clothing, stickers, ...)?  
A. : Clothing, stickers

Q. Have you received swag from this?  
A. : No, my swags are shipped. I'm yet to receive them.

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
