### ISSUE TITLE
Add MongoDB HacktoberFest swag

### ISSUE THREAD

**Issue by emiliano-carrillo** [swapagarwal/swag-for-dev#90]
- [ ] I've checked that this isn't a duplicate issue.

Is it regarding the current promotions or something new? Yes
Fill the corresponding section below:
Mongo DB Swag

Reference:
[Link](https://www.mongodb.com/blog/post/welcome-to-hacktoberfest-2018)

Reference Link:
- [ ] I've confirmed that the promotion is legit.
- [ ] I've verified that it's still available to the public.

**Comment by darshkpatel** [comment]
It's more like a competition i believe

**Comment by swapagarwal** [comment]
Thanks @emiliano-carrillo for taking the time to report this.
I agree with @darshkpatel that it's more of a competition rather than swag for all, hence closing this.
