### ISSUE TITLE
CockroachLabs Swag

### ISSUE THREAD

**Issue by rakhi-agrawal** [swapagarwal/swag-for-dev#900]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : CockroachLabs University

Q. Where have you seen the announcement (URL)?  
A. : https://www.tosscall.com/soloblog/506/Cockroach-University-Free-Course

Q. What kind of swag (clothing, stickers, ...)?  
A. : Clothing

Q. Have you received swag from this?  
A. : Yes

Q. How long did it take?  
A. : 30-40 days

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by prathikshetty2002** [comment]
Hi rakhi, do we need to complete all the courses like mentioned in the blog or any course? and about final exam is it like cummulatively or course oriented ?

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
