### ISSUE TITLE
Bagisto swag

### ISSUE THREAD

**Issue by Dahbaeraychy** [swapagarwal/swag-for-dev#902]
## Wild swag opportunity appeared!

- [ x ] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Bagisto

Q. Where have you seen the announcement (URL)?  
A. : https://webkul.com/meetups/hacktober-fest-bagisto-2021/

Q. What kind of swag (clothing, stickers, ...)?  
A. : Stickers, Stationery  

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : 

Q. Does it ship worldwide?  
A. : Yes

- [ x ] I've checked that the promotion is legit.
- [ x ] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
