### ISSUE TITLE
codedamn - Build a project and win t-shirt! 

### ISSUE THREAD

**Issue by mayankchaudhary26** [swapagarwal/swag-for-dev#904]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. :  codedamn

Q. Where have you seen the announcement (URL)?  
A. :  https://codedamn.com/projects

Q. What kind of swag (clothing, stickers, ...)?  
A. :  tshirt

Q. Have you received swag from this?  
A. :  waiting list

Q. How long did it take?  
A. :  few days to approve your PR

Q. Does it ship worldwide?  
A. :  India only

Codedamn brings you a collection of projects to build in #hacktoberfest this year. Complete a single project, submit it on our GitHub repository, and win a t-shirt for free!

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
Duplicate #895
