### ISSUE TITLE
swag opportunity

### ISSUE THREAD

**Issue by srishti2609** [swapagarwal/swag-for-dev#920]
## Wild swag opportunity appeared!

- [ ] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. :  codedamn

Q. Where have you seen the announcement (URL)?  
A. : https://codedamn.com/projects

Q. What kind of swag (clothing, stickers, ...)?  
A. : tshirt

Q. Have you received swag from this?  
A. : waiting

Q. How long did it take?  
A. : few days after your approval

Q. Does it ship worldwide?  
A. : 

Q. your reaction wow or wowww? -->
A. Wowww

- [ ] I've checked that the promotion is legit.
- [ ] I've checked that it's still available to the public.

**Comment by soham117** [comment]
@srishti2609  This swag opportunity is over now. It was a hacktoberfest celebration. I got the swag delivered. I request you to close this PR

**Comment by srishti2609** [comment]
Ohk
