### ISSUE TITLE
Robocorp Swag (T-Shirt & Stickers)

### ISSUE THREAD

**Issue by fzs1994** [swapagarwal/swag-for-dev#923]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Robocorp

Q. Where have you seen the announcement (URL)?  
A. : https://robocorp.com/docs/courses/beginners-course/wrapping-up-and-next-steps

Q. What kind of swag (clothing, stickers, ...)?  
A. : T-shirt & Stickers

Q. Have you received swag from this?  
A. : Ordered

Q. How long did it take?  
A. : Around 2 Weeks

Q. Does it ship worldwide?  
A. : Yes

Take a quiz, they have very simple questions (You can get answer from the documentation itself) and they will send you course completion certification and once you share that certificate on any social media tagging them, you will get link from them to get free swags.

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by soham117** [comment]
@fzs1994 It is closed now! Kindly close the PR

**Comment by fzs1994** [comment]
Not sure if they still ship those.

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
