### ISSUE TITLE
Jina AI

### ISSUE THREAD

**Issue by ABHIGPT401** [swapagarwal/swag-for-dev#934]
## Issue with an existing swag opportunity

- [x] I've checked that this isn't a duplicate issue.

Q. Which opportunity?  

A. : 
This website has put its swag distribution on hold.  So kindly remove it from the latest page. It is quite misleading.

**Comment by siuting0511** [comment]
<img width="359" alt="Screenshot 2022-03-14 at 9 14 07 AM" src="https://user-images.githubusercontent.com/37100124/158088855-43cdff41-a0cd-44d1-9f2b-e59c67a03724.png">
Hi I am new comer, do you mean the yellow indicator in this card?

**Comment by ABHIGPT401** [comment]
No I meant you should just open the opportunity posted and you'll find that its on hold.

**Comment by soham117** [comment]
@ABHIGPT401 This website is not longer maintained. Most of the opporutinies are outdated.

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
