### ISSUE TITLE
Show tags alphabetically in dropdown

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/swag-for-dev#94]
Currently, `accessories` is shown towards the end while it should be at the start of the list.

**Comment by vikaspotluri123** [comment]
Hint: look at `site/src/pug/includes/body.pug` to see how the tag list is loaded, and make necessary changes to sort the tag list alphabetically

**Comment by swapagarwal** [comment]
@alekangelov Go ahead!

**Comment by swapagarwal** [comment]
@alekangelov Are you working on this?
