### ISSUE TITLE
Feedback on our new public changelog

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/swag-for-dev#95]
I'm playing around with Beamer to announce new features and relevant news.
You can check it out in the bottom-right corner of the website.
Let me know what you think! 🦄

**Comment by sorianog** [comment]
A nice to have: Hover text telling me what the button does. 
Right now I can see myself thinking that it is just notifications about some event on the site. 
Or maybe change the icon to something else? 
![What's New Icon](http://icon-park.com/imagefiles/new_circle_icon_green.png)

**Comment by swapagarwal** [comment]
Here are some of the icons that Beamer provides:
<img width="84" alt="screenshot 2018-10-16 22 41 13" src="https://user-images.githubusercontent.com/2833845/47034536-41daf100-d195-11e8-9a3f-c3e06f0fb060.png">
<img width="83" alt="screenshot 2018-10-16 22 43 50" src="https://user-images.githubusercontent.com/2833845/47034544-47383b80-d195-11e8-9422-02a9b7fcec9c.png">
<img width="90" alt="screenshot 2018-10-16 22 44 59" src="https://user-images.githubusercontent.com/2833845/47034547-4b645900-d195-11e8-91f2-d703ab8ef672.png">
<img width="81" alt="screenshot 2018-10-16 22 45 29" src="https://user-images.githubusercontent.com/2833845/47034549-4d2e1c80-d195-11e8-8cb9-b38b191cfcc0.png">
What one would you prefer?

**Comment by sorianog** [comment]
The megaphone one!!!

**Comment by swapagarwal** [comment]
I was inclined towards that as well! New icon is live on site. 🎉

**Comment by sorianog** [comment]
It looks lovely!! 😍

**Comment by aslafy-z** [comment]
copied from #126, @tannmaysgupta said
> The New to devSwag button isn't very noticeable in the desktop version and at the same time its tooo huge in the mobile version.

**Comment by swapagarwal** [comment]
@tannmaysgupta Thanks for taking the time to report this! 💯
Can you post screenshots? 😇

**Comment by aslafy-z** [comment]
Doing some housekeeping in here. @tannmaysgupta please open a new issue if this is still bothering you.
