### ISSUE TITLE
Twilio Swag

### ISSUE THREAD

**Issue by sank20** [swapagarwal/swag-for-dev#96]
- [x] I've checked that this isn't a duplicate issue.

Is it regarding the current promotions or something new?
Fill the corresponding section below:

(Current Promotion)
Please describe your concern here:
(New Promotion)
On the occasion of Hacktoberfest, @twilio is promoting Open Source as well as the Twilio APIs through a self paced game called TwilioQuest. T-shirt to be won. 
Reference Link: https://www.twilio.com/quest/
- [x] I've confirmed that the promotion is legit.
- [x] I've verified that it's still available to the public.

**Comment by sank20** [comment]
Taking up the task to add it.

**Comment by caseydierking** [comment]
Are you sure they are sending out a shirt themselves too? It isn't clear that they are doing that. It seems like they are just promoting people to participate in Hacktoberfest.

**Comment by sank20** [comment]
@caseydierking I am confident about the t-shirts. Same has been mentioned in a [tweet](https://twitter.com/twilio/status/1049109623532376064). Also, I completed the quest and filled the t-shirt form.

**Comment by aslafy-z** [comment]
Also featured here: https://www.youtube.com/watch?v=r9MPBJjPQdA

**Comment by plibither8** [comment]
Since the t-shirt is just the logo, I think something like this will do OK (after adding some margin):

![image](https://user-images.githubusercontent.com/31861755/46615802-c646c780-cb36-11e8-9f9f-564b07c5b43e.png)

**Comment by caseydierking** [comment]
@sank20  I'll grab the image and add it in here this evening.

**Comment by caseydierking** [comment]
[](url)
<img width="448" alt="screen shot 2018-10-08 at 10 49 14 pm" src="https://user-images.githubusercontent.com/3005311/46645844-770b9180-cb4c-11e8-940c-9f38fba5d299.png">

Didn't turn out quite like i had hoped. Feel free to use if you want.

**Comment by sank20** [comment]
cool, thanks @caseydierking !

**Comment by swapagarwal** [comment]
Thanks @sank20! 👍
