### ISSUE TITLE
Dead ?

### ISSUE THREAD

**Issue by Mikaleb** [swapagarwal/swag-for-dev#960]
## Issue regarding the website

- [ ] I've checked that this isn't a duplicate issue.

 Is the repo dead ?

**Comment by karlrez** [comment]
Is it still possible to run this project locally? After running `npm start` I get two errors:

`Failed downloading https://openbazaar.org/blog/Hacktoberfest-with-OpenBazaar-Help-Make-Trade-Free-Get-Rewards/Hacktoberfest_2018_poster1_1600x850.png [159.46ms]: getaddrinfo ENOTFOUND openbazaar.org
Downloading https://cdn-images-1.medium.com/max/1000/1*xSLmpInA96k9beqMwFPjZQ.jpeg to dist/assets/swag-img/opsdroid.jpeg
`

`Failed downloading https://valor-software.com/assets/images/5d91e2ddd7ccc682175962ea_f27J06AkBW3Dd3pB4fanZWw1sbrhcs-GJCI5H3DgSK_U2R2cbRSAY_-3hTCe75DQU9iMPJpWnJJlSLra_yAyKtPmzmyeUlGVIVlTj2do6t_Y1za0aYfDaTVc8bR6yFgEwNIQ1ZXM.jpeg [191.51ms]: Response code 404 (Not Found)
`

**Comment by aslafy-z** [comment]
Hello,
I cleaned everything up a bit. Please feel free to contribute! :)
