### ISSUE TITLE
MLH Local Hack Day

### ISSUE THREAD

**Issue by namita27** [swapagarwal/swag-for-dev#992]
## Wild swag opportunity appeared!

- [ ] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : Github

Q. Where have you seen the announcement (URL)?  
A. :  https://organize.mlh.io/participants/events/6072-local-hack-day-build#:~:text=Local%20Hack%20Day%3A%20Build%20is,all%20that%20you've%20built.

Q. What kind of swag (clothing, stickers, ...)?  
A. : Stickers

Q. Have you received swag from this?  
A. : No

Q. How long did it take?  
A. : 15-20 days

Q. Does it ship worldwide?  
A. : Yes

- [ ] I've checked that the promotion is legit.
- [ ] I've checked that it's still available to the public.

**Comment by thisisamish** [comment]
I don't understand. What one needs to do here? Is this a feature request, or an issue?

**Comment by aslafy-z** [comment]
This is now expired. Thank you for your participation.
