### ISSUE TITLE
Free stickers(no code) available!!!

### ISSUE THREAD

**Issue by combatantash** [swapagarwal/swag-for-dev#995]
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : RedwoodJS

Q. Where have you seen the announcement (URL)?  
A. : https://redwoodjs.com/stickers

Q. What kind of swag (clothing, stickers, ...)?  
A. : stickers

Q. Have you received swag from this?  
A. : 

Q. How long did it take?  
A. : 

Q. Does it ship worldwide?  
A. : Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

**Comment by aslafy-z** [comment]
This opportunity is already in the list. Thank you for participating.
